// Varsayılan e-posta şablonları. Her kuruma bu katalogdan kopyalanır,
// sonra kurum içeriği serbestçe düzenleyebilir. Dil samimi, iki satıra yayılmış,
// değişkenler doğal cümlelerin içine yerleştirilmiş.
export const emailTemplateCatalog=[
  ['application_received',
    'Başvurunuzu aldık, {{participant.first_name}} 👋',
    'Merhaba {{participant.first_name}},\n{{event.name}} etkinliğine başvurunu aldık. Etkinlik ekibi inceleyip en kısa sürede dönüş yapacak.\nEtkinlik sayfası: {{event.public_url}}'],
  ['registration_confirmed',
    'Kaydınız onaylandı — {{event.name}}',
    'Merhaba {{participant.first_name}},\nHarika haber: {{event.name}} etkinliğine kaydınız onaylandı. Sizi aramızda görmek için sabırsızlanıyoruz.\nEtkinlik {{event.start_date}} tarihinde başlıyor.'],
  ['application_accepted',
    'Hoş geldiniz, {{participant.first_name}}!',
    'Merhaba {{participant.first_name}},\n{{event.name}} başvurunuz kabul edildi, tebrikler!\nEtkinlik {{event.start_datetime}} tarihinde, {{event.location}} adresinde. Detaylar için: {{event.public_url}}'],
  ['application_rejected',
    '{{event.name}} başvuru sonucu',
    'Merhaba {{participant.first_name}},\nBu kez sizi aramıza dahil edemiyoruz, üzgünüz. Kontenjan ve uygunluk kısıtları nedeniyle böyle bir karar vermek zorunda kaldık.\nGelecek etkinliklerde görüşmek dileğiyle.'],
  ['waitlisted',
    'Yedek listedesiniz, {{participant.first_name}}',
    'Merhaba {{participant.first_name}},\n{{event.name}} için yedek listeye alındınız. Kontenjan açılırsa sizi haberdar edeceğiz.\nEtkinlik hakkında bilgi: {{event.public_url}}'],
  ['reminder_1',
    'Hatırlatma: {{event.name}}',
    'Merhaba {{participant.first_name}},\nKısa bir hatırlatma: {{event.name}} etkinliği yakında.\nTarih: {{event.start_datetime}}\nYer: {{event.location}}\nEtkinlik sayfası: {{event.public_url}}'],
  ['reminder_2',
    'Son hatırlatma — yarın {{event.name}}',
    'Merhaba {{participant.first_name}},\nEtkinlik çok yakında başlıyor, hazır olun.\n{{event.start_datetime}} tarihinde, {{event.location}} adresinde sizi bekliyoruz.\nEtkinlik alanı: {{event.participant_url}}'],
  ['event_changed',
    '{{event.name}} bilgileri güncellendi',
    'Merhaba {{participant.first_name}},\nKatılacağınız etkinlikte bazı bilgiler değişti. Lütfen yeni detayları kontrol edin.\nYeni tarih/saat: {{event.start_datetime}}\nYer: {{event.location}}\nEtkinlik sayfası: {{event.public_url}}'],
  ['event_cancelled',
    'Üzgünüz: {{event.name}} iptal edildi',
    'Merhaba {{participant.first_name}},\n{{event.name}} etkinliği iptal edilmek zorunda kaldı. Sizi de üzdüğümüz için özür dileriz.\nYeni duyurular için etkinlik sayfasını takip edebilirsiniz: {{event.public_url}}'],
  ['post_test',
    'Son testinizi doldurun — {{event.name}}',
    'Merhaba {{participant.first_name}},\nEtkinliğin son testini doldurma vakti geldi. Kısa sürüyor, hemen tamamlayabilirsiniz.\nTeste buradan ulaşın: {{event.participant_url}}'],
  ['feedback',
    'Görüşleriniz bizim için önemli, {{participant.first_name}}',
    'Merhaba {{participant.first_name}},\n{{event.name}} etkinliğiyle ilgili deneyiminizi paylaşır mısınız?\nGeri bildiriminiz gelecekteki etkinlikleri şekillendirecek. Form çok kısa:\n{{event.participant_url}}'],
  ['certificate_ready',
    'Sertifikanız hazır, {{participant.first_name}} 🎉',
    'Merhaba {{participant.first_name}},\n{{event.name}} etkinliğine katılımınız için sertifikanız hazır. Aşağıdaki bağlantıdan indirebilir ve doğrulayabilirsiniz.\nSertifika: {{certificate.url}}'],
  ['thank_you',
    'Teşekkürler, {{participant.first_name}}!',
    'Merhaba {{participant.first_name}},\n{{event.name}} etkinliğimize katıldığınız için içten teşekkür ederiz. Sizinle birlikte olmak güzeldi.\nSertifikanız hazır olduğunda size ayrıca haber vereceğiz.']
] as const;
