'use client';
import Link from 'next/link';
import { FormEvent, useState } from 'react';

type FormState={title:string;slug:string;summary:string;startsAt:string;endsAt:string;capacity:number;registrationMode:string;visibility:string;templateId:string;consentText:string};
const steps=['Temel bilgiler','Tarih ve yer','Başvuru','Kontrol'];
export function EventBuilder({organization,templates}:{organization:{id:string;slug:string};templates:Array<{id:string;name:string}>}){
 const[text,setText]=useState(''),[form,setForm]=useState<FormState>({title:'',slug:'',summary:'',startsAt:'',endsAt:'',capacity:100,registrationMode:'APPROVAL',visibility:'LINK_ONLY',templateId:templates[0]?.id??'',consentText:''}),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[step,setStep]=useState(0);
 const set=(key:keyof FormState,value:string|number)=>setForm(current=>({...current,[key]:value}));
 const slugify=(value:string)=>value.toLocaleLowerCase('tr').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
 async function extract(){setBusy(true);setMessage('');const response=await fetch(`/api/backend/organizations/${organization.id}/event-drafts/extract`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({text})}),data=await response.json();if(response.ok){const draft=data.draft;setForm(current=>({...current,title:draft.title??current.title,summary:draft.description??current.summary,startsAt:draft.startsAt?draft.startsAt.slice(0,16):current.startsAt,capacity:draft.capacity??current.capacity,slug:slugify(draft.title??current.title)}));setMessage('Harika, taslağı hazırladık. Bilgileri birlikte kontrol edelim.')}else setMessage(data.message??'Taslak hazırlanamadı. Bilgileriniz kaybolmadı; tekrar deneyebilirsiniz.');setBusy(false)}
 function next(){if(step===0&&!form.title.trim()){setMessage('Devam etmek için etkinliğinize bir ad verin.');return}if(step===1&&(!form.startsAt||!form.endsAt)){setMessage('Başlangıç ve bitiş zamanını seçmeniz gerekiyor.');return}setMessage('');setStep(current=>Math.min(3,current+1));window.scrollTo({top:0,behavior:'smooth'})}
 async function submit(event:FormEvent){event.preventDefault();if(step<3){next();return}setBusy(true);setMessage('Etkinliğiniz hazırlanıyor…');let formId:string|undefined;if(form.templateId){const response=await fetch(`/api/backend/organizations/${organization.id}/forms/from-template`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({templateId:form.templateId,name:`${form.title} kayıt formu`})});if(response.ok)formId=(await response.json()).id}if(!formId){const response=await fetch(`/api/backend/organizations/${organization.id}/forms`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:`${form.title} kayıt formu`,schema:{fields:[]}})});if(response.ok)formId=(await response.json()).id}const{templateId:_,consentText,...fields}=form,response=await fetch(`/api/backend/organizations/${organization.id}/events`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...fields,formId,startsAt:new Date(form.startsAt).toISOString(),endsAt:new Date(form.endsAt).toISOString(),capacity:Number(form.capacity),faqs:[]})}),data=await response.json();if(!response.ok){setMessage(Array.isArray(data.message)?data.message.join(' '):data.message);setBusy(false);return}if(consentText.trim()){const consentResponse=await fetch(`/api/backend/organizations/${organization.id}/consents`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({key:`event-${data.id}`,title:'Etkinlik onamı',text:consentText})}),consent=await consentResponse.json();if(consentResponse.ok)await fetch(`/api/backend/organizations/${organization.id}/events/${data.id}/consents/${consent.id}`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({required:true})})}location.href=`/dashboard/events/${data.id}`}
 return <main className="builder-shell wizard-shell"><header><Link href="/dashboard">← Ana sayfaya dön</Link><div><p className="eyebrow">YENİ ETKİNLİK</p><h1>Etkinliğinizi oluşturalım</h1><p>Dört kısa adımda hazır. İstediğiniz zaman önceki adıma dönebilirsiniz.</p></div></header>
  <ol className="wizard-progress">{steps.map((label,index)=><li key={label} className={index===step?'active':index<step?'done':''}><span>{index<step?'✓':index+1}</span><b>{label}</b></li>)}</ol>
  <form className="wizard-card" onSubmit={submit}>
   {step===0&&<><div className="wizard-intro"><h2>Önce temel bilgiler</h2><p>Etkinliğin adı ve kısa bir açıklaması başlangıç için yeterli.</p></div><label>Etkinlik adı<input autoFocus required value={form.title} onChange={event=>{set('title',event.target.value);if(!form.slug)set('slug',slugify(event.target.value))}} placeholder="Örn. Gençlik ve İklim Buluşması"/></label><label>Kısa açıklama<textarea value={form.summary} onChange={event=>set('summary',event.target.value)} placeholder="Katılımcılara etkinliği bir iki cümleyle anlatın."/></label><details className="smart-draft"><summary>Duyuru metninden otomatik doldur</summary><p>Hazır bir duyurunuz varsa buraya yapıştırın; bilgileri sizin için ayıralım.</p><textarea value={text} onChange={event=>setText(event.target.value)} placeholder="Duyuru metni…"/><button type="button" className="secondary" disabled={busy||text.length<20} onClick={extract}>Bilgileri hazırla</button></details></>}
   {step===1&&<><div className="wizard-intro"><h2>Ne zaman gerçekleşecek?</h2><p>Başlangıç ve bitiş zamanını seçin. Mekânı daha sonra da ekleyebilirsiniz.</p></div><div className="two"><label>Başlangıç<input required type="datetime-local" value={form.startsAt} onChange={event=>set('startsAt',event.target.value)}/></label><label>Bitiş<input required type="datetime-local" value={form.endsAt} onChange={event=>set('endsAt',event.target.value)}/></label></div><label>Bağlantı kısa adı<input required pattern="[a-z0-9-]+" value={form.slug} onChange={event=>set('slug',event.target.value)}/><small>Etkinlik bağlantısında kullanılacak. Örn. genclik-bulusmasi</small></label></>}
   {step===2&&<><div className="wizard-intro"><h2>Başvurular nasıl alınsın?</h2><p>En sık kullanılan güvenli seçenekleri sizin için seçtik.</p></div><div className="choice-grid"><label className={form.registrationMode==='APPROVAL'?'selected':''}><input type="radio" checked={form.registrationMode==='APPROVAL'} onChange={()=>set('registrationMode','APPROVAL')}/><b>Onaylı başvuru</b><small>Her başvuruyu siz değerlendirirsiniz.</small></label><label className={form.registrationMode==='DIRECT'?'selected':''}><input type="radio" checked={form.registrationMode==='DIRECT'} onChange={()=>set('registrationMode','DIRECT')}/><b>Doğrudan kayıt</b><small>Uygun başvurular otomatik kabul edilir.</small></label></div><label>Kontenjan<input required min="1" type="number" value={form.capacity} onChange={event=>set('capacity',event.target.value)}/></label><label>Kayıt formu<select value={form.templateId} onChange={event=>set('templateId',event.target.value)}><option value="">Standart form</option>{templates.map(template=><option key={template.id} value={template.id}>{template.name}</option>)}</select></label><details><summary>Gelişmiş seçenekler</summary><label>Görünürlük<select value={form.visibility} onChange={event=>set('visibility',event.target.value)}><option value="PUBLIC">Herkese açık</option><option value="LINK_ONLY">Bağlantıya sahip olanlar</option><option value="INVITE_ONLY">Yalnız davetliler</option></select></label><label>Zorunlu onam metni<textarea value={form.consentText} onChange={event=>set('consentText',event.target.value)} placeholder="İsteğe bağlı"/></label></details></>}
   {step===3&&<><div className="wizard-intro"><h2>Her şey hazır görünüyor</h2><p>Etkinlik taslak olarak oluşturulacak. Hazır olduğunuzda yönetim ekranından yayınlayabilirsiniz.</p></div><dl className="review-list"><div><dt>Etkinlik</dt><dd>{form.title}</dd></div><div><dt>Tarih</dt><dd>{new Date(form.startsAt).toLocaleString('tr-TR')} – {new Date(form.endsAt).toLocaleString('tr-TR')}</dd></div><div><dt>Başvuru</dt><dd>{form.registrationMode==='APPROVAL'?'Onaylı başvuru':'Doğrudan kayıt'} · {form.capacity} kişi</dd></div><div><dt>Görünürlük</dt><dd>{form.visibility==='PUBLIC'?'Herkese açık':form.visibility==='LINK_ONLY'?'Bağlantıya sahip olanlar':'Yalnız davetliler'}</dd></div></dl></>}
   {message&&<p className="notice" role="status">{message}</p>}<div className="wizard-actions">{step>0&&<button type="button" className="secondary" onClick={()=>setStep(current=>current-1)}>← Geri</button>}<button className="primary" disabled={busy}>{busy?'Hazırlanıyor…':step===3?'Etkinliği oluştur':'Devam et →'}</button></div>
  </form>
 </main>;
}
