'use client';
import Link from 'next/link';
import { FormEvent, useState } from 'react';
import { MarkdownEditor } from './markdown-editor';

type FormState={title:string;slug:string;summary:string;startsAt:string;endsAt:string;capacity:number;registrationMode:string;visibility:string;templateId:string;consentText:string};
const steps=['Temel bilgiler','Tarih ve yer','Başvuru','Kontrol'];
export function EventBuilder({organization}:{organization:{id:string;slug:string;name:string};templates:Array<{id:string;name:string}>}){
 const[text,setText]=useState(''),[form,setForm]=useState<FormState>({title:'',slug:'',summary:'',startsAt:'',endsAt:'',capacity:100,registrationMode:'APPROVAL',visibility:'LINK_ONLY',templateId:'',consentText:''}),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[step,setStep]=useState(0);
 const set=(key:keyof FormState,value:string|number)=>setForm(current=>({...current,[key]:value}));
 const slugify=(value:string)=>value.toLocaleLowerCase('tr').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i').replace(/ş/g,'s').replace(/ğ/g,'g').replace(/ü/g,'u').replace(/ö/g,'o').replace(/ç/g,'c').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
 const autoSlug=()=>{const base=slugify(organization.name||'etkinlik').slice(0,20),title=slugify(form.title).slice(0,30);return title?`${base}-${title}`:base};
 const ensureSlug=()=>{if(!form.slug)set('slug',autoSlug())};
 const extract=async()=>{setBusy(true);setMessage('');const response=await fetch(`/api/backend/organizations/${organization.id}/event-drafts/extract`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({text})}),data=await response.json();if(response.ok){const draft=data.draft;setForm(current=>({...current,title:draft.title??current.title,summary:draft.description??current.summary,startsAt:draft.startsAt?draft.startsAt.slice(0,16):current.startsAt,capacity:draft.capacity??current.capacity}));setMessage('Harika, taslağı hazırladık.')}else setMessage(data.message??'Taslak hazırlanamadı.');setBusy(false)};
 function next(){ensureSlug();if(step===0&&!form.title.trim()){setMessage('Devam etmek için etkinliğinize bir ad verin.');return}if(step===1&&(!form.startsAt||!form.endsAt)){setMessage('Başlangıç ve bitiş zamanını seçmeniz gerekiyor.');return}setMessage('');setStep(current=>Math.min(3,current+1));window.scrollTo({top:0,behavior:'smooth'})}
 async function submit(event:FormEvent){event.preventDefault();ensureSlug();if(step<3){next();return}setBusy(true);setMessage('Etkinliğiniz hazırlanıyor…');let formId:string|undefined;if(form.templateId){const response=await fetch(`/api/backend/organizations/${organization.id}/forms/from-template`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({templateId:form.templateId,name:`${form.title} kayıt formu`})});if(response.ok)formId=(await response.json()).id}if(!formId){const response=await fetch(`/api/backend/organizations/${organization.id}/forms`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:`${form.title} kayıt formu`,schema:{fields:[]}})});if(response.ok)formId=(await response.json()).id}const{templateId:_,consentText,...fields}=form,response=await fetch(`/api/backend/organizations/${organization.id}/events`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...fields,formId,startsAt:new Date(form.startsAt).toISOString(),endsAt:new Date(form.endsAt).toISOString(),capacity:Number(form.capacity),faqs:[]})}),data=await response.json();if(!response.ok){setMessage(Array.isArray(data.message)?data.message.join(' '):data.message);setBusy(false);return}if(consentText.trim()){const consentResponse=await fetch(`/api/backend/organizations/${organization.id}/consents`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({key:`event-${data.id}`,title:'Etkinlik onamı',text:consentText})}),consent=await consentResponse.json();if(consentResponse.ok)await fetch(`/api/backend/organizations/${organization.id}/events/${data.id}/consents/${consent.id}`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({required:true})})}location.href=`/dashboard/events/${data.id}`}
 return <main className="builder-shell wizard-shell"><header><Link href="/dashboard">← Ana sayfaya dön</Link><div><p className="eyebrow">YENİ ETKİNLİK</p><h1>Etkinliğinizi oluşturalım</h1><p>Dört kısa adımda hazır. İstediğiniz zaman önceki adıma dönebilirsiniz.</p></div></header>
  <ol className="wizard-progress">{steps.map((label,index)=><li key={label} className={index===step?'active':index<step?'done':''}><span>{index<step?'✓':index+1}</span><b>{label}</b></li>)}</ol>
  <form className="wizard-card" onSubmit={submit}>
   {step===0&&<><div className="wizard-intro"><h2>Önce temel bilgiler</h2><p>Etkinliğin adı ve açıklaması başlangıç için yeterli.</p></div><label>Etkinlik adı<input autoFocus required value={form.title} onChange={event=>set('title',event.target.value)} placeholder="Örn. Gençlik ve İklim Buluşması"/></label><label>Kısa açıklama<MarkdownEditor value={form.summary} onChange={v=>set('summary',v)} placeholder="Katılımcılara etkinliği bir iki cümleyle anlatın. **Kalın**, *italik* kullanabilirsiniz."/></label><details className="smart-draft"><summary>📋 Duyuru metninden otomatik doldur</summary><p>Hazır bir duyurunuz varsa buraya yapıştırın; bilgileri sizin için ayıralım.</p><textarea value={text} onChange={event=>setText(event.target.value)} placeholder="Duyuru metni…" rows={5}/><button type="button" className="secondary" disabled={busy||text.length<20} onClick={extract}>Bilgileri hazırla</button></details></>}
   {step===1&&<><div className="wizard-intro"><h2>Ne zaman gerçekleşecek?</h2><p>Başlangıç ve bitiş zamanını seçin.</p></div><div className="datetime-picker"><label>Başlangıç<div className="datetime-inputs"><input required type="date" value={form.startsAt.slice(0,10)} onChange={e=>set('startsAt',`${e.target.value}T${form.startsAt.slice(11,16)||'10:00'}`)}/><input type="time" value={form.startsAt.slice(11,16)||'10:00'} onChange={e=>set('startsAt',`${form.startsAt.slice(0,10)||new Date().toISOString().slice(0,10)}T${e.target.value}`)}/></div></label><label>Bitiş<div className="datetime-inputs"><input required type="date" value={form.endsAt.slice(0,10)} onChange={e=>set('endsAt',`${e.target.value}T${form.endsAt.slice(11,16)||'18:00'}`)}/><input type="time" value={form.endsAt.slice(11,16)||'18:00'} onChange={e=>set('endsAt',`${form.endsAt.slice(0,10)||new Date().toISOString().slice(0,10)}T${e.target.value}`)}/></div></label></div><div className="quick-dates"><button type="button" className="toolbar-btn" onClick={()=>{const d=new Date();d.setDate(d.getDate()+7);const ds=d.toISOString().slice(0,10);set('startsAt',`${ds}T10:00`);set('endsAt',`${ds}T18:00`)}}>Önümüzdeki hafta</button><button type="button" className="toolbar-btn" onClick={()=>{const d=new Date();d.setMonth(d.getMonth()+1);const ds=d.toISOString().slice(0,10);set('startsAt',`${ds}T10:00`);set('endsAt',`${ds}T18:00`)}}>Önümüzdeki ay</button></div><label>Bağlantı kısa adı <span className="tooltip" data-tip="Etkinlik sayfasının bağlantısında kullanılacak kısa ad. Otomatik oluşturuldu, istediğiniz gibi düzenleyin.">(?)</span><div className="slug-preview"><input required pattern="[a-z0-9-]+" value={form.slug} onChange={event=>set('slug',event.target.value)} placeholder={autoSlug()}/><button type="button" className="toolbar-btn" onClick={()=>set('slug',autoSlug())} title="Otomatik oluştur">🔄</button></div><small>Boş bırakırsanız otomatik oluşturulur: {autoSlug()}</small></label></>}
   {step===2&&<><div className="wizard-intro"><h2>Başvurular nasıl alınsın?</h2><p>En sık kullanılan güvenli seçenekleri sizin için seçtik.</p></div><div className="choice-grid"><label className={form.registrationMode==='APPROVAL'?'selected':''}><input type="radio" checked={form.registrationMode==='APPROVAL'} onChange={()=>set('registrationMode','APPROVAL')}/><b>Onaylı başvuru</b><small>Her başvuruyu siz değerlendirirsiniz.</small></label><label className={form.registrationMode==='DIRECT'?'selected':''}><input type="radio" checked={form.registrationMode==='DIRECT'} onChange={()=>set('registrationMode','DIRECT')}/><b>Doğrudan kayıt</b><small>Uygun başvurular otomatik kabul edilir.</small></label></div><label>Kontenjan<input required min="1" type="number" value={form.capacity} onChange={event=>set('capacity',event.target.value)}/></label><details><summary>Görünürlük ayarı</summary><label>Görünürlük<select value={form.visibility} onChange={event=>set('visibility',event.target.value)}><option value="PUBLIC">Herkese açık</option><option value="LINK_ONLY">Bağlantıya sahip olanlar</option><option value="INVITE_ONLY">Yalnız davetliler</option></select></label></details><p className="hint-box">Onam metinlerini (KVKK, fotoğraf izni) etkinlik oluşturduktan sonra <b>Ayarlar → Formlar ve Onam</b> bölümünden ekleyebilirsiniz.</p></>}
   {step===3&&<><div className="wizard-intro"><h2>Her şey hazır görünüyor</h2><p>Etkinlik taslak olarak oluşturulacak. Hazır olduğunuzda üstteki toggle ile yayınlayabilirsiniz.</p></div><dl className="review-list"><div><dt>Etkinlik</dt><dd>{form.title}</dd></div><div><dt>Tarih</dt><dd>{form.startsAt?`${new Date(form.startsAt).toLocaleString('tr-TR')} – ${new Date(form.endsAt).toLocaleString('tr-TR')}`:'Seçilmedi'}</dd></div><div><dt>Başvuru</dt><dd>{form.registrationMode==='APPROVAL'?'Onaylı başvuru':'Doğrudan kayıt'} · {form.capacity} kişi</dd></div><div><dt>Görünürlük</dt><dd>{form.visibility==='PUBLIC'?'Herkese açık':form.visibility==='LINK_ONLY'?'Bağlantıya sahip olanlar':'Yalnız davetliler'}</dd></div><div><dt>Bağlantı</dt><dd>/events/{organization.slug}/{form.slug||autoSlug()}</dd></div></dl></>}
   {message&&<p className="notice" role="status">{message}</p>}<div className="wizard-actions">{step>0&&<button type="button" className="secondary" onClick={()=>setStep(current=>current-1)}>← Geri</button>}<button className="primary" disabled={busy}>{busy?'Hazırlanıyor…':step===3?'Etkinliği oluştur':'Devam et →'}</button></div>
  </form>
 </main>;
}
