const dialog=document.querySelector('#eventDialog'),form=document.querySelector('#eventForm'),toast=document.querySelector('#toast'),sidebar=document.querySelector('.sidebar');
const seedEvents=[{id:1,name:'Gençlik İklim Atölyesi',date:'2026-07-18',time:'10:00',location:'Kadıköy Tasarım Atölyesi',capacity:60,registered:48,status:'open',visibility:'public'},{id:2,name:'Gönüllüler Buluşması',date:'2026-07-24',time:'18:30',location:'Moda Sahnesi',capacity:80,registered:0,status:'draft',visibility:'link'},{id:3,name:'Sosyal Etki Eğitimi',date:'2026-08-02',time:'19:00',location:'Çevrim içi',capacity:120,registered:84,status:'open',visibility:'link'},{id:4,name:'Mahalle Dayanışma Günü',date:'2026-07-06',time:'11:00',location:'Yoğurtçu Parkı',capacity:160,registered:156,status:'closed',visibility:'public'}];
let events=JSON.parse(localStorage.getItem('birlikte.events')||'null')||seedEvents,step=1,activeFilter='all';
const seedParticipants=[{id:101,name:'Merve Erdem',email:'merve@example.org',eventId:1,date:'2026-07-12',status:'pending'},{id:102,name:'Ahmet Kaya',email:'ahmet@example.org',eventId:1,date:'2026-07-12',status:'pending'},{id:103,name:'Selin Aksoy',email:'selin@example.org',eventId:1,date:'2026-07-11',status:'accepted'},{id:104,name:'Deniz Bulut',email:'deniz@example.org',eventId:3,date:'2026-07-10',status:'accepted'},{id:105,name:'Can Yıldız',email:'can@example.org',eventId:1,date:'2026-07-10',status:'waitlisted'},{id:106,name:'Ece Arslan',email:'ece@example.org',eventId:3,date:'2026-07-09',status:'pending'},{id:107,name:'Burak Koç',email:'burak@example.org',eventId:1,date:'2026-07-08',status:'rejected'},{id:108,name:'Zeynep Şen',email:'zeynep@example.org',eventId:3,date:'2026-07-08',status:'accepted'}];
let participants=JSON.parse(localStorage.getItem('birlikte.participants')||'null')||seedParticipants,selectedParticipants=new Set();
const emailTemplates=[{id:'received',name:'Başvuru alındı',description:'Başvuru sonrası otomatik bilgi',subject:'{{event.name}} başvurunuz alındı',body:'Merhaba {{participant.first_name}},\n\n{{event.name}} etkinliği için başvurunuzu aldık. Değerlendirme sonucunu ayrıca paylaşacağız.'},{id:'accepted',name:'Başvuru kabul edildi',description:'Kabul ve etkinlik bilgileri',subject:'{{event.name}} başvurunuz kabul edildi',body:'Merhaba {{participant.first_name}},\n\nBaşvurunuz kabul edildi. Etkinlik {{event.start_date}} tarihinde {{event.location}} konumunda gerçekleşecek.'},{id:'reminder',name:'Etkinlik hatırlatması',description:'Tarih ve mekân hatırlatması',subject:'Hatırlatma: {{event.name}}',body:'Merhaba {{participant.first_name}},\n\n{{event.name}} etkinliğinde buluşmamıza az kaldı. Yer: {{event.location}}.'},{id:'waitlist',name:'Yedek liste',description:'Yedek durum bilgilendirmesi',subject:'{{event.name}} yedek liste bilgilendirmesi',body:'Merhaba {{participant.first_name}},\n\nBaşvurunuz yedek listeye alınmıştır. Kontenjan açıldığında sizi bilgilendireceğiz.'}];
const seedCampaigns=[{id:201,eventId:1,templateId:'accepted',subject:'Gençlik İklim Atölyesi başvurunuz kabul edildi',audience:'accepted',recipients:2,status:'sent',scheduledAt:'2026-07-12T14:00',createdAt:'2026-07-12'},{id:202,eventId:1,templateId:'reminder',subject:'Hatırlatma: Gençlik İklim Atölyesi',audience:'accepted',recipients:2,status:'scheduled',scheduledAt:'2026-07-17T18:00',createdAt:'2026-07-14'}];
let campaigns=JSON.parse(localStorage.getItem('birlikte.campaigns')||'null')||seedCampaigns;
const save=()=>localStorage.setItem('birlikte.events',JSON.stringify(events));
const saveParticipants=()=>localStorage.setItem('birlikte.participants',JSON.stringify(participants));
const saveCampaigns=()=>localStorage.setItem('birlikte.campaigns',JSON.stringify(campaigns));
const escapeHtml=value=>String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
function notify(message){toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),3200)}
function updateWizard(){document.querySelectorAll('.wizard-step').forEach(el=>el.classList.toggle('active',Number(el.dataset.step)===step));document.querySelectorAll('.steps i').forEach((el,i)=>el.classList.toggle('active',i<step));document.querySelector('#stepCurrent').textContent=step;document.querySelector('#wizardBack').textContent=step===1?'Vazgeç':'← Geri';document.querySelector('#wizardNext').textContent=step===1?'Bilgileri çıkar →':step===2?'Görünürlüğü seç →':'Taslak oluştur';document.querySelector('#wizardTitle').textContent=['','Duyurudan hızlıca başlayın','Bilgileri kontrol edin','Yayın ayarlarını seçin'][step]}
function openWizard(){step=1;form.reset();document.querySelector('#eventCapacity').value=50;document.querySelector('input[value="link"]').checked=true;updateWizard();dialog.showModal()}
document.querySelectorAll('#newEvent,.new-event-trigger').forEach(button=>button.addEventListener('click',openWizard));document.querySelector('.close').addEventListener('click',()=>dialog.close());
function extractDraft(text){const date=text.match(/(\d{1,2})[ .\/-](\d{1,2})[ .\/-](\d{4})/),time=text.match(/(?:saat\s*)?(\d{1,2}[:.]\d{2})/i),capacity=text.match(/(?:kontenjan|kapasite)\D{0,8}(\d{1,3})/i),first=text.split(/[.!?\n]/).find(line=>line.trim().length>5)||'';document.querySelector('#eventName').value=first.trim().slice(0,80);if(date)document.querySelector('#eventDate').value=`${date[3]}-${date[2].padStart(2,'0')}-${date[1].padStart(2,'0')}`;if(time)document.querySelector('#eventTime').value=time[1].replace('.',':');if(capacity)document.querySelector('#eventCapacity').value=capacity[1];notify('Taslak çıkarıldı; bilgileri kontrol edin.')}
document.querySelector('#wizardNext').addEventListener('click',()=>{if(step===1){extractDraft(document.querySelector('#announcement').value);step=2;updateWizard();return}if(step===2){const required=[...form.querySelectorAll('[data-step="2"] [required]')];if(!required.every(input=>input.reportValidity()))return;step=3;updateWizard();return}events.unshift({id:Date.now(),name:document.querySelector('#eventName').value,date:document.querySelector('#eventDate').value,time:document.querySelector('#eventTime').value,location:document.querySelector('#eventLocation').value,capacity:Number(document.querySelector('#eventCapacity').value),registered:0,status:'draft',visibility:form.elements.visibility.value,registrationModel:document.querySelector('#registrationModel').value,consent:document.querySelector('#addConsent').checked});save();renderEvents();dialog.close();showView('events');notify('Etkinlik taslağı oluşturuldu.')});
document.querySelector('#wizardBack').addEventListener('click',()=>{if(step===1)dialog.close();else{step--;updateWizard()}});document.querySelectorAll('.radio-cards label').forEach(label=>label.addEventListener('click',()=>{document.querySelectorAll('.radio-cards label').forEach(el=>el.classList.remove('selected'));label.classList.add('selected')}));
function formatDate(value){return new Intl.DateTimeFormat('tr-TR',{day:'numeric',month:'long',year:'numeric'}).format(new Date(value+'T12:00:00'))}
function renderEvents(){const query=document.querySelector('#eventSearch').value.toLocaleLowerCase('tr'),filtered=events.filter(event=>(activeFilter==='all'||event.status===activeFilter)&&event.name.toLocaleLowerCase('tr').includes(query));document.querySelector('#eventCount').textContent=events.filter(e=>e.status!=='closed').length;document.querySelector('#eventCards').innerHTML=filtered.map((event,index)=>`<article class="event-card"><div class="event-cover ${index%3===1?'blue-cover':index%3===2?'orange-cover':''}"><span class="badge ${event.status==='open'?'live':event.status==='draft'?'draft':'link'}">${event.status==='open'?'Kayıt açık':event.status==='draft'?'Taslak':'Tamamlandı'}</span><button class="more" aria-label="Diğer işlemler">•••</button></div><div class="event-card-body"><h3>${escapeHtml(event.name)}</h3><p>◷ ${formatDate(event.date)} · ${escapeHtml(event.time)}</p><p>📍 ${escapeHtml(event.location)}</p><div class="event-progress"><div><span>${event.registered} katılımcı</span><b>${event.registered} / ${event.capacity}</b></div><div class="bar"><i style="width:${Math.min(100,event.registered/event.capacity*100)}%"></i></div></div><div class="card-actions"><button data-action="toggle" data-id="${event.id}">${event.status==='draft'?'Yayınla':'Yönet'}</button><button>Katılımcılar</button></div></div></article>`).join('');document.querySelector('#eventEmpty').hidden=filtered.length>0}
function showView(id){document.querySelectorAll('.app-view').forEach(view=>view.hidden=view.id!==id);document.querySelectorAll('nav a[data-view]').forEach(link=>link.classList.toggle('active',link.dataset.view===id));location.hash=id;if(id==='checkin')renderCheckin();if(innerWidth<=760)sidebar.classList.remove('open')}
document.querySelectorAll('nav a[data-view]').forEach(link=>link.addEventListener('click',event=>{event.preventDefault();showView(link.dataset.view)}));document.querySelectorAll('.filter').forEach(button=>button.addEventListener('click',()=>{activeFilter=button.dataset.filter;document.querySelectorAll('.filter').forEach(el=>el.classList.remove('active'));button.classList.add('active');renderEvents()}));document.querySelector('#eventSearch').addEventListener('input',renderEvents);document.querySelector('#eventCards').addEventListener('click',event=>{const button=event.target.closest('[data-action="toggle"]');if(!button)return;const item=events.find(e=>e.id===Number(button.dataset.id));if(item.status==='draft'){item.status='open';save();renderEvents();notify('Etkinlik yayınlandı ve kayıtlar açıldı.')}else notify('Etkinlik yönetimi sonraki modülde açılacak.')});
const statusLabels={pending:'Bekliyor',accepted:'Kabul edildi',waitlisted:'Yedek liste',rejected:'Reddedildi'};
function participantEventName(id){return events.find(event=>event.id===id)?.name||'Silinmiş etkinlik'}
function updateParticipantStats(){const count=status=>participants.filter(person=>person.status===status).length;document.querySelector('#totalApplicants').textContent=participants.length;document.querySelector('#pendingApplicants').textContent=count('pending');document.querySelector('#acceptedApplicants').textContent=count('accepted');document.querySelector('#waitlistedApplicants').textContent=count('waitlisted');document.querySelector('#pendingCount').textContent=count('pending')}
function updateEventOptions(){const select=document.querySelector('#participantEvent'),current=select.value;select.innerHTML='<option value="all">Tüm etkinlikler</option>'+events.map(event=>`<option value="${event.id}">${escapeHtml(event.name)}</option>`).join('');select.value=[...select.options].some(option=>option.value===current)?current:'all'}
function initials(name){return name.split(' ').slice(0,2).map(part=>part[0]).join('').toLocaleUpperCase('tr')}
function filteredParticipants(){const query=document.querySelector('#participantSearch').value.toLocaleLowerCase('tr'),eventId=document.querySelector('#participantEvent').value,status=document.querySelector('#participantStatus').value;return participants.filter(person=>(eventId==='all'||person.eventId===Number(eventId))&&(status==='all'||person.status===status)&&(person.name+' '+person.email).toLocaleLowerCase('tr').includes(query))}
function renderParticipants(){updateParticipantStats();updateEventOptions();const filtered=filteredParticipants();document.querySelector('#participantRows').innerHTML=filtered.map(person=>`<tr><td><input type="checkbox" data-select="${person.id}" ${selectedParticipants.has(person.id)?'checked':''} aria-label="${escapeHtml(person.name)} seç"></td><td><div class="person"><span class="person-avatar">${escapeHtml(initials(person.name))}</span><span><b>${escapeHtml(person.name)}</b><small>${escapeHtml(person.email)}</small></span></div></td><td>${escapeHtml(participantEventName(person.eventId))}</td><td>${formatDate(person.date)}</td><td><span class="status-pill ${person.status}">${statusLabels[person.status]}</span></td><td><div class="row-actions"><button data-person-action="accepted" data-id="${person.id}" title="Kabul et">✓</button><button data-person-action="waitlisted" data-id="${person.id}" title="Yedeğe al">◷</button><button data-person-action="rejected" data-id="${person.id}" title="Reddet">×</button></div></td></tr>`).join('');document.querySelector('#participantEmpty').hidden=filtered.length>0;document.querySelector('#selectAll').checked=filtered.length>0&&filtered.every(person=>selectedParticipants.has(person.id));updateBulkBar()}
function updateBulkBar(){document.querySelector('#selectedCount').textContent=selectedParticipants.size;document.querySelector('#bulkBar').hidden=selectedParticipants.size===0}
function setParticipantStatus(ids,status){participants=participants.map(person=>ids.includes(person.id)?{...person,status}:person);saveParticipants();selectedParticipants.clear();renderParticipants();notify(`${ids.length} başvuru: ${statusLabels[status].toLocaleLowerCase('tr')}.`)}
['participantSearch','participantEvent','participantStatus'].forEach(id=>document.querySelector('#'+id).addEventListener(id==='participantSearch'?'input':'change',renderParticipants));document.querySelector('#participantRows').addEventListener('change',event=>{const checkbox=event.target.closest('[data-select]');if(!checkbox)return;const id=Number(checkbox.dataset.select);checkbox.checked?selectedParticipants.add(id):selectedParticipants.delete(id);updateBulkBar()});document.querySelector('#participantRows').addEventListener('click',event=>{const button=event.target.closest('[data-person-action]');if(button)setParticipantStatus([Number(button.dataset.id)],button.dataset.personAction)});document.querySelector('#selectAll').addEventListener('change',event=>{filteredParticipants().forEach(person=>event.target.checked?selectedParticipants.add(person.id):selectedParticipants.delete(person.id));renderParticipants()});document.querySelector('#bulkBar').addEventListener('click',event=>{const button=event.target.closest('[data-bulk]');if(button)setParticipantStatus([...selectedParticipants],button.dataset.bulk)});
document.querySelector('#exportParticipants').addEventListener('click',()=>{const rows=[['Ad Soyad','E-posta','Etkinlik','Başvuru Tarihi','Durum'],...participants.map(person=>[person.name,person.email,participantEventName(person.eventId),person.date,statusLabels[person.status]])],csv='\uFEFF'+rows.map(row=>row.map(value=>'"'+String(value).replaceAll('"','""')+'"').join(',')).join('\n'),link=document.createElement('a');link.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));link.download='katilimcilar.csv';link.click();URL.revokeObjectURL(link.href);notify('Katılımcı listesi indirildi.')});
function updateCheckinEvents(){const select=document.querySelector('#checkinEvent'),current=select.value,active=events.filter(event=>event.status==='open');select.innerHTML=active.map(event=>`<option value="${event.id}">${escapeHtml(event.name)}</option>`).join('');if(active.some(event=>String(event.id)===current))select.value=current}
function checkinPeople(){const eventId=Number(document.querySelector('#checkinEvent').value),query=document.querySelector('#checkinSearch').value.toLocaleLowerCase('tr');return participants.filter(person=>person.eventId===eventId&&person.status==='accepted'&&(person.name+' '+person.email).toLocaleLowerCase('tr').includes(query))}
function renderCheckin(){updateCheckinEvents();const eventId=Number(document.querySelector('#checkinEvent').value),all=participants.filter(person=>person.eventId===eventId&&person.status==='accepted'),filtered=checkinPeople(),done=all.filter(person=>person.checkedIn).length,door=all.filter(person=>person.doorRegistration).length;document.querySelector('#checkinTotal').textContent=all.length;document.querySelector('#checkinDone').textContent=done;document.querySelector('#checkinWaiting').textContent=all.length-done;document.querySelector('#doorCount').textContent=door;document.querySelector('#checkinRate').textContent='%'+(all.length?Math.round(done/all.length*100):0);document.querySelector('#checkinRows').innerHTML=filtered.map(person=>`<article class="checkin-row"><div class="person"><span class="person-avatar">${escapeHtml(initials(person.name))}</span><span><b>${escapeHtml(person.name)}</b><small>${escapeHtml(person.email)}</small></span></div>${person.doorRegistration?'<span class="door-badge">Kapıda kayıt</span>':''}<small>${person.checkedIn?'Teyit: '+escapeHtml(person.checkinTime||'Şimdi'):'Henüz gelmedi'}</small><button class="check-button ${person.checkedIn?'done':''}" data-checkin="${person.id}" ${person.checkedIn?'disabled':''}>${person.checkedIn?'✓ Teyit edildi':'Teyit et'}</button></article>`).join('');document.querySelector('#checkinEmpty').hidden=filtered.length>0}
document.querySelector('#checkinEvent').addEventListener('change',renderCheckin);document.querySelector('#checkinSearch').addEventListener('input',renderCheckin);document.querySelector('#checkinRows').addEventListener('click',event=>{const button=event.target.closest('[data-checkin]');if(!button)return;const person=participants.find(item=>item.id===Number(button.dataset.checkin));if(person.checkedIn){notify('Bu katılımcının teyidi zaten alınmış.');return}person.checkedIn=true;person.checkinTime=new Intl.DateTimeFormat('tr-TR',{hour:'2-digit',minute:'2-digit'}).format(new Date());saveParticipants();renderCheckin();notify(`${person.name} için katılım teyidi alındı.`)});
const doorDialog=document.querySelector('#doorDialog');document.querySelector('#openDoorRegistration').addEventListener('click',()=>{document.querySelector('#doorForm').reset();doorDialog.showModal()});document.querySelectorAll('.door-close').forEach(button=>button.addEventListener('click',()=>doorDialog.close()));document.querySelector('#doorForm').addEventListener('submit',event=>{event.preventDefault();const email=document.querySelector('#doorEmail').value.trim().toLocaleLowerCase('tr'),eventId=Number(document.querySelector('#checkinEvent').value);if(participants.some(person=>person.eventId===eventId&&person.email.toLocaleLowerCase('tr')===email)){notify('Bu e-posta ile etkinlikte zaten bir kayıt var.');return}participants.unshift({id:Date.now(),name:document.querySelector('#doorName').value.trim(),email,eventId,date:new Date().toISOString().slice(0,10),status:'accepted',checkedIn:true,checkinTime:new Intl.DateTimeFormat('tr-TR',{hour:'2-digit',minute:'2-digit'}).format(new Date()),doorRegistration:true,consent:true});saveParticipants();renderParticipants();renderCheckin();doorDialog.close();notify('Kapıda kayıt ve katılım teyidi tamamlandı.')});
document.querySelector('#fullscreenQr').addEventListener('click',()=>{const panel=document.querySelector('.qr-panel'),active=panel.classList.toggle('fullscreen-qr');document.querySelector('#fullscreenQr').textContent=active?'× Tam ekrandan çık':'⛶ Tam ekran göster'});document.addEventListener('keydown',event=>{if(event.key==='Escape'){const panel=document.querySelector('.qr-panel');if(panel.classList.contains('fullscreen-qr')){panel.classList.remove('fullscreen-qr');document.querySelector('#fullscreenQr').textContent='⛶ Tam ekran göster'}}});
const campaignDialog=document.querySelector('#campaignDialog'),campaignStatus={scheduled:'Planlandı',sent:'Gönderildi',cancelled:'İptal edildi'},allowedVariables=new Set(['participant.first_name','event.name','event.start_date','event.location']);
function campaignRecipients(){const eventId=Number(document.querySelector('#campaignEvent').value),audience=document.querySelector('#campaignAudience').value;return participants.filter(person=>person.eventId===eventId&&(audience==='all'||person.status===audience)).length}
function emailQuota(){const limit=Math.max(3,participants.length*3),used=campaigns.filter(item=>item.status==='sent').reduce((sum,item)=>sum+item.recipients,0);return{limit,used}}
function updateCampaignPreview(){const count=campaignRecipients(),{limit,used}=emailQuota(),warning=used+count>limit?'Kota yetersiz':'';document.querySelector('#recipientCount').textContent=count+' kişi';document.querySelector('#quotaWarning').textContent=warning}
function fillCampaignTemplate(id){const template=emailTemplates.find(item=>item.id===id)||emailTemplates[0];document.querySelector('#campaignTemplate').value=template.id;document.querySelector('#campaignSubject').value=template.subject;document.querySelector('#campaignBody').value=template.body}
function openCampaign(templateId='accepted'){document.querySelector('#campaignForm').reset();document.querySelector('#campaignEvent').innerHTML=events.map(event=>`<option value="${event.id}">${escapeHtml(event.name)}</option>`).join('');document.querySelector('#campaignTemplate').innerHTML=emailTemplates.map(template=>`<option value="${template.id}">${escapeHtml(template.name)}</option>`).join('');document.querySelector('#scheduleField').hidden=true;fillCampaignTemplate(templateId);updateCampaignPreview();campaignDialog.showModal()}
function renderCampaigns(){const filter=document.querySelector('#campaignFilter').value,shown=campaigns.filter(item=>filter==='all'||item.status===filter),{limit,used}=emailQuota(),percent=Math.min(100,Math.round(used/limit*100));document.querySelector('#emailUsed').textContent=used;document.querySelector('#emailLimit').textContent=limit;document.querySelector('#emailPercent').textContent=percent+'%';document.querySelector('#quotaRing').style.background=`conic-gradient(#74559b ${percent*3.6}deg,#ece8f1 0deg)`;document.querySelector('#scheduledCount').textContent=campaigns.filter(item=>item.status==='scheduled').length;document.querySelector('#sentCount').textContent=campaigns.filter(item=>item.status==='sent').reduce((sum,item)=>sum+item.recipients,0);document.querySelector('#campaignList').innerHTML=shown.map(item=>`<article class="campaign"><span class="campaign-icon">✉</span><div><h3>${escapeHtml(item.subject)}</h3><p>${escapeHtml(participantEventName(item.eventId))} · ${item.recipients} alıcı</p></div><div class="campaign-meta"><b>${formatDate(item.scheduledAt.slice(0,10))}</b><small>${escapeHtml(item.scheduledAt.slice(11,16))}</small></div><span class="status-pill ${item.status==='sent'?'accepted':item.status==='scheduled'?'waitlisted':'rejected'}">${campaignStatus[item.status]}</span>${item.status==='scheduled'?`<button class="more" data-cancel-campaign="${item.id}" title="Planı iptal et">×</button>`:''}</article>`).join('');document.querySelector('#campaignEmpty').hidden=shown.length>0;document.querySelector('#templateList').innerHTML=emailTemplates.map(template=>`<button class="template-item" data-template="${template.id}"><span>✉</span><span><b>${escapeHtml(template.name)}</b><small>${escapeHtml(template.description)}</small></span><em>→</em></button>`).join('')}
function validateVariables(text){const variables=[...text.matchAll(/{{\s*([^}]+)\s*}}/g)].map(match=>match[1].trim());return variables.filter(variable=>!allowedVariables.has(variable))}
document.querySelector('#newCampaign').addEventListener('click',()=>openCampaign());document.querySelectorAll('.campaign-close').forEach(button=>button.addEventListener('click',()=>campaignDialog.close()));document.querySelector('#templateList').addEventListener('click',event=>{const button=event.target.closest('[data-template]');if(button)openCampaign(button.dataset.template)});document.querySelector('#campaignTemplate').addEventListener('change',event=>fillCampaignTemplate(event.target.value));['campaignEvent','campaignAudience'].forEach(id=>document.querySelector('#'+id).addEventListener('change',updateCampaignPreview));document.querySelector('#campaignTiming').addEventListener('change',event=>{const scheduled=event.target.value==='scheduled';document.querySelector('#scheduleField').hidden=!scheduled;document.querySelector('#campaignDate').required=scheduled});document.querySelector('#campaignFilter').addEventListener('change',renderCampaigns);document.querySelector('#campaignList').addEventListener('click',event=>{const button=event.target.closest('[data-cancel-campaign]');if(!button)return;const item=campaigns.find(campaign=>campaign.id===Number(button.dataset.cancelCampaign));item.status='cancelled';saveCampaigns();renderCampaigns();notify('Planlanmış gönderim iptal edildi.')});
document.querySelector('#campaignForm').addEventListener('submit',event=>{event.preventDefault();const subject=document.querySelector('#campaignSubject').value.trim(),body=document.querySelector('#campaignBody').value.trim(),invalid=validateVariables(subject+' '+body),recipients=campaignRecipients(),{limit,used}=emailQuota();if(invalid.length){notify('Geçersiz şablon değişkeni: '+invalid[0]);return}if(!recipients){notify('Seçilen hedef kitlede alıcı bulunmuyor.');return}if(used+recipients>limit){notify('Aylık e-posta kotası bu gönderim için yetersiz.');return}const timing=document.querySelector('#campaignTiming').value,scheduledAt=timing==='scheduled'?document.querySelector('#campaignDate').value:new Date(Date.now()+60000).toISOString().slice(0,16);campaigns.unshift({id:Date.now(),eventId:Number(document.querySelector('#campaignEvent').value),templateId:document.querySelector('#campaignTemplate').value,subject,body,audience:document.querySelector('#campaignAudience').value,recipients,status:'scheduled',scheduledAt,createdAt:new Date().toISOString().slice(0,10)});saveCampaigns();renderCampaigns();campaignDialog.close();notify('E-posta arka plan gönderim kuyruğuna eklendi.')});
document.querySelector('.mobile-menu').addEventListener('click',()=>sidebar.classList.toggle('open'));document.addEventListener('click',e=>{if(innerWidth<=760&&!sidebar.contains(e.target)&&!e.target.closest('.mobile-menu'))sidebar.classList.remove('open')});renderEvents();renderParticipants();renderCheckin();renderCampaigns();if(['#events','#participants','#checkin','#communications'].includes(location.hash))showView(location.hash.slice(1));
