import { BadRequestException, ConflictException, Inject, Injectable, NotFoundException } from '@nestjs/common';
import { AssessmentKind, Prisma } from '@prisma/client';
import { PrismaService } from '../../shared/persistence/prisma.service';
import { OrganizationAccessService } from '../organizations/policies/organization-access.service';
import { AuditService } from '../audit/audit.service';
import { FeaturesService } from '../features/features.service';
import { AssessmentQuestion, scoreAssessment } from './scoring';
@Injectable()
export class AssessmentsService {
  constructor(@Inject(PrismaService) private prisma: PrismaService, @Inject(OrganizationAccessService) private access: OrganizationAccessService, @Inject(AuditService) private audit: AuditService, @Inject(FeaturesService) private features: FeaturesService) {}
  async list(userId: string, organizationId: string, eventId: string) { await this.access.requireEventAccess(userId, organizationId, eventId); return this.prisma.assessment.findMany({ where: { eventId }, include: { _count: { select: { submissions: true } }, submissions: { select: { score: true } } }, orderBy: { createdAt: 'desc' } }); }
  async submissionDetails(userId: string, organizationId: string, assessmentId: string) { const assessment = await this.prisma.assessment.findUnique({ where: { id: assessmentId }, include: { event: true, submissions: { include: { registration: { select: { firstName: true, lastName: true } } } } } }); if (!assessment || assessment.event.organizationId !== organizationId) throw new NotFoundException('Test bulunamadı.'); await this.access.requireEventAccess(userId, organizationId, assessment.eventId, ['ORGANIZATION_ADMIN', 'EVENT_MANAGER']); return { assessment: { id: assessment.id, title: assessment.title, kind: assessment.kind, questions: ((assessment.schema as unknown as { questions: AssessmentQuestion[] }).questions ?? []) }, submissions: assessment.submissions.map(s => ({ id: s.id, name: `${s.registration.firstName} ${s.registration.lastName}`, score: s.score, answers: s.answers })) }; }
  async copy(userId: string, organizationId: string, id: string, kind: AssessmentKind, title: string) { const source = await this.prisma.assessment.findUnique({ where: { id }, include: { event: true } }); if (!source || source.event.organizationId !== organizationId) throw new NotFoundException('Kaynak test bulunamadı.'); await this.access.requireEventAccess(userId, organizationId, source.eventId, ['ORGANIZATION_ADMIN', 'EVENT_MANAGER']); const created = await this.prisma.assessment.create({ data: { eventId: source.eventId, kind, title, schema: source.schema as Prisma.InputJsonValue } }); await this.audit.record({ actorId: userId, organizationId, action: 'assessment.copied', resourceType: 'assessment', resourceId: created.id, metadata: { sourceId: id } }); return created; }
  async comparison(userId: string, organizationId: string, eventId: string) { await this.access.requireEventAccess(userId, organizationId, eventId); const assessments = await this.prisma.assessment.findMany({ where: { eventId }, include: { submissions: { select: { score: true } } } }); const summary = (kind: AssessmentKind) => { const rows = assessments.filter(item => item.kind === kind).flatMap(item => item.submissions).map(row => row.score).filter((score): score is number => score !== null); return { submissions: rows.length, average: rows.length ? Math.round(rows.reduce((sum, score) => sum + score, 0) / rows.length) : null }; }; const pre = summary('PRE_TEST'), post = summary('POST_TEST'); return { pre, post, improvement: pre.average !== null && post.average !== null ? post.average - pre.average : null }; }
  async create(userId: string, organizationId: string, eventId: string, kind: AssessmentKind, title: string, questions: AssessmentQuestion[]) { await this.access.requireEventAccess(userId, organizationId, eventId, ['ORGANIZATION_ADMIN', 'EVENT_MANAGER']); if (!questions.length || new Set(questions.map(q => q.id)).size !== questions.length) throw new BadRequestException('Test soruları boş veya tekrarlı olamaz.'); return this.prisma.assessment.create({ data: { eventId, kind, title, schema: { questions } as unknown as Prisma.InputJsonValue } }); }
  async setOpen(userId: string, organizationId: string, id: string, open: boolean) { const assessment = await this.prisma.assessment.findUnique({ where: { id }, include: { event: true } }); if (!assessment || assessment.event.organizationId !== organizationId) throw new NotFoundException('Test bulunamadı.'); await this.access.requireEventAccess(userId, organizationId, assessment.eventId, ['ORGANIZATION_ADMIN', 'EVENT_MANAGER']); const updated = await this.prisma.assessment.update({ where: { id }, data: { open } }); await this.audit.record({ actorId: userId, organizationId, action: open ? 'assessment.opened' : 'assessment.closed', resourceType: 'assessment', resourceId: id }); return updated; }
  async available(userId: string, eventId: string) { await this.features.assertEnabled(eventId, 'assessments'); const registration = await this.registrationFor(userId, eventId); return this.prisma.assessment.findMany({ where: { eventId, open: true }, select: { id: true, kind: true, title: true, schema: true, submissions: { where: { registrationId: registration.id }, select: { id: true, score: true } } } }); }
  async submit(userId: string, id: string, answers: Record<string, unknown>) { const assessment = await this.prisma.assessment.findUnique({ where: { id } }); if (!assessment?.open) throw new NotFoundException('Test açık değil.'); await this.features.assertEnabled(assessment.eventId, 'assessments'); const registration = await this.registrationFor(userId, assessment.eventId), questions = ((assessment.schema as unknown as { questions: AssessmentQuestion[] }).questions ?? []), score = scoreAssessment(questions, answers); try{return await this.prisma.assessmentSubmission.create({ data: { assessmentId: id, registrationId: registration.id, answers: answers as Prisma.InputJsonValue, score } })}catch(error){if(error instanceof Prisma.PrismaClientKnownRequestError&&error.code==='P2002')throw new ConflictException('Bu testi daha önce gönderdiniz.');throw error} }
  private async registrationFor(userId: string, eventId: string) { const user = await this.prisma.user.findUnique({ where: { id: userId } }); if (!user) throw new NotFoundException('Kullanıcı bulunamadı.'); const registration = await this.prisma.eventRegistration.findUnique({ where: { eventId_email: { eventId, email: user.email } } }); if (!registration || registration.applicationStatus !== 'ACCEPTED') throw new NotFoundException('Kabul edilmiş katılımcı kaydı bulunamadı.'); return registration; }
}
