import { BadRequestException, Inject, Injectable, NotFoundException } from '@nestjs/common';
import { Prisma } from '@prisma/client'; import { PrismaService } from '../../shared/persistence/prisma.service'; import { OrganizationAccessService } from '../organizations/policies/organization-access.service';
export interface FormField { key:string; type:'text'|'email'|'phone'|'number'|'select'|'checkbox'|'textarea'; label:string; required?:boolean; options?:string[] }
function validateSchema(value: unknown): asserts value is { fields: FormField[] } { const s=value as {fields?:FormField[]}; if(!s || !Array.isArray(s.fields) || new Set(s.fields.map(f=>f.key)).size!==s.fields.length) throw new BadRequestException('Geçersiz veya tekrarlı alan anahtarı içeren form şeması.'); }
@Injectable() export class FormsService { constructor(@Inject(PrismaService) private prisma:PrismaService,@Inject(OrganizationAccessService) private access:OrganizationAccessService){}
 async create(userId:string,organizationId:string,name:string,schema:unknown){await this.access.requireMembership(userId,organizationId,['ORGANIZATION_ADMIN','EVENT_MANAGER']);validateSchema(schema);return this.prisma.form.create({data:{organizationId,name,versions:{create:{version:1,schema:schema as unknown as Prisma.InputJsonValue}}},include:{versions:true}});}
 async publishVersion(userId:string,organizationId:string,formId:string,schema:unknown){await this.access.requireMembership(userId,organizationId,['ORGANIZATION_ADMIN','EVENT_MANAGER']);validateSchema(schema);const form=await this.prisma.form.findFirst({where:{id:formId,organizationId},include:{versions:{orderBy:{version:'desc'},take:1}}});if(!form)throw new NotFoundException('Form bulunamadı.');return this.prisma.formVersion.create({data:{formId,version:(form.versions[0]?.version??0)+1,schema:schema as unknown as Prisma.InputJsonValue,publishedAt:new Date()}});}
 list(userId:string,organizationId:string){return this.access.requireMembership(userId,organizationId).then(()=>this.prisma.form.findMany({where:{organizationId},include:{versions:{orderBy:{version:'desc'}}}}));}
}
