import { BadRequestException, Inject, Injectable, NotFoundException } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { PrismaService } from '../../shared/persistence/prisma.service';
import { OrganizationAccessService } from '../organizations/policies/organization-access.service';
export interface FormField { key: string; type: 'text'|'email'|'phone'|'number'|'select'|'checkbox'|'textarea'; label: string; required: boolean; options: string[] }
function validateSchema(value: unknown): asserts value is { fields: FormField[] } { const schema = value as { fields: FormField[] }; if (!schema || !Array.isArray(schema.fields) || new Set(schema.fields.map(field => field.key)).size !== schema.fields.length) throw new BadRequestException('Geçersiz veya tekrarlı alan anahtarı içeren form şeması.'); }
@Injectable()
export class FormsService {
  constructor(@Inject(PrismaService) private prisma: PrismaService, @Inject(OrganizationAccessService) private access: OrganizationAccessService) {}
  async publicForEvent(eventId: string) { const event = await this.prisma.event.findFirst({ where: { id: eventId, publicationStatus: 'PUBLISHED' }, select: { form: { select: { versions: { where: { publishedAt: { not: null } }, orderBy: { version: 'desc' }, take: 1, select: { id: true, version: true, schema: true } } } } } }); return event?.form?.versions[0] ?? { id: null, version: 0, schema: { fields: [] } }; }
  async create(userId: string, organizationId: string, name: string, schema: unknown) { await this.access.requireMembership(userId, organizationId, ['ORGANIZATION_ADMIN', 'EVENT_MANAGER']); validateSchema(schema); return this.prisma.form.create({ data: { organizationId, name, versions: { create: { version: 1, schema: schema as unknown as Prisma.InputJsonValue } } }, include: { versions: true } }); }
  async publishVersion(userId: string, organizationId: string, formId: string, schema: unknown) { await this.access.requireMembership(userId, organizationId, ['ORGANIZATION_ADMIN', 'EVENT_MANAGER']); validateSchema(schema); const form = await this.prisma.form.findFirst({ where: { id: formId, organizationId }, include: { versions: { orderBy: { version: 'desc' }, take: 1 } } }); if (!form) throw new NotFoundException('Form bulunamadı.'); return this.prisma.formVersion.create({ data: { formId, version: (form.versions[0]?.version ?? 0) + 1, schema: schema as unknown as Prisma.InputJsonValue, publishedAt: new Date() } }); }
  list(userId: string, organizationId: string) { return this.access.requireMembership(userId, organizationId).then(() => this.prisma.form.findMany({ where: { organizationId }, include: { versions: { orderBy: { version: 'desc' } } } })); }
  async listTemplates(userId: string, organizationId: string) { await this.access.requireMembership(userId, organizationId); return this.prisma.formTemplate.findMany({ where: { organizationId }, orderBy: { name: 'asc' } }); }
  async createFromTemplate(userId: string, organizationId: string, templateId: string, name: string) { await this.access.requireMembership(userId, organizationId, ['ORGANIZATION_ADMIN', 'EVENT_MANAGER']); const template = await this.prisma.formTemplate.findFirst({ where: { id: templateId, organizationId } }); if (!template) throw new NotFoundException('Form şablonu bulunamadı.'); return this.prisma.form.create({ data: { organizationId, name, versions: { create: { version: 1, schema: template.schema as Prisma.InputJsonValue, publishedAt: new Date() } } }, include: { versions: true } }); }
}
