export type Cop31Locale = 'tr' | 'en';
export type Cop31Format = 'ONLINE' | 'IN_PERSON' | 'HYBRID';
export type Cop31Status = 'DRAFT' | 'PUBLISHED' | 'POSTPONED' | 'CANCELLED' | 'ARCHIVED';

export type Cop31LocalizedContent = {
  title: string;
  summary: string;
  description?: string | null;
  venueName?: string | null;
  venueAddress?: string | null;
  city?: string | null;
  country?: string | null;
  organizers: string[];
  organizerUrl?: string | null;
  languages: string[];
  topics: string[];
  cop31Connection: string;
  access?: string | null;
  registrationUrl?: string | null;
  informationUrl?: string | null;
  sourceUrl: string;
};

export type Cop31Event = {
  id: string;
  slug: string;
  contentTr: Cop31LocalizedContent;
  contentEn: Cop31LocalizedContent;
  startsAt: string;
  endsAt: string | null;
  timezone: string;
  format: Cop31Format;
  status: Cop31Status;
  featured: boolean;
  verifiedAt: string | null;
  createdAt: string;
  updatedAt: string;
};

export type Cop31Copy = {
  label: string;
  eyebrow: string;
  title: string;
  intro: string;
  search: string;
  upcoming: string;
  newest: string;
  all: string;
  filters: string;
  topic: string;
  filterAccess: string;
  date: string;
  region: string;
  format: string;
  language: string;
  allTopics: string;
  allFormats: string;
  allLanguages: string;
  results: string;
  featured: string;
  latest: string;
  details: string;
  register: string;
  information: string;
  source: string;
  share: string;
  calendar: string;
  back: string;
  eventLanguage: string;
  organizers: string;
  when: string;
  where: string;
  cop31Connection: string;
  updated: string;
  emptyTitle: string;
  emptyBody: string;
  clearFilters: string;
  online: string;
  inPerson: string;
  hybrid: string;
  postponed: string;
  cancelled: string;
  past: string;
  pastEvents: string;
  onThisPage: string;
  about: string;
  access: string;
  noRegistration: string;
};
