import { BadRequestException, Inject, Injectable, NotFoundException } from '@nestjs/common'; import { PrismaService } from '../../shared/persistence/prisma.service'; import { OrganizationAccessService } from '../organizations/policies/organization-access.service'; import { AuditService } from '../audit/audit.service';
@Injectable() export class ConsentsService { constructor(@Inject(PrismaService)private prisma:PrismaService,@Inject(OrganizationAccessService)private access:OrganizationAccessService,@Inject(AuditService)private audit:AuditService){}
 async create(userId:string,organizationId:string,key:string,title:string,text:string){await this.access.requireMembership(userId,organizationId,['ORGANIZATION_ADMIN','EVENT_MANAGER']);const definition=await this.prisma.consentDefinition.create({data:{organizationId,key,title,versions:{create:{version:1,text}}},include:{versions:true}});await this.audit.record({actorId:userId,organizationId,action:'consent.created',resourceType:'consent',resourceId:definition.id});return definition}
 async addVersion(userId:string,organizationId:string,definitionId:string,text:string){await this.access.requireMembership(userId,organizationId,['ORGANIZATION_ADMIN','EVENT_MANAGER']);const d=await this.prisma.consentDefinition.findFirst({where:{id:definitionId,organizationId},include:{versions:{orderBy:{version:'desc'},take:1}}});if(!d)throw new NotFoundException('Onam tanımı bulunamadı.');return this.prisma.consentVersion.create({data:{definitionId,version:(d.versions[0]?.version??0)+1,text}})}
 async requireForEvent(userId:string,organizationId:string,eventId:string,definitionId:string,required:boolean){await this.access.requireMembership(userId,organizationId,['ORGANIZATION_ADMIN','EVENT_MANAGER']);const [event,definition]=await Promise.all([this.prisma.event.findFirst({where:{id:eventId,organizationId}}),this.prisma.consentDefinition.findFirst({where:{id:definitionId,organizationId}})]);if(!event||!definition)throw new NotFoundException('Etkinlik veya onam bulunamadı.');return this.prisma.eventConsentRequirement.upsert({where:{eventId_definitionId:{eventId,definitionId}},create:{eventId,definitionId,required},update:{required}})}
 async publicRequirements(eventId:string){return this.prisma.eventConsentRequirement.findMany({where:{eventId},include:{definition:{include:{versions:{orderBy:{version:'desc'},take:1}}}}})}
 async validateSelection(eventId:string,versionIds:string[]){const requirements=await this.publicRequirements(eventId);const selected=new Set(versionIds);for(const r of requirements){const current=r.definition.versions[0];if(r.required&&(!current||!selected.has(current.id)))throw new BadRequestException(`Zorunlu onam eksik: ${r.definition.title}`)}const valid=requirements.flatMap(r=>r.definition.versions).filter(v=>selected.has(v.id));if(valid.length!==selected.size)throw new BadRequestException('Geçersiz veya eski onam sürümü.');return valid.map(v=>v.id)}
 async record(registrationId:string,versionIds:string[]){if(versionIds.length)await this.prisma.consentRecord.createMany({data:versionIds.map(consentVersionId=>({registrationId,consentVersionId}))});}
}
