'use client';
import { useMemo, useState } from 'react';
import { DoorRegistration } from './door-registration';

type Stats = { registered: number; checkedIn: number; remaining: number };
type RosterItem = { id: string; firstName: string; lastName: string; email: string; attendance: null | { status: string; confirmedAt: string; method: string } };
type Feature = { key: string; enabled: boolean };

export function FieldOperations({ organizationId, eventId, initialPhase, initialStats, initialRoster, initialFeatures }: { organizationId: string; eventId: string; initialPhase: string; initialStats: Stats; initialRoster: RosterItem[]; initialFeatures: Feature[] }) {
  const [phase, setPhase] = useState(initialPhase), [stats, setStats] = useState(initialStats), [roster, setRoster] = useState(initialRoster), [features, setFeatures] = useState(initialFeatures), [query, setQuery] = useState(''), [message, setMessage] = useState(''), [busy, setBusy] = useState(false);
  const featureKeys = ['check_in', 'door_registration', 'participant_area'] as const;
  const labels = { check_in: 'QR ile katılım teyidi', door_registration: 'Kapıda kayıt', participant_area: 'Katılımcı alanı' };
  const shown = useMemo(() => roster.filter(item => `${item.firstName} ${item.lastName} ${item.email}`.toLocaleLowerCase('tr').includes(query.toLocaleLowerCase('tr'))), [roster, query]);
  async function request(path: string, method = 'GET', body?: object) { const response = await fetch(`/api/backend/${path}`, { method, headers: { 'content-type': 'application/json' }, body: body ? JSON.stringify(body) : undefined }); const data = await response.json(); if (!response.ok) throw new Error(Array.isArray(data.message) ? data.message.join(' ') : data.message ?? 'İşlem tamamlanamadı.'); return data; }
  async function refresh() { const [nextStats, nextRoster] = await Promise.all([request(`organizations/${organizationId}/events/${eventId}/check-in/stats`), request(`organizations/${organizationId}/events/${eventId}/check-in/roster`)]); setStats(nextStats); setRoster(nextRoster); }
  async function start() { setBusy(true); try { await request(`organizations/${organizationId}/events/${eventId}/phase`, 'PATCH', { phase: 'LIVE' }); for (const key of featureKeys) await request(`organizations/${organizationId}/events/${eventId}/features/${key}`, 'PUT', { enabled: true, config: {} }); setPhase('LIVE'); setFeatures(current => current.map(feature => featureKeys.includes(feature.key as typeof featureKeys[number]) ? { ...feature, enabled: true } : feature)); setMessage('Etkinlik canlıya alındı; saha ve katılımcı özellikleri açıldı.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Etkinlik başlatılamadı.'); } finally { setBusy(false); } }
  async function toggle(key: typeof featureKeys[number]) { const enabled = !features.find(feature => feature.key === key)?.enabled; try { await request(`organizations/${organizationId}/events/${eventId}/features/${key}`, 'PUT', { enabled, config: {} }); setFeatures(current => current.map(feature => feature.key === key ? { ...feature, enabled } : feature)); setMessage(`${labels[key]} ${enabled ? 'açıldı' : 'kapatıldı'}.`); } catch (error) { setMessage(error instanceof Error ? error.message : 'Ayar değiştirilemedi.'); } }
  async function confirm(registrationId: string) { try { await request(`organizations/${organizationId}/events/${eventId}/check-in/manual`, 'POST', { registrationId }); await refresh(); setMessage('Katılım görevli tarafından teyit edildi.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Katılım teyit edilemedi.'); } }
  return <section className="field-operations"><div className="metric-grid field-metrics"><article><span>Kayıtlı</span><b>{stats.registered}</b></article><article><span>Teyit veren</span><b>{stats.checkedIn}</b></article><article><span>Beklenen</span><b>{stats.remaining}</b></article></div><article className="operations-card"><div className="operations-head"><div><p className="eyebrow">SAHA KONTROLÜ</p><h2>{phase === 'LIVE' ? 'Etkinlik canlı' : 'Etkinlik henüz başlamadı'}</h2></div>{phase !== 'LIVE' && <button className="primary" disabled={busy} onClick={start}>{busy ? 'Başlatılıyor…' : 'Etkinliği başlat'}</button>}</div>{phase !== 'LIVE' && <small className="field-help">“Etkinliği başlat” katılım teyidi, kapıda kayıt ve katılımcı alanını açar. Geri alınamaz.</small>}<div className="feature-switches">{featureKeys.map(key => <button key={key} className={features.find(feature => feature.key === key)?.enabled ? 'feature-on' : 'feature-off'} onClick={() => toggle(key)}>{labels[key]}: {features.find(feature => feature.key === key)?.enabled ? 'Açık' : 'Kapalı'}</button>)}</div>{message && <p className="notice" role="status">{message}</p>}</article><article className="operations-card roster"><div className="operations-head"><div><h2>Katılımcı listesi</h2><p>İsim veya e-posta ile arayın; QR kullanamayan kişiyi görevli olarak teyit edin.</p></div><a className="secondary link-button" href={`/api/backend/organizations/${organizationId}/events/${eventId}/check-in/signature.pdf`}>İmza formu PDF</a></div><small className="field-help">İnternet olmayan bir mekândaysanız imza formunu önceden indirip yazdırın; etkinlik sonrası katılımları buradan işaretleyebilirsiniz.</small><input className="roster-search" value={query} onChange={event => setQuery(event.target.value)} placeholder="İsim veya e-posta ara…"/><div className="roster-list">{shown.length === 0 ? <div className="hint-box">Aramayla eşleşen katılımcı yok.</div> : shown.map(item => <div className="roster-row" key={item.id}><div><b>{item.firstName} {item.lastName}</b><small>{item.email}</small></div>{item.attendance ? <span className="pill published">Teyit edildi</span> : <button className="secondary" onClick={() => confirm(item.id)}>Teyit et</button>}</div>)}</div></article><DoorRegistration organizationId={organizationId} eventId={eventId} onSuccess={refresh}/></section>;
}
