'use client';import{useState}from'react';
interface Registration{id:string;firstName:string;lastName:string;email:string;applicationStatus:string}
const statusLabel:Record<string,string>={SUBMITTED:'Gönderildi',PENDING:'Beklemede',ACCEPTED:'Kabul edildi',WAITLISTED:'Yedek listede',REJECTED:'Reddedildi'};
export function Applications({organizationId,initial}:{organizationId:string;initial:Registration[]}){
  const[rows,setRows]=useState(initial),[message,setMessage]=useState('');
  async function decide(id:string,status:string){const r=await fetch(`/api/backend/organizations/${organizationId}/registrations/${id}/decision`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({status})});const data=await r.json();if(r.ok)setRows(v=>v.map(x=>x.id===id?{...x,applicationStatus:data.applicationStatus}:x));else setMessage(Array.isArray(data.message)?data.message.join(' '):data.message)}
  if(!rows.length)return <section className="empty-state"><span className="empty-illustration">✦</span><h2>Henüz başvuru yok</h2><p>Etkinlik sayfası üzerinden gelen başvurular burada görünecek.</p></section>;
  return <section className="applications">{message&&<p className="notice">{message}</p>}<table><thead><tr><th>Katılımcı</th><th>E-posta</th><th>Durum</th><th>İşlem</th></tr></thead><tbody>{rows.map(r=>{const s=r.applicationStatus;return <tr key={r.id}><td>{r.firstName} {r.lastName}</td><td>{r.email}</td><td><span className={`pill ${s==='ACCEPTED'?'published':''}`}>{statusLabel[s]??s}</span></td><td className="action-links">{s!=='ACCEPTED'&&<button className="secondary" onClick={()=>decide(r.id,'ACCEPTED')}>Kabul et</button>}{s!=='WAITLISTED'&&<button className="secondary" onClick={()=>decide(r.id,'WAITLISTED')}>Yedek listeye al</button>}{s!=='REJECTED'&&<button className="secondary" onClick={()=>decide(r.id,'REJECTED')}>Reddet</button>}</td></tr>})}</tbody></table></section>;
}
