'use client';
import { FormEvent, useMemo, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { Applications } from './applications';
import { FaqEditor, FormFieldEditor } from './visual-editors';
import { MarkdownEditor } from '../new/markdown-editor';

type Faq={question:string;answer:string};type Field={key:string;type:string;label:string;required?:boolean;options?:string[]};
type EventInfo={id:string;title:string;slug:string;summary?:string;description?:string;venueName?:string;venueAddress?:string;format?:string;onlineLink?:string;startsAt:string;endsAt:string;publicationStatus:string;registrationStatus:string;phase:string;visibility:string;registrationMode:string;capacity:number;formId?:string;faqs:Faq[];_count:{registrations:number}};
type Registration={id:string;firstName:string;lastName:string;email:string;applicationStatus:string};
type FormInfo={id:string;name:string;versions:Array<{version:number;schema:{fields?:Field[]}}>};
type Template={id:string;key:string;subject:string;body:string};
type Consent={definition:{id:string;title:string;versions:Array<{id:string;version:number;text:string}>};required:boolean};
type Reminder={id:string;sendAt:string;status:string;template:{key:string;subject:string}};
export type EventSection='dashboard'|'settings'|'communication';
const labelMap:Record<string,string>={DRAFT:'Taslak',PUBLISHED:'Yayında',UNPUBLISHED:'Yayın dışı',ARCHIVED:'Arşivlendi',OPEN:'Kayıt açık',CLOSED:'Kayıt kapalı',NOT_OPEN:'Başlamadı',PRE_EVENT:'Hazırlık',LIVE:'Canlı',POST_EVENT:'Tamamlandı',PUBLIC:'Herkese açık',LINK_ONLY:'Bağlantıya sahip olanlar',INVITE_ONLY:'Yalnız davetliler',DIRECT:'Doğrudan kayıt',APPROVAL:'Onaylı başvuru',WAITLIST:'Yedek liste',OFFLINE:'Yüz yüze',ONLINE:'Çevrim içi',HYBRID:'Hibrit'};
const L=(v?:string)=>v?labelMap[v]??v:'—';

async function request(path:string,options:RequestInit={}) {
  const response=await fetch(`/api/backend/${path}`,{...options,headers:{'content-type':'application/json',...(options.headers??{})}});
  const data=await response.json().catch(()=>({message:'İşlem tamamlanamadı.'}));
  if(!response.ok)throw new Error(Array.isArray(data.message)?data.message.join(' '):data.message);
  return data;
}

export function EventWorkspace({organization,event:initialEvent,initialRegistrations,forms,templates,consents,initialReminders,section='dashboard',initialSubtab='overview'}:{organization:{id:string;slug:string};event:EventInfo;initialRegistrations:unknown[];forms:unknown[];templates:unknown[];consents:unknown[];initialReminders:unknown[];section?:EventSection;initialSubtab?:string}) {
  const[event,setEvent]=useState(initialEvent),[subtab,setSubtab]=useState(initialSubtab),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[reminders,setReminders]=useState(initialReminders as Reminder[]),[settingsFormat,setSettingsFormat]=useState<string>(initialEvent.format??'OFFLINE'),[notifTitle,setNotifTitle]=useState(''),[notifBody,setNotifBody]=useState(''),[notifAudience,setNotifAudience]=useState('ACCEPTED'),[descDraft,setDescDraft]=useState(initialEvent.description??''),[summaryDraft,setSummaryDraft]=useState(initialEvent.summary??'');
  const publicUrl=`/events/${organization.slug}/${event.slug}`,base=`/dashboard/events/${event.id}`;
  const typedForms=forms as FormInfo[],typedTemplates=templates as Template[],typedConsents=consents as Consent[];
  const accepted=useMemo(()=>(initialRegistrations as Registration[]).filter(r=>r.applicationStatus==='ACCEPTED').length,[initialRegistrations]);
  const published=event.publicationStatus==='PUBLISHED';
  const registrationOpen=event.registrationStatus==='OPEN';
  async function run(action:()=>Promise<unknown>,success:string){setBusy(true);setNotice('');try{await action();setNotice(success)}catch(error){setNotice(error instanceof Error?error.message:'İşlem tamamlanamadı.')}finally{setBusy(false)}}
  async function state(publicationStatus:string,registrationStatus:string){await run(async()=>{await request(`organizations/${organization.id}/events/${event.id}/state`,{method:'PATCH',body:JSON.stringify({publicationStatus,registrationStatus})});setEvent(value=>({...value,publicationStatus,registrationStatus}))},'Etkinlik durumu güncellendi.');}
  async function togglePublish(){await state(published?'UNPUBLISHED':'PUBLISHED',event.registrationStatus)}
  async function toggleRegistration(){const target=registrationOpen?'CLOSED':'OPEN';if(!registrationOpen&&!published){await state('PUBLISHED','OPEN')}else{await state(event.publicationStatus,target)}}
  async function deleteEvent(){if(confirm('Etkinlik 30 gün boyunca geri alınabilir, sonra kalıcı silinir. Emin misiniz?'))await run(async()=>{await request(`organizations/${organization.id}/events/${event.id}/deletion`,{method:'POST'})},'Etkinlik silme işlemi başlatıldı. 30 gün içinde geri alabilirsiniz.')}
  async function goLive(){if(!confirm('Etkinlik canlıya alınacak. Katılımcı alanı, oyunlar, testler, geri bildirim, duyurular ve katılım teyidi açılacak. Devam edilsin mi?'))return;await run(async()=>{await request(`organizations/${organization.id}/events/${event.id}/phase`,{method:'PATCH',body:JSON.stringify({phase:'LIVE'})});for(const key of['check_in','door_registration','participant_area','assessments','feedback','icebreaker','groups'])await request(`organizations/${organization.id}/events/${event.id}/features/${key}`,{method:'PUT',body:JSON.stringify({enabled:true,config:{}})});setEvent(value=>({...value,phase:'LIVE'}))},'🎉 Etkinlik canlıya alındı! Tüm modüller aktif.')}
  async function invite(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,email=String(new FormData(form).get('email'));await run(()=>request(`organizations/${organization.id}/events/${event.id}/invitations`,{method:'POST',body:JSON.stringify({email})}),'Davet oluşturuldu.');form.reset()}
  async function addConsent(e:FormEvent<HTMLFormElement>){e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget));await run(async()=>{const consent=await request(`organizations/${organization.id}/consents`,{method:'POST',body:JSON.stringify({key:`event-${event.id}-${Date.now()}`,title:values.title,text:values.text})});await request(`organizations/${organization.id}/events/${event.id}/consents/${consent.id}`,{method:'PUT',body:JSON.stringify({required:true})})},'Zorunlu onam eklendi. Sayfayı yenilediğinizde listede görünecek.');e.currentTarget.reset()}
  async function reminder(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,values=Object.fromEntries(new FormData(form)),template=typedTemplates.find(item=>item.id===values.templateId);await run(async()=>{const created=await request(`organizations/${organization.id}/events/${event.id}/reminders`,{method:'POST',body:JSON.stringify({templateId:values.templateId,sendAt:new Date(String(values.sendAt)).toISOString()})});setReminders(rows=>[...rows,{...created,template:{key:template?.key??'',subject:template?.subject??''}}])},'Hatırlatma planlandı.');form.reset()}
  async function saveSettings(e:FormEvent<HTMLFormElement>){e.preventDefault();const values=new FormData(e.currentTarget),faqs=(JSON.parse(String(values.get('faqs')??'[]'))as Faq[]).filter(item=>item.question.trim()&&item.answer.trim());const payload={title:values.get('title'),summary:values.get('summary'),description:values.get('description'),venueName:values.get('venueName'),venueAddress:values.get('venueAddress'),format:values.get('format'),onlineLink:values.get('onlineLink')||undefined,startsAt:new Date(String(values.get('startsAt'))).toISOString(),endsAt:new Date(String(values.get('endsAt'))).toISOString(),capacity:Number(values.get('capacity')),visibility:values.get('visibility'),registrationMode:values.get('registrationMode'),formId:values.get('formId')||undefined,faqs};await run(async()=>{const updated=await request(`organizations/${organization.id}/events/${event.id}`,{method:'PATCH',body:JSON.stringify(payload)});setEvent(value=>({...value,...updated}))},'Harika, etkinlik bilgileriniz kaydedildi.')}
  async function publishForm(e:FormEvent<HTMLFormElement>){e.preventDefault();const values=new FormData(e.currentTarget),formId=String(values.get('formId')),fields=(JSON.parse(String(values.get('fields')??'[]'))as Field[]).filter(item=>item.label.trim());await run(()=>request(`organizations/${organization.id}/forms/${formId}/versions`,{method:'POST',body:JSON.stringify({schema:{fields}})}),'Harika, kayıt formunun yeni sürümü yayınlandı.')}
  async function updateTemplate(e:FormEvent<HTMLFormElement>,id:string){e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget));await run(()=>request(`organizations/${organization.id}/email-templates/${id}`,{method:'PATCH',body:JSON.stringify(values)}),'E-posta şablonu güncellendi.')}
  async function cancelReminder(id:string){await run(async()=>{await request(`organizations/${organization.id}/events/${event.id}/reminders/${id}`,{method:'DELETE'});setReminders(rows=>rows.map(row=>row.id===id?{...row,status:'CANCELLED'}:row))},'Hatırlatma iptal edildi.')}
  async function sendNotification(e:FormEvent<HTMLFormElement>){e.preventDefault();await run(async()=>{const r=await fetch(`/api/backend/organizations/${organization.id}/events/${event.id}/notifications`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({title:notifTitle,body:notifBody,audience:notifAudience})});const data=await r.json();if(!r.ok)throw new Error(Array.isArray(data.message)?data.message.join(' '):data.message);if(data.recipientCount)setNotice(`Duyuru ${data.recipientCount} kişiye gönderildi.`)},'Duyuru gönderildi.');setNotifTitle('');setNotifBody('')}
  const router=useRouter();
  const setTab=(t:string)=>setSubtab(t);
  const subLink=(href:string,label:string,key:string)=><Link href={href} className={subtab===key?'active':''} onClick={e=>{e.preventDefault();setSubtab(key);router.push(href);router.refresh()}}>{label}</Link>;

  return <>
    {/* Eylem çubuğu */}
    <div className="event-toolbar">
      <div className="event-toolbar-group">
        <button className={`toggle-switch ${published?'on':''}`} onClick={togglePublish} disabled={busy} title="Etkinlik sayfasını yayınla/kaldır"><span>Yayın</span><span className="toggle-track"/></button>
        <button className={`toggle-switch ${registrationOpen?'on':''}`} onClick={toggleRegistration} disabled={busy} title="Kayıt alımını aç/kapat (gerekirse yayını da açar)"><span>Kayıt</span><span className="toggle-track"/></button>
      </div>
      <div className="event-toolbar-spacer"/>
      {event.phase==='PRE_EVENT'&&<button className="toolbar-btn primary" onClick={goLive} disabled={busy} title="Etkinliği canlıya al — katılımcı alanı, oyunlar ve duyurular açılır">🔴 Canlıya al</button>}
      {event.phase==='LIVE'&&<button className="toolbar-btn" disabled title="Etkinlik canlı">🟢 Canlıda</button>}
      <a className="toolbar-btn" href={publicUrl} target="_blank" rel="noopener noreferrer">🔗 Etkinlik sayfasını aç</a>
      <a className="toolbar-btn" href={`${base}/communication?subtab=notifications`}>📢 Duyuru</a>
      <button className="toolbar-btn danger" onClick={deleteEvent} disabled={busy} title="Etkinliği sil (30 gün geri alınabilir)">🗑 Sil</button>
    </div>

    {notice&&<p className="notice" role="status">{notice}</p>}

    {/* ============ DASHBOARD (Genel Bakış) ============ */}
    {section==='dashboard'&&<section className="workspace-grid">
      <article className="workspace-card wide"><p className="eyebrow">KATILIMCI DURUMU</p><h2>Katılım görünümü</h2><div className="metric-grid"><div><span>Başvuru</span><b>{initialRegistrations.length}</b></div><div><span>Kabul</span><b>{accepted}</b></div><div><span>Kontenjan</span><b>{event.capacity}</b></div>{(event.phase==='LIVE'||event.phase==='POST_EVENT')&&<div><span>Doluluk</span><b>%{event.capacity?Math.round(accepted/event.capacity*100):0}</b></div>}</div></article>
      <article className="workspace-card wide roadmap-card"><p className="eyebrow">YOL HARİTASI</p><h2>Sıradaki adımlar</h2>{event.phase==='PRE_EVENT'&&event.publicationStatus==='DRAFT'&&<><p className="roadmap-current">Etkinliğiniz taslak halinde. Şunları tamamlayın:</p><ol className="roadmap-steps"><li><b>Bilgileri düzenleyin</b> — başlık, açıklama, tarih ve mekân.<a className="link-button" href={`${base}/settings?subtab=info`}>Bilgileri düzenle →</a></li><li><b>Kayıt formunu kontrol edin</b>.<a className="link-button" href={`${base}/settings?subtab=forms`}>Formu düzenle →</a></li><li><b>Yayınlayın</b> — üstteki Yayın toggle'ını açın.</li></ol></>}{event.phase==='PRE_EVENT'&&event.publicationStatus!=='DRAFT'&&<><p className="roadmap-current">Etkinliğiniz yayında. Şunları yapabilirsiniz:</p><ol className="roadmap-steps"><li><b>Başvuruları takip edin</b>.<a className="link-button" href={`${base}/settings?subtab=applications`}>Başvurulara bak → ({initialRegistrations.length})</a></li><li><b>Katılımcılara bilgi verin</b>.<a className="link-button" href={`${base}/communication?subtab=reminders`}>Hatırlatmalar →</a></li><li><b>Etkinlik günü yaklaşınca</b> — kontrol merkezinden canlıya alın.</li></ol></>}{event.phase==='LIVE'&&<><p className="roadmap-current">🎉 Etkinlik canlı!</p><ol className="roadmap-steps"><li><b>Katılım teyidi</b>.<a className="link-button" href={`${base}/day`} target="_blank" rel="noopener noreferrer">Kontrol merkezine git →</a></li><li><b>Modüller</b> — gruplar, oyun, testler.<a className="link-button" href={`${base}/modules`}>Modülleri yönet →</a></li></ol></>}{event.phase==='POST_EVENT'&&<><p className="roadmap-current">Etkinlik tamamlandı.</p><ol className="roadmap-steps"><li><b>Raporları indirin</b>.<a className="link-button" href={`${base}/post-event`}>Sonuçlara git →</a></li><li><b>Sertifikaları üretin</b>.<a className="link-button" href={`${base}/post-event`}>Sertifikalar →</a></li></ol></>}{event.phase==='ARCHIVED'&&<p className="roadmap-current">Bu etkinlik arşivlendi/silme sürecinde.</p>}</article>
      <article className="workspace-card"><p className="eyebrow">DURUM</p><h2>Etkinlik bilgileri</h2><p><b>{new Intl.DateTimeFormat('tr-TR',{dateStyle:'long',timeStyle:'short'}).format(new Date(event.startsAt))}</b></p>{event.venueName&&<p>📍 {event.venueName}</p>}{event.onlineLink&&<p>🔗 <a href={event.onlineLink} target="_blank" rel="noopener noreferrer">Çevrim içi katılım linki</a></p>}<div className="status-row" style={{marginTop:'.5rem'}}><span className="pill">{L(event.publicationStatus)}</span><span className="pill">{L(event.registrationStatus)}</span><span className="pill">{L(event.phase)}</span></div></article>
      <article className="workspace-card"><p className="eyebrow">KURALLAR</p><h2>Etkinlik ayarları</h2><dl><dt>Görünürlük</dt><dd>{L(event.visibility)}</dd><dt>Kayıt modeli</dt><dd>{L(event.registrationMode)}</dd><dt>Tür</dt><dd>{L(event.format)}</dd></dl><a className="link-button" href={`${base}/settings?subtab=info`}>Bilgileri düzenle →</a></article>
    </section>}

    {/* ============ AYARLAR ============ */}
    {section==='settings'&&<>
      <nav className="workspace-tabs" aria-label="Ayarlar bölümleri">
        {subLink(`${base}/settings?subtab=info`,'Bilgiler','info')}
        {subLink(`${base}/settings?subtab=faq`,'SSS','faq')}
        {subLink(`${base}/settings?subtab=applications`,`Başvurular (${initialRegistrations.length})`,'applications')}
        {subLink(`${base}/settings?subtab=forms`,'Formlar ve Onam','forms')}
        {subLink(`${base}/settings?subtab=invite`,'Davet','invite')}
        {subLink(`${base}/settings?subtab=reminders`,'Hatırlatmalar','reminders')}
        <a className="toolbar-btn" href={`${base}/modules`} style={{marginLeft:'auto'}}>Testler ↗</a>
      </nav>
      {subtab==='info'&&<form className="workspace-card event-settings" onSubmit={saveSettings}>
        <div className="settings-section"><div className="section-intro"><h2>Temel bilgiler</h2><p>Etkinliğin ana kimliğini belirleyin.</p></div><label>Etkinlik adı<input name="title" required defaultValue={event.title}/></label><label>Kısa açıklama (özet) <span className="tooltip" data-tip="Boş bırakırsanız ayrıntılı açıklamadan otomatik oluşturulur. İsterseniz elle düzenleyin.">(?)</span><textarea name="summary" value={summaryDraft} onChange={e=>setSummaryDraft(e.target.value)} placeholder="Boş bırakılırsa açıklamadan otomatik oluşturulur."/></label><label>Ayrıntılı açıklama <span className="tooltip" data-tip="Markdown desteklenir: **kalın**, *italik*, ## başlık, - madde işareti">(?)</span><MarkdownEditor value={descDraft} onChange={v=>{setDescDraft(v);if(!summaryDraft.trim())setSummaryDraft(v.replace(/[#*`\[\]()_-]/g,'').replace(/\n+/g,' ').trim().slice(0,150))}} placeholder={"## Hakkında\n\nEtkinlik ayrıntılarını yazın."} rows={6}/><input type="hidden" name="description" value={descDraft}/></label></div>
        <div className="settings-section"><div className="section-intro"><h2>Tarih ve mekân</h2><p>Etkinlik ne zaman ve nerede?</p></div><div className="two"><label>Başlangıç<input name="startsAt" type="datetime-local" required defaultValue={event.startsAt.slice(0,16)}/></label><label>Bitiş<input name="endsAt" type="datetime-local" required defaultValue={event.endsAt.slice(0,16)}/></label></div><label>Etkinlik türü<select name="format" value={settingsFormat} onChange={e=>setSettingsFormat(e.target.value)}><option value="OFFLINE">Yüz yüze (Offline)</option><option value="ONLINE">Çevrim içi (Online)</option><option value="HYBRID">Hibrit</option></select></label>{settingsFormat!=='ONLINE'&&<div className="two"><label>Mekân adı<input name="venueName" defaultValue={event.venueName} placeholder="Örn. Konferans Salonu"/></label><label>Adres<input name="venueAddress" defaultValue={event.venueAddress} placeholder="Tam adres"/></label></div>}{(settingsFormat==='ONLINE'||settingsFormat==='HYBRID')&&<label>Çevrim içi katılım linki<input name="onlineLink" defaultValue={event.onlineLink} placeholder="Etkinlik linki kısa süre içinde paylaşılacak"/></label>}</div>
        <div className="settings-section"><div className="section-intro"><h2>Kayıt ayarları</h2><p>Katılım kontenjanı ve kayıt kuralları.</p></div><div className="two"><label>Kontenjan<input name="capacity" type="number" min="1" required defaultValue={event.capacity}/></label><label>Kayıt modeli<select name="registrationMode" defaultValue={event.registrationMode}><option value="DIRECT">Doğrudan — otomatik kabul</option><option value="APPROVAL">Onaylı — manuel değerlendirme</option><option value="WAITLIST">Yedek liste — dolunca bekleme</option></select></label></div><details className="advanced-settings"><summary>Görünürlük ve gelişmiş ayarlar</summary><label>Görünürlük <span className="tooltip" data-tip="Herkese açık: sayfa herkese görünür. Bağlantıya sahip olanlar: linki bilenler. Yalnız davetliler: sadece davet edilen hesaplar.">(?)</span><select name="visibility" defaultValue={event.visibility}><option value="PUBLIC">Herkese açık</option><option value="LINK_ONLY">Bağlantıya sahip olanlar</option><option value="INVITE_ONLY">Yalnız davetliler</option></select></label></details></div>
        <button className="primary" disabled={busy}>Değişiklikleri kaydet</button>
      </form>}
      {subtab==='faq'&&<form className="workspace-card" onSubmit={saveSettings}><div className="section-intro"><h2>Sık sorulan sorular</h2><p>Katılımcıların merak edeceği soruları ekleyin.</p></div><input type="hidden" name="title" defaultValue={event.title}/><input type="hidden" name="summary" defaultValue={event.summary}/><input type="hidden" name="description" defaultValue={event.description}/><input type="hidden" name="venueName" defaultValue={event.venueName}/><input type="hidden" name="venueAddress" defaultValue={event.venueAddress}/><input type="hidden" name="format" defaultValue={event.format}/><input type="hidden" name="onlineLink" defaultValue={event.onlineLink}/><input type="hidden" name="startsAt" defaultValue={event.startsAt.slice(0,16)}/><input type="hidden" name="endsAt" defaultValue={event.endsAt.slice(0,16)}/><input type="hidden" name="capacity" defaultValue={event.capacity}/><input type="hidden" name="registrationMode" defaultValue={event.registrationMode}/><input type="hidden" name="visibility" defaultValue={event.visibility}/><FaqEditor initial={event.faqs??[]}/><button className="primary" disabled={busy}>SSS'i kaydet</button></form>}
      {subtab==='applications'&&<Applications organizationId={organization.id} initial={initialRegistrations as Registration[]}/>}
      {subtab==='forms'&&<section className="workspace-grid"><article className="workspace-card wide"><div className="section-intro"><h2>Bu etkinliğin kayıt formu</h2><p>Katılımcıdan hangi bilgilerin isteneceğini buradan yönetin.</p></div>{typedForms.length?<div className="list-row"><div><b>{typedForms[0].name}</b><small>Sürüm {typedForms[0].versions[0]?.version??1} · {typedForms[0].versions[0]?.schema?.fields?.length??0} özel alan</small></div></div>:<div className="hint-box">Bu etkinliğe henüz form bağlı değil.</div>}</article><form className="workspace-card wide" onSubmit={publishForm}><div className="form-heading"><h2>Form alanlarını düzenle</h2><p>Ad, soyad ve e-posta standart olarak alınır. Yalnızca ek bilgileri tanımlayın.</p></div>{typedForms[0]&&<input type="hidden" name="formId" value={typedForms[0].id}/>}<FormFieldEditor/><button className="primary" disabled={busy||!typedForms.length}>Yeni sürümü yayınla</button></form><form className="workspace-card" onSubmit={addConsent}><div className="section-intro"><h2>Zorunlu onam ekle</h2><p>KVKK, fotoğraf izni veya etkinliğe özgü şartlar için.</p></div><label>Başlık<input name="title" required placeholder="KVKK ve fotoğraf izni"/></label><label>Onam metni<textarea name="text" required minLength={20} placeholder="Katılımcının göreceği onam metnini yazın…"/></label><button className="primary" disabled={busy}>Onamı ekle</button></form><article className="workspace-card"><div className="section-intro"><h2>Etkinlik onamları</h2></div>{typedConsents.length?typedConsents.map(item=><div className="list-row" key={item.definition.id}><div><b>{item.definition.title}</b><small>Sürüm {item.definition.versions[0]?.version} · {item.required?'Zorunlu':'İsteğe bağlı'}</small></div></div>):<div className="hint-box">Bu etkinlikte onam yok.</div>}</article></section>}
      {subtab==='invite'&&<section className="workspace-grid"><form className="workspace-card" onSubmit={invite}><div className="section-intro"><h2>Katılımcı davet et</h2><p>Davetli etkinliklerde davet edilen hesaplar kayıt olabilir.</p></div><label>E-posta<input name="email" type="email" required placeholder="katilimci@ornek.com"/></label><button className="primary" disabled={busy}>Davet oluştur</button></form><article className="workspace-card wide"><div className="section-intro"><h2>E-posta şablonları</h2><p>Konu ve içerikte değişkenleri koruyarak düzenleyin.</p></div><div className="template-editor">{typedTemplates.map(t=><form key={t.id} className="template-form" onSubmit={e=>updateTemplate(e,t.id)}><b>{t.key}</b><label>Konu<input name="subject" defaultValue={t.subject} required/></label><label>İçerik<textarea name="body" defaultValue={t.body} required rows={5}/></label><button className="secondary" disabled={busy}>Şablonu kaydet</button></form>)}</div></article></section>}
      {subtab==='reminders'&&<section className="workspace-grid"><form className="workspace-card" onSubmit={reminder}><div className="section-intro"><h2>Hatırlatma planla</h2><p>Katılımcılara etkinlik öncesi otomatik hatırlatma gönderin.</p></div><label>Şablon<select name="templateId" required>{typedTemplates.map(t=><option value={t.id} key={t.id}>{t.key} — {t.subject}</option>)}</select></label><label>Gönderim zamanı<input name="sendAt" type="datetime-local" required/></label><button className="primary" disabled={busy||!typedTemplates.length}>Hatırlatmayı planla</button></form><article className="workspace-card wide"><div className="section-intro"><h2>Planlanmış hatırlatmalar</h2></div>{reminders.length?reminders.map(item=><div className="list-row" key={item.id}><div><b>{item.template?.subject||item.template?.key}</b><small>{new Intl.DateTimeFormat('tr-TR',{dateStyle:'long',timeStyle:'short'}).format(new Date(item.sendAt))} · {item.status}</small></div>{item.status==='SCHEDULED'&&<button className="secondary" onClick={()=>cancelReminder(item.id)}>İptal et</button>}</div>):<div className="hint-box">Henüz hatırlatma planlanmadı.</div>}</article></section>}
    </>}

    {/* ============ İLETİŞİM ============ */}
    {section==='communication'&&<>
      <nav className="workspace-tabs" aria-label="İletişim bölümleri">
        {subLink(`${base}/communication?subtab=reminders`,'Hatırlatmalar','reminders')}
        {subLink(`${base}/communication?subtab=invite`,'Davet','invite')}
        {subLink(`${base}/communication?subtab=notifications`,'Duyurular','notifications')}
        {subLink(`${base}/communication?subtab=resources`,'Kaynak Paylaş','resources')}
        {subLink(`${base}/communication?subtab=photos`,'Etkinlik Fotoğrafları','photos')}
      </nav>
      {subtab==='reminders'&&<section className="workspace-grid"><form className="workspace-card" onSubmit={reminder}><div className="section-intro"><h2>Hatırlatma planla</h2></div><label>Şablon<select name="templateId" required>{typedTemplates.map(t=><option value={t.id} key={t.id}>{t.key} — {t.subject}</option>)}</select></label><label>Gönderim zamanı<input name="sendAt" type="datetime-local" required/></label><button className="primary" disabled={busy}>Hatırlatmayı planla</button></form><article className="workspace-card wide"><div className="section-intro"><h2>Planlanmış hatırlatmalar</h2></div>{reminders.length?reminders.map(item=><div className="list-row" key={item.id}><div><b>{item.template?.subject||item.template?.key}</b><small>{new Intl.DateTimeFormat('tr-TR',{dateStyle:'long',timeStyle:'short'}).format(new Date(item.sendAt))} · {item.status}</small></div>{item.status==='SCHEDULED'&&<button className="secondary" onClick={()=>cancelReminder(item.id)}>İptal et</button>}</div>):<div className="hint-box">Henüz hatırlatma planlanmadı.</div>}</article></section>}
      {subtab==='invite'&&<section className="workspace-grid"><form className="workspace-card" onSubmit={invite}><div className="section-intro"><h2>Katılımcı davet et</h2></div><label>E-posta<input name="email" type="email" required placeholder="katilimci@ornek.com"/></label><button className="primary" disabled={busy}>Davet oluştur</button></form><article className="workspace-card wide"><div className="section-intro"><h2>E-posta şablonları</h2></div><div className="template-editor">{typedTemplates.map(t=><form key={t.id} className="template-form" onSubmit={e=>updateTemplate(e,t.id)}><b>{t.key}</b><label>Konu<input name="subject" defaultValue={t.subject} required/></label><label>İçerik<textarea name="body" defaultValue={t.body} required rows={5}/></label><button className="secondary" disabled={busy}>Şablonu kaydet</button></form>)}</div></article></section>}
      {subtab==='notifications'&&<form className="workspace-card" onSubmit={sendNotification}><div className="section-intro"><h2>Duyuru gönderin</h2><p>Bu mesaj seçtiğiniz katılımcıların etkinlik alanında anlık bildirim olarak görünür.</p></div><label>Hedef kitle <span className="tooltip" data-tip="Kabul edilenler: başvurusu kabul edilmiş. Katılım teyidi verenler: giriş yapmış. Tüm kayıtlılar: başvuran herkes.">(?)</span><select value={notifAudience} onChange={e=>setNotifAudience(e.target.value)}><option value="ACCEPTED">Kabul edilenler</option><option value="CHECKED_IN">Katılım teyidi verenler</option><option value="ALL">Tüm kayıtlılar</option></select></label><label>Başlık<input value={notifTitle} onChange={e=>setNotifTitle(e.target.value)} required placeholder="Örn. Öğle arası saati değişti"/></label><label>Mesaj<textarea value={notifBody} onChange={e=>setNotifBody(e.target.value)} required placeholder="Kısa ve net bir duyuru yazın."/></label><button className="primary" disabled={busy||!notifTitle||!notifBody}>Duyuruyu gönder</button></form>}
      {subtab==='resources'&&<section className="workspace-grid"><form className="workspace-card" onSubmit={async e=>{e.preventDefault();const d=new FormData(e.currentTarget);await run(async()=>{await request(`organizations/${organization.id}/events/${event.id}/resources/link`,{method:'POST',body:JSON.stringify({title:d.get('title'),url:d.get('url')})})},'Kaynak bağlantısı paylaşıldı.')}}><div className="section-intro"><h2>Bağlantı paylaş</h2><p>Harici bir bağlantı (sunum, anket) paylaşın.</p></div><label>Başlık<input name="title" required placeholder="Örn. Etkinlik sunumu"/></label><label>URL<input name="url" type="url" required placeholder="https://…"/></label><button className="primary" disabled={busy}>Paylaş</button></form><form className="workspace-card" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget),file=f.get('file')as File;if(!file)return;setBusy(true);try{const grant=await request(`organizations/${organization.id}/events/${event.id}/resources/upload`,{method:'POST',body:JSON.stringify({name:file.name,contentType:file.type,sizeBytes:file.size})});const uploaded=await fetch(String(grant.uploadUrl).replace('/api/','/api/backend/'),{method:'PUT',headers:{'content-type':file.type},body:file});if(uploaded.ok)await request(`organizations/${organization.id}/events/${event.id}/resources/confirm`,{method:'POST',body:JSON.stringify({title:f.get('title'),assetId:grant.assetId,reservationId:grant.reservationId})});setNotice('Dosya paylaşıldı.')}catch(err){setNotice('Dosya yüklenemedi.')}finally{setBusy(false)}}}><div className="section-intro"><h2>Dosya paylaş</h2><p>PDF, doküman yükleyin. Katılımcılar indirebilir.</p></div><label>Başlık<input name="title" required placeholder="Örn. Etkinlik raporu"/></label><label>Dosya<input name="file" type="file" required/></label><button className="primary" disabled={busy}>Yükle ve paylaş</button></form></section>}
      {subtab==='photos'&&<article className="workspace-card"><div className="section-intro"><h2>Etkinlik fotoğrafları</h2><p>Katılımcıların yüklediği fotoğrafları burada yönetebilirsiniz.</p></div><div className="hint-box">Fotoğraf moderasyonu için <a href={`${base}/post-event`}>Etkinlik Sonrası</a> sayfasına gidin.</div></article>}
    </>}
  </>;
}
