'use client';
import { FormEvent, useMemo, useState } from 'react';
import { Applications } from './applications';

type Faq={question:string;answer:string};type Field={key:string;type:string;label:string;required?:boolean;options?:string[]};
type EventInfo={id:string;title:string;slug:string;summary?:string;description?:string;venueName?:string;venueAddress?:string;startsAt:string;endsAt:string;publicationStatus:string;registrationStatus:string;phase:string;visibility:string;registrationMode:string;capacity:number;formId?:string;faqs:Faq[];_count:{registrations:number}};
type Registration={id:string;firstName:string;lastName:string;email:string;applicationStatus:string};
type FormInfo={id:string;name:string;versions:Array<{version:number;schema:{fields?:Field[]}}>};
type Template={id:string;key:string;subject:string;body:string};
type Consent={definition:{id:string;title:string;versions:Array<{id:string;version:number;text:string}>};required:boolean};
type Reminder={id:string;sendAt:string;status:string;template:{key:string;subject:string}};

async function request(path:string,options:RequestInit={}) {
  const response=await fetch(`/api/backend/${path}`,{...options,headers:{'content-type':'application/json',...(options.headers??{})}});
  const data=await response.json().catch(()=>({message:'İşlem tamamlanamadı.'}));
  if(!response.ok)throw new Error(Array.isArray(data.message)?data.message.join(' '):data.message);
  return data;
}

export function EventWorkspace({organization,event:initialEvent,initialRegistrations,forms,templates,consents,initialReminders}:{organization:{id:string;slug:string};event:EventInfo;initialRegistrations:unknown[];forms:unknown[];templates:unknown[];consents:unknown[];initialReminders:unknown[]}) {
  const[event,setEvent]=useState(initialEvent),[tab,setTab]=useState<'overview'|'settings'|'applications'|'forms'|'communication'>('overview'),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[reminders,setReminders]=useState(initialReminders as Reminder[]);
  const publicUrl=`/events/${organization.slug}/${event.slug}`;
  const typedForms=forms as FormInfo[],typedTemplates=templates as Template[],typedConsents=consents as Consent[];
  const accepted=useMemo(()=>(initialRegistrations as Registration[]).filter(r=>r.applicationStatus==='ACCEPTED').length,[initialRegistrations]);
  async function run(action:()=>Promise<unknown>,success:string){setBusy(true);setNotice('');try{await action();setNotice(success)}catch(error){setNotice(error instanceof Error?error.message:'İşlem tamamlanamadı.')}finally{setBusy(false)}}
  async function state(publicationStatus:string,registrationStatus:string){await run(async()=>{await request(`organizations/${organization.id}/events/${event.id}/state`,{method:'PATCH',body:JSON.stringify({publicationStatus,registrationStatus})});setEvent(value=>({...value,publicationStatus,registrationStatus}))},'Etkinlik durumu güncellendi.');}
  async function invite(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,email=String(new FormData(form).get('email'));await run(()=>request(`organizations/${organization.id}/events/${event.id}/invitations`,{method:'POST',body:JSON.stringify({email})}),'Davet oluşturuldu.');form.reset()}
  async function addConsent(e:FormEvent<HTMLFormElement>){e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget));await run(async()=>{const consent=await request(`organizations/${organization.id}/consents`,{method:'POST',body:JSON.stringify({key:`event-${event.id}-${Date.now()}`,title:values.title,text:values.text})});await request(`organizations/${organization.id}/events/${event.id}/consents/${consent.id}`,{method:'PUT',body:JSON.stringify({required:true})})},'Zorunlu onam eklendi. Sayfayı yenilediğinizde listede görünecek.');e.currentTarget.reset()}
  async function reminder(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,values=Object.fromEntries(new FormData(form)),template=typedTemplates.find(item=>item.id===values.templateId);await run(async()=>{const created=await request(`organizations/${organization.id}/events/${event.id}/reminders`,{method:'POST',body:JSON.stringify({templateId:values.templateId,sendAt:new Date(String(values.sendAt)).toISOString()})});setReminders(rows=>[...rows,{...created,template:{key:template?.key??'',subject:template?.subject??''}}])},'Hatırlatma planlandı.');form.reset()}
  async function saveSettings(e:FormEvent<HTMLFormElement>){e.preventDefault();const values=new FormData(e.currentTarget),faqs=String(values.get('faqs')??'').split('\n').map(line=>line.split('|').map(v=>v.trim())).filter(parts=>parts[0]&&parts[1]).map(([question,answer])=>({question,answer}));const payload={title:values.get('title'),summary:values.get('summary'),description:values.get('description'),venueName:values.get('venueName'),venueAddress:values.get('venueAddress'),startsAt:new Date(String(values.get('startsAt'))).toISOString(),endsAt:new Date(String(values.get('endsAt'))).toISOString(),capacity:Number(values.get('capacity')),visibility:values.get('visibility'),registrationMode:values.get('registrationMode'),formId:values.get('formId')||undefined,faqs};await run(async()=>{const updated=await request(`organizations/${organization.id}/events/${event.id}`,{method:'PATCH',body:JSON.stringify(payload)});setEvent(value=>({...value,...updated}))},'Etkinlik bilgileri ve SSS güncellendi.')}
  async function publishForm(e:FormEvent<HTMLFormElement>){e.preventDefault();const values=new FormData(e.currentTarget),formId=String(values.get('formId')),fields=String(values.get('fields')).split('\n').map(line=>line.split('|').map(v=>v.trim())).filter(parts=>parts[0]&&parts[1]).map(([label,type='text',required='hayır'],index)=>({key:`field_${index+1}`,label,type,required:required.toLocaleLowerCase('tr').startsWith('e')}));await run(()=>request(`organizations/${organization.id}/forms/${formId}/versions`,{method:'POST',body:JSON.stringify({schema:{fields}})}),'Kayıt formunun yeni sürümü yayınlandı.')}
  async function updateTemplate(e:FormEvent<HTMLFormElement>,id:string){e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget));await run(()=>request(`organizations/${organization.id}/email-templates/${id}`,{method:'PATCH',body:JSON.stringify(values)}),'E-posta şablonu güncellendi.')}
  async function cancelReminder(id:string){await run(async()=>{await request(`organizations/${organization.id}/events/${event.id}/reminders/${id}`,{method:'DELETE'});setReminders(rows=>rows.map(row=>row.id===id?{...row,status:'CANCELLED'}:row))},'Hatırlatma iptal edildi.')}
  return <>
    <nav className="workspace-tabs" aria-label="Etkinlik yönetimi bölümleri">
      <button className={tab==='overview'?'active':''} onClick={()=>setTab('overview')}>Genel bakış</button>
      <button className={tab==='settings'?'active':''} onClick={()=>setTab('settings')}>Bilgiler ve SSS</button>
      <button className={tab==='applications'?'active':''} onClick={()=>setTab('applications')}>Başvurular ({initialRegistrations.length})</button>
      <button className={tab==='forms'?'active':''} onClick={()=>setTab('forms')}>Form ve onam</button>
      <button className={tab==='communication'?'active':''} onClick={()=>setTab('communication')}>Davet ve iletişim</button>
    </nav>
    {notice&&<p className="notice" role="status">{notice}</p>}
    {tab==='overview'&&<section className="workspace-grid">
      <article className="workspace-card"><p className="eyebrow">DURUM</p><h2>Yayın ve kayıt</h2><div className="status-row"><span className="pill">{event.publicationStatus}</span><span className="pill">{event.registrationStatus}</span><span className="pill">{event.phase}</span></div><p>{new Intl.DateTimeFormat('tr-TR',{dateStyle:'long',timeStyle:'short'}).format(new Date(event.startsAt))}</p><div className="action-links"><button disabled={busy} onClick={()=>state('PUBLISHED','OPEN')}>Yayınla ve kaydı aç</button><button disabled={busy} onClick={()=>state('PUBLISHED','CLOSED')}>Kaydı kapat</button><button disabled={busy} onClick={()=>state('UNPUBLISHED','CLOSED')}>Yayından kaldır</button></div></article>
      <article className="workspace-card"><p className="eyebrow">PAYLAŞIM</p><h2>Etkinlik sayfası</h2><p>Katılımcılar bu bağlantıdan etkinlik bilgilerini görür ve kayıt olur.</p><input readOnly value={publicUrl}/><div className="action-links"><a className="primary link-button" href={publicUrl} target="_blank">Sayfayı aç</a><button onClick={()=>navigator.clipboard.writeText(`${window.location.origin}${publicUrl}`)}>Bağlantıyı kopyala</button></div></article>
      <article className="workspace-card"><p className="eyebrow">ÖZET</p><h2>Katılım görünümü</h2><div className="metric-grid"><div><span>Başvuru</span><b>{initialRegistrations.length}</b></div><div><span>Kabul</span><b>{accepted}</b></div><div><span>Kontenjan</span><b>{event.capacity}</b></div></div></article>
      <article className="workspace-card"><p className="eyebrow">KURALLAR</p><h2>Etkinlik ayarları</h2><dl><dt>Görünürlük</dt><dd>{event.visibility}</dd><dt>Kayıt modeli</dt><dd>{event.registrationMode}</dd><dt>Kayıt formu</dt><dd>{typedForms[0]?.name??'Standart form'}</dd></dl></article>
    </section>}
    {tab==='settings'&&<form className="workspace-card event-settings" onSubmit={saveSettings}><h2>Etkinlik bilgileri</h2><label>Etkinlik adı<input name="title" required defaultValue={event.title}/></label><label>Kısa açıklama<textarea name="summary" defaultValue={event.summary}/></label><label>Ayrıntılı açıklama<textarea name="description" defaultValue={event.description}/></label><div className="two"><label>Başlangıç<input name="startsAt" type="datetime-local" required defaultValue={event.startsAt.slice(0,16)}/></label><label>Bitiş<input name="endsAt" type="datetime-local" required defaultValue={event.endsAt.slice(0,16)}/></label></div><div className="two"><label>Mekân<input name="venueName" defaultValue={event.venueName}/></label><label>Adres<input name="venueAddress" defaultValue={event.venueAddress}/></label></div><div className="two"><label>Kontenjan<input name="capacity" type="number" min="1" required defaultValue={event.capacity}/></label><label>Kayıt formu<select name="formId" defaultValue={event.formId}><option value="">Standart form</option>{typedForms.map(form=><option value={form.id} key={form.id}>{form.name}</option>)}</select></label></div><div className="two"><label>Görünürlük<select name="visibility" defaultValue={event.visibility}><option value="PUBLIC">Herkese açık</option><option value="LINK_ONLY">Bağlantıya sahip olanlar</option><option value="INVITE_ONLY">Yalnız davetliler</option></select></label><label>Kayıt modeli<select name="registrationMode" defaultValue={event.registrationMode}><option value="DIRECT">Doğrudan</option><option value="APPROVAL">Onaylı</option><option value="WAITLIST">Yedek liste</option></select></label></div><label>SSS — her satıra “Soru | Yanıt”<textarea name="faqs" rows={7} defaultValue={(event.faqs??[]).map(f=>`${f.question} | ${f.answer}`).join('\n')} placeholder={'Kimler katılabilir? | Etkinlik herkese açıktır.\nKatılım ücretsiz mi? | Evet, ücretsizdir.'}/></label><button className="primary" disabled={busy}>Bilgileri kaydet</button></form>}
    {tab==='applications'&&<Applications organizationId={organization.id} initial={initialRegistrations as Registration[]}/>} 
    {tab==='forms'&&<section className="workspace-grid"><article className="workspace-card"><h2>Kayıt formları</h2>{typedForms.length?typedForms.map(form=><div className="list-row" key={form.id}><div><b>{form.name}</b><small>Sürüm {form.versions[0]?.version??1} · {form.versions[0]?.schema?.fields?.length??0} alan</small></div></div>):<p>Henüz form bulunmuyor.</p>}</article><form className="workspace-card" onSubmit={publishForm}><h2>Formun yeni sürümünü yayınla</h2><label>Form<select name="formId" required>{typedForms.map(form=><option key={form.id} value={form.id}>{form.name}</option>)}</select></label><label>Alanlar — her satıra “Başlık | tür | evet/hayır”<textarea name="fields" rows={8} required placeholder={'Ad Soyad | text | evet\nTelefon | phone | hayır\nKatılım nedeni | textarea | evet'}/></label><small>Türler: text, textarea, email, phone, number, select, checkbox.</small><button className="primary" disabled={busy||!typedForms.length}>Yeni sürümü yayınla</button></form><form className="workspace-card" onSubmit={addConsent}><h2>Zorunlu onam ekle</h2><label>Başlık<input name="title" required placeholder="KVKK ve fotoğraf izni"/></label><label>Onam metni<textarea name="text" required minLength={20}/></label><button className="primary" disabled={busy}>Onamı ekle</button></form><article className="workspace-card"><h2>Etkinlik onamları</h2>{typedConsents.length?typedConsents.map(item=><div className="list-row" key={item.definition.id}><div><b>{item.definition.title}</b><small>Sürüm {item.definition.versions[0]?.version} · {item.required?'Zorunlu':'İsteğe bağlı'}</small></div></div>):<p>Bu etkinlikte onam bulunmuyor.</p>}</article></section>}
    {tab==='communication'&&<section className="workspace-grid"><form className="workspace-card" onSubmit={invite}><h2>Katılımcı davet et</h2><label>E-posta<input name="email" type="email" required/></label><button className="primary" disabled={busy}>Davet oluştur</button><small>Davetli etkinliklerde yalnızca davet edilen hesaplar kayıt olabilir.</small></form><form className="workspace-card" onSubmit={reminder}><h2>Hatırlatma planla</h2><label>Şablon<select name="templateId" required>{typedTemplates.map(t=><option value={t.id} key={t.id}>{t.key} — {t.subject}</option>)}</select></label><label>Gönderim zamanı<input name="sendAt" type="datetime-local" required/></label><button className="primary" disabled={busy||!typedTemplates.length}>Hatırlatmayı planla</button><small>Bir etkinlik için en fazla iki hatırlatma planlanabilir.</small></form><article className="workspace-card wide"><h2>Planlanmış hatırlatmalar</h2>{reminders.length?reminders.map(item=><div className="list-row" key={item.id}><div><b>{item.template?.subject||item.template?.key}</b><small>{new Intl.DateTimeFormat('tr-TR',{dateStyle:'long',timeStyle:'short'}).format(new Date(item.sendAt))} · {item.status}</small></div>{item.status==='SCHEDULED'&&<button onClick={()=>cancelReminder(item.id)}>İptal et</button>}</div>):<p>Henüz planlanmış hatırlatma yok.</p>}</article><article className="workspace-card wide"><h2>E-posta şablonları</h2><p>Konu ve içerikte değişkenleri koruyarak kurumunuza göre düzenleyebilirsiniz.</p><div className="template-editor">{typedTemplates.map(t=><form key={t.id} className="template-form" onSubmit={e=>updateTemplate(e,t.id)}><b>{t.key}</b><label>Konu<input name="subject" defaultValue={t.subject} required/></label><label>İçerik<textarea name="body" defaultValue={t.body} required rows={5}/></label><button disabled={busy}>Şablonu kaydet</button></form>)}</div></article></section>}
  </>;
}
