import { Body, Controller, Get, Inject, Param, Post, Res } from '@nestjs/common'; import { IsEmail, IsString } from 'class-validator'; import type { Response } from 'express'; import { AuthenticatedUser, CurrentUser } from '../identity/policies/current-user.decorator'; import { Public } from '../identity/policies/public.decorator'; import { OrganizationAccessService } from '../organizations/policies/organization-access.service'; import { CheckInService } from './check-in.service'; import { simplePdf } from './pdf';
class EmailDto{@IsEmail()email!:string}class MagicDto{@IsString()token!:string}class DoorDto{@IsEmail()email!:string;@IsString()firstName!:string;@IsString()lastName!:string}class RegistrationDto{@IsString()registrationId!:string}
@Controller() export class CheckInController {
  constructor(@Inject(CheckInService)private c:CheckInService,@Inject(OrganizationAccessService)private access:OrganizationAccessService){}
  @Post('organizations/:organizationId/events/:eventId/check-in/activate') async activate(@CurrentUser()u:AuthenticatedUser,@Param('organizationId')o:string,@Param('eventId')e:string){await this.access.requireEventAccess(u.id,o,e,['ORGANIZATION_ADMIN','EVENT_MANAGER']);return this.c.activate(u.id,o,e)}
  @Public() @Get('check-in/:eventToken') info(@Param('eventToken')t:string){return this.c.publicInfo(t)}
  @Public() @Post('check-in/:eventToken/request-link') request(@Param('eventToken')t:string,@Body()d:EmailDto){return this.c.requestMagicLink(t,d.email)}
  @Public() @Post('check-in/:eventToken/confirm-magic') magic(@Param('eventToken')t:string,@Body()d:MagicDto){return this.c.confirmMagic(t,d.token)}
  @Post('check-in/:eventToken/confirm-account') account(@Param('eventToken')t:string,@CurrentUser()u:AuthenticatedUser){return this.c.confirmAccount(t,u.id)}
  @Post('organizations/:organizationId/events/:eventId/check-in/door') async door(@CurrentUser()u:AuthenticatedUser,@Param('organizationId')o:string,@Param('eventId')e:string,@Body()d:DoorDto){await this.access.requireEventAccess(u.id,o,e,['ORGANIZATION_ADMIN','EVENT_MANAGER','FIELD_STAFF']);return this.c.doorRegister(u.id,o,e,d)}
  @Post('organizations/:organizationId/events/:eventId/check-in/manual') async manual(@CurrentUser()u:AuthenticatedUser,@Param('organizationId')o:string,@Param('eventId')e:string,@Body()d:RegistrationDto){await this.access.requireEventAccess(u.id,o,e,['ORGANIZATION_ADMIN','EVENT_MANAGER','FIELD_STAFF']);return this.c.manual(u.id,o,e,d.registrationId)}
  @Get('organizations/:organizationId/events/:eventId/check-in/stats') async stats(@CurrentUser()u:AuthenticatedUser,@Param('organizationId')o:string,@Param('eventId')e:string){await this.access.requireEventAccess(u.id,o,e,['ORGANIZATION_ADMIN','EVENT_MANAGER','FIELD_STAFF']);return this.c.stats(u.id,o,e)}
  @Get('organizations/:organizationId/events/:eventId/check-in/signature.pdf') async signature(@CurrentUser()u:AuthenticatedUser,@Param('organizationId')o:string,@Param('eventId')e:string,@Res()res:Response){await this.access.requireEventAccess(u.id,o,e,['ORGANIZATION_ADMIN','EVENT_MANAGER','FIELD_STAFF']);const rows=await this.c.signatureRows(u.id,o,e),pdf=simplePdf('Etkinlik katilim imza formu',rows.map((r,i)=>`${i+1}. ${r.firstName} ${r.lastName} | ${r.email} | Imza: __________________`));res.setHeader('content-type','application/pdf');res.setHeader('content-disposition','attachment; filename="attendance-signatures.pdf"');res.send(pdf)}
}
