import{BadRequestException,Inject,Injectable,NotFoundException}from'@nestjs/common';import{CheckInMethod}from'@prisma/client';import{createHash,randomBytes,randomUUID}from'node:crypto';import{PrismaService}from'../../shared/persistence/prisma.service';import{OrganizationAccessService}from'../organizations/policies/organization-access.service';import{FeaturesService}from'../features/features.service';import{RegistrationsService}from'../registrations/registrations.service';import{CommunicationsService}from'../communications/communications.service';import{AuditService}from'../audit/audit.service';
@Injectable()export class CheckInService{constructor(@Inject(PrismaService)private prisma:PrismaService,@Inject(OrganizationAccessService)private access:OrganizationAccessService,@Inject(FeaturesService)private features:FeaturesService,@Inject(RegistrationsService)private registrations:RegistrationsService,@Inject(CommunicationsService)private communications:CommunicationsService,@Inject(AuditService)private audit:AuditService){}
 async activate(userId:string,organizationId:string,eventId:string){await this.access.requireMembership(userId,organizationId,['ORGANIZATION_ADMIN','EVENT_MANAGER']);const event=await this.prisma.event.findFirst({where:{id:eventId,organizationId}});if(!event)throw new NotFoundException('Etkinlik bulunamadı.');const access=await this.prisma.eventCheckInAccess.upsert({where:{eventId},create:{eventId,publicToken:randomUUID(),enabled:true},update:{enabled:true}});await this.prisma.eventFeatureSetting.upsert({where:{eventId_featureKey:{eventId,featureKey:'check_in'}},create:{eventId,featureKey:'check_in',enabled:true,config:{}},update:{enabled:true}});return{eventToken:access.publicToken,checkInUrl:`/check-in/${access.publicToken}`}}
 async publicInfo(token:string){const access=await this.prisma.eventCheckInAccess.findUnique({where:{publicToken:token},include:{event:{select:{id:true,title:true,venueName:true,phase:true}}}});if(!access?.enabled)throw new NotFoundException('Katılım bağlantısı bulunamadı.');return access.event}
 async requestMagicLink(token:string,emailInput:string){const access=await this.prisma.eventCheckInAccess.findUnique({where:{publicToken:token},include:{event:true}});if(!access?.enabled)throw new NotFoundException('Katılım bağlantısı bulunamadı.');await this.features.assertEnabled(access.eventId,'check_in');const email=emailInput.trim().toLowerCase(),registration=await this.prisma.eventRegistration.findUnique({where:{eventId_email:{eventId:access.eventId,email}}});if(registration?.applicationStatus==='ACCEPTED'){const raw=randomBytes(32).toString('base64url'),hash=this.hash(raw),expiresAt=new Date(Date.now()+15*60_000);await this.prisma.guestAccessToken.create({data:{eventId:access.eventId,registrationId:registration.id,tokenHash:hash,expiresAt}});await this.communications.queueSystemMessage(email,`${access.event.title} katılım bağlantısı`,`Tek kullanımlık bağlantınız: /check-in/${token}?magic=${raw}`,`magic-link:${hash}`)}return{sent:true}}
 async confirmMagic(token:string,raw:string){const access=await this.prisma.eventCheckInAccess.findUnique({where:{publicToken:token}});if(!access?.enabled)throw new NotFoundException('Katılım bağlantısı bulunamadı.');const guest=await this.prisma.guestAccessToken.findUnique({where:{tokenHash:this.hash(raw)}});if(!guest||guest.eventId!==access.eventId||guest.usedAt||guest.expiresAt<=new Date())throw new BadRequestException('Bağlantı geçersiz, süresi dolmuş veya kullanılmış.');const claimed=await this.prisma.guestAccessToken.updateMany({where:{id:guest.id,usedAt:null,expiresAt:{gt:new Date()}},data:{usedAt:new Date()}});if(!claimed.count)throw new BadRequestException('Bağlantı daha önce kullanılmış.');return this.confirm(access.eventId,guest.registrationId,'MAGIC_LINK')}
 async confirmAccount(token:string,userId:string){const access=await this.prisma.eventCheckInAccess.findUnique({where:{publicToken:token}});if(!access?.enabled)throw new NotFoundException('Katılım bağlantısı bulunamadı.');const user=await this.prisma.user.findUnique({where:{id:userId}}),registration=user?await this.prisma.eventRegistration.findUnique({where:{eventId_email:{eventId:access.eventId,email:user.email}}}):null;if(!registration||registration.applicationStatus!=='ACCEPTED')throw new NotFoundException('Bu hesap için kabul edilmiş kayıt bulunamadı.');if(!registration.userId)await this.prisma.eventRegistration.update({where:{id:registration.id},data:{userId}});return this.confirm(access.eventId,registration.id,'ACCOUNT')}
 async doorRegister(userId:string,organizationId:string,eventId:string,d:{email:string;firstName:string;lastName:string}){await this.access.requireMembership(userId,organizationId,['ORGANIZATION_ADMIN','EVENT_MANAGER','FIELD_STAFF']);const event=await this.prisma.event.findFirst({where:{id:eventId,organizationId}});if(!event)throw new NotFoundException('Etkinlik bulunamadı.');await this.features.assertEnabled(eventId,'door_registration');const registration=await this.registrations.doorRegister(eventId,d);return this.confirm(eventId,registration.id,'DOOR_REGISTRATION',userId)}
 async manual(userId:string,organizationId:string,eventId:string,registrationId:string){await this.access.requireMembership(userId,organizationId,['ORGANIZATION_ADMIN','EVENT_MANAGER','FIELD_STAFF']);const registration=await this.prisma.eventRegistration.findFirst({where:{id:registrationId,eventId,event:{organizationId}}});if(!registration)throw new NotFoundException('Kayıt bulunamadı.');return this.confirm(eventId,registrationId,'STAFF_MANUAL',userId)}
 async stats(userId:string,organizationId:string,eventId:string){await this.access.requireMembership(userId,organizationId,['ORGANIZATION_ADMIN','EVENT_MANAGER','FIELD_STAFF']);const [registered,checkedIn]=await Promise.all([this.prisma.eventRegistration.count({where:{eventId,event:{organizationId},applicationStatus:'ACCEPTED'}}),this.prisma.attendanceRecord.count({where:{eventId,event:{organizationId},status:{in:['CHECKED_IN','MANUALLY_CONFIRMED']}}})]);return{registered,checkedIn,remaining:Math.max(0,registered-checkedIn)}}
 async signatureRows(userId:string,organizationId:string,eventId:string){await this.access.requireMembership(userId,organizationId,['ORGANIZATION_ADMIN','EVENT_MANAGER','FIELD_STAFF']);return this.prisma.eventRegistration.findMany({where:{eventId,event:{organizationId},applicationStatus:'ACCEPTED'},select:{firstName:true,lastName:true,email:true,attendance:{select:{status:true,confirmedAt:true}}},orderBy:[{lastName:'asc'},{firstName:'asc'}]})}
 private async confirm(eventId:string,registrationId:string,method:CheckInMethod,actorId?:string){const now=new Date(),status=method==='STAFF_MANUAL'?'MANUALLY_CONFIRMED':'CHECKED_IN';const record=await this.prisma.attendanceRecord.upsert({where:{registrationId},create:{eventId,registrationId,status,method,confirmedAt:now,confirmedById:actorId},update:{}});await this.prisma.checkInAttempt.create({data:{eventId,registrationId,method,successful:true}});await this.audit.record({actorId,action:'attendance.confirmed',resourceType:'attendance',resourceId:record.id,metadata:{eventId,method}});return record}
 private hash(token:string){return createHash('sha256').update(token).digest('hex')}
}
