import { BadRequestException, Inject, Injectable } from '@nestjs/common';
import { PrismaService } from '../../shared/persistence/prisma.service';
import { OrganizationAccessService } from '../organizations/policies/organization-access.service';
import { resolveTierLimits, TierLimitOverrides, TierLimits } from './domain/tier-limits';

@Injectable()
export class TiersService {
  constructor(@Inject(PrismaService) private readonly prisma: PrismaService, @Inject(OrganizationAccessService) private readonly access: OrganizationAccessService) {}
  async limitsFor(userId:string,organizationId:string):Promise<TierLimits>{await this.access.requireMembership(userId,organizationId);const organization=await this.withTier(organizationId);return this.resolve(organization)}
  async reserveStorage(organizationId:string,key:'photo_storage'|'file_storage',bytes:number){const organization=await this.withTier(organizationId),limits=this.resolve(organization),assetUse=key==='photo_storage'?{OR:[{photos:{some:{}}},{logoFor:{isNot:null}},{coverForEvents:{some:{}}}]}:{resources:{some:{}}},[used,reserved]=await Promise.all([this.prisma.mediaAsset.aggregate({_sum:{sizeBytes:true},where:{organizationId,status:{in:['PENDING','ACTIVE']},...assetUse}}),this.prisma.quotaReservation.aggregate({_sum:{bytes:true},where:{organizationId,key,consumedAt:null,expiresAt:{gt:new Date()}}})]),limit=key==='photo_storage'?limits.photoStorageLimitBytes:limits.fileStorageLimitBytes;if((used._sum.sizeBytes??0n)+(reserved._sum.bytes??0n)+BigInt(bytes)>limit)throw new BadRequestException('Depolama kotası yetersiz.');return this.prisma.quotaReservation.create({data:{organizationId,key,bytes,expiresAt:new Date(Date.now()+15*60_000)}})}
  async photoLimits(organizationId:string){const limits=this.resolve(await this.withTier(organizationId));return{maxPhotosPerEvent:limits.maxPhotosPerEvent,maxPhotosPerParticipant:limits.defaultMaxPhotosPerParticipant}}
  private withTier(organizationId:string){return this.prisma.organization.findUniqueOrThrow({where:{id:organizationId},include:{tier:true,tierOverride:true}})}
  private resolve(organization:Awaited<ReturnType<TiersService['withTier']>>):TierLimits{const tier:TierLimits={maxActiveEvents:organization.tier.maxActiveEvents,maxParticipantsPerEvent:organization.tier.maxParticipantsPerEvent,photoStorageLimitBytes:organization.tier.photoStorageLimitBytes,fileStorageLimitBytes:organization.tier.fileStorageLimitBytes,maxPhotosPerEvent:organization.tier.maxPhotosPerEvent,defaultMaxPhotosPerParticipant:organization.tier.defaultMaxPhotosPerParticipant,emailMultiplier:organization.tier.emailMultiplier,allowedFileTypes:organization.tier.allowedFileTypes,featureFlags:organization.tier.featureFlags as Record<string,boolean>};const override=organization.tierOverride&&(!organization.tierOverride.expiresAt||organization.tierOverride.expiresAt>new Date())?organization.tierOverride.limits as TierLimitOverrides:null;return resolveTierLimits(tier,override)}
}
