import{BadRequestException,ForbiddenException,Inject,Injectable,NotFoundException,OnModuleInit}from'@nestjs/common';import{createHash,randomBytes}from'node:crypto';import{JobQueue}from'../../infrastructure/jobs/job-queue.port';import{JobRunnerService}from'../../infrastructure/jobs/job-runner.service';import{PrismaService}from'../../shared/persistence/prisma.service';import{AuditService}from'../audit/audit.service';import{OrganizationAccessService}from'../organizations/policies/organization-access.service';
@Injectable()export class AdministrationService implements OnModuleInit{constructor(@Inject(PrismaService)private prisma:PrismaService,@Inject(AuditService)private audit:AuditService,@Inject(OrganizationAccessService)private access:OrganizationAccessService,@Inject(JobQueue)private jobs:JobQueue,@Inject(JobRunnerService)private runner:JobRunnerService){}onModuleInit(){this.runner.register('deletion.purge',p=>this.purge(String(p.kind),String(p.id)))}
  overview(){return Promise.all([this.prisma.organization.count(),this.prisma.user.count(),this.prisma.event.count(),this.prisma.backgroundJob.count({where:{status:'FAILED'}})]).then(([organizations,users,events,failedJobs])=>({organizations,users,events,failedJobs}))}
  organizations(){return this.prisma.organization.findMany({include:{tier:true,_count:{select:{events:true,memberships:true}}},orderBy:{createdAt:'desc'}})}
  tiers(){return this.prisma.tier.findMany({orderBy:{maxActiveEvents:'asc'}})}
  async assignTier(adminId:string,organizationId:string,tierId:string){if(!await this.prisma.tier.findUnique({where:{id:tierId}}))throw new NotFoundException('Tier bulunamadı.');const result=await this.prisma.organization.update({where:{id:organizationId},data:{tierId},include:{tier:true}});await this.audit.record({actorId:adminId,organizationId,action:'admin.tier_assigned',resourceType:'organization',resourceId:organizationId,metadata:{tierId}});return result}
  async requestPromotion(userId:string,organizationId:string,tierId:string,reason:string){await this.access.requireMembership(userId,organizationId,['ORGANIZATION_ADMIN']);return this.prisma.promotionRequest.create({data:{organizationId,requestedTierId:tierId,reason}})}
  promotions(){return this.prisma.promotionRequest.findMany({where:{status:'PENDING'},include:{organization:true,requestedTier:true},orderBy:{createdAt:'asc'}})}
  async reviewPromotion(adminId:string,id:string,approved:boolean){const request=await this.prisma.promotionRequest.findUnique({where:{id}});if(!request||request.status!=='PENDING')throw new NotFoundException('Bekleyen talep bulunamadı.');return this.prisma.$transaction(async tx=>{if(approved)await tx.organization.update({where:{id:request.organizationId},data:{tierId:request.requestedTierId}});const result=await tx.promotionRequest.update({where:{id},data:{status:approved?'APPROVED':'REJECTED',reviewedById:adminId,reviewedAt:new Date()}});await tx.auditLog.create({data:{actorId:adminId,organizationId:request.organizationId,action:'admin.promotion_reviewed',resourceType:'promotion_request',resourceId:id,metadata:{approved}}});return result})}
  audits(organizationId?:string){return this.prisma.auditLog.findMany({where:{organizationId},include:{actor:{select:{email:true}}},orderBy:{createdAt:'desc'},take:200})}
  async quota(userId:string,organizationId:string){await this.access.requireMembership(userId,organizationId);const organization=await this.prisma.organization.findUniqueOrThrow({where:{id:organizationId},include:{tier:true}}),[photos,files]=await Promise.all([this.prisma.mediaAsset.aggregate({_sum:{sizeBytes:true},where:{organizationId,photos:{some:{}},status:'ACTIVE'}}),this.prisma.mediaAsset.aggregate({_sum:{sizeBytes:true},where:{organizationId,resources:{some:{}},status:'ACTIVE'}})]);return{photoBytes:photos._sum.sizeBytes??0n,photoLimitBytes:organization.tier.photoStorageLimitBytes,fileBytes:files._sum.sizeBytes??0n,fileLimitBytes:organization.tier.fileStorageLimitBytes}}
  async grantSupport(adminId:string,organizationId:string,reason:string,minutes:number){if(minutes<1||minutes>120)throw new BadRequestException('Destek erişimi 1–120 dakika olabilir.');const token=randomBytes(32).toString('base64url'),tokenHash=this.hash(token),grant=await this.prisma.supportAccessGrant.create({data:{adminId,organizationId,reason,tokenHash,expiresAt:new Date(Date.now()+minutes*60_000)}});await this.audit.record({actorId:adminId,organizationId,action:'support.access_granted',resourceType:'support_grant',resourceId:grant.id,metadata:{minutes,reason}});return{token,expiresAt:grant.expiresAt}}
  async redeemSupport(token:string){const tokenHash=this.hash(token),grant=await this.prisma.supportAccessGrant.findUnique({where:{tokenHash},include:{organization:{include:{tier:true,_count:{select:{events:true,memberships:true}}}}}});if(!grant||grant.revokedAt||grant.expiresAt<=new Date())throw new ForbiddenException('Destek erişimi geçersiz veya süresi dolmuş.');await this.prisma.$transaction([this.prisma.supportAccessGrant.update({where:{id:grant.id},data:{lastUsedAt:new Date()}}),this.prisma.auditLog.create({data:{actorId:grant.adminId,organizationId:grant.organizationId,action:'support.access_used',resourceType:'support_grant',resourceId:grant.id,metadata:{readOnly:true}}})]);return{readOnly:true,organization:grant.organization,reason:grant.reason,expiresAt:grant.expiresAt}}
  async scheduleDeletion(userId:string,kind:'account'|'organization',id:string){if(kind==='account'&&userId!==id)throw new ForbiddenException();if(kind==='organization')await this.access.requireMembership(userId,id,['ORGANIZATION_ADMIN']);const at=new Date(Date.now()+30*24*60*60_000);if(kind==='account')await this.prisma.user.update({where:{id},data:{status:'DELETED_PENDING',deletedAt:new Date(),deletionScheduledFor:at}});else await this.prisma.organization.update({where:{id},data:{status:'DELETED_PENDING',deletedAt:new Date(),deletionScheduledFor:at}});await this.jobs.enqueue({type:'deletion.purge',payload:{kind,id},runAt:at,idempotencyKey:`deletion:${kind}:${id}`});await this.audit.record({actorId:userId,organizationId:kind==='organization'?id:undefined,action:'deletion.scheduled',resourceType:kind,resourceId:id,metadata:{purgeAt:at.toISOString()}});return{recoverableUntil:at}}
  async recover(userId:string,kind:'account'|'organization',id:string){if(kind==='account'&&userId!==id)throw new ForbiddenException();if(kind==='organization')await this.access.requireMembership(userId,id,['ORGANIZATION_ADMIN']);if(kind==='account')await this.prisma.user.update({where:{id},data:{status:'ACTIVE',deletedAt:null,deletionScheduledFor:null}});else await this.prisma.organization.update({where:{id},data:{status:'ACTIVE',deletedAt:null,deletionScheduledFor:null}});await this.prisma.backgroundJob.updateMany({where:{idempotencyKey:`deletion:${kind}:${id}`,status:'PENDING'},data:{status:'COMPLETED',completedAt:new Date()}});return{recovered:true}}
  private async purge(kind:string,id:string){if(kind==='account'){const row=await this.prisma.user.findUnique({where:{id}});if(row?.status==='DELETED_PENDING'&&row.deletionScheduledFor&&row.deletionScheduledFor<=new Date())await this.prisma.user.delete({where:{id}})}else if(kind==='organization'){const row=await this.prisma.organization.findUnique({where:{id}});if(row?.status==='DELETED_PENDING'&&row.deletionScheduledFor&&row.deletionScheduledFor<=new Date())await this.prisma.organization.delete({where:{id}})}}private hash(value:string){return createHash('sha256').update(value).digest('hex')}}
