import { Inject, Injectable, NotFoundException } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { PrismaService } from '../../shared/persistence/prisma.service';
import { OrganizationAccessService } from '../organizations/policies/organization-access.service';
import { AuditService } from '../audit/audit.service';
import { FeaturesService } from '../features/features.service';
@Injectable()
export class FeedbackService {
  constructor(@Inject(PrismaService) private prisma: PrismaService, @Inject(OrganizationAccessService) private access: OrganizationAccessService, @Inject(AuditService) private audit: AuditService, @Inject(FeaturesService) private features: FeaturesService) {}
  async list(userId: string, organizationId: string, eventId: string) { await this.access.requireEventAccess(userId, organizationId, eventId); return this.prisma.feedbackForm.findMany({ where: { eventId }, include: { _count: { select: { submissions: true } } }, orderBy: { createdAt: 'desc' } }); }
  async create(userId: string, organizationId: string, eventId: string, title: string, schema: object) { await this.access.requireEventAccess(userId, organizationId, eventId, ['ORGANIZATION_ADMIN', 'EVENT_MANAGER']); return this.prisma.feedbackForm.create({ data: { eventId, title, schema: schema as Prisma.InputJsonValue } }); }
  async open(userId: string, organizationId: string, id: string, open: boolean) { const form = await this.prisma.feedbackForm.findUnique({ where: { id }, include: { event: true } }); if (!form || form.event.organizationId !== organizationId) throw new NotFoundException('Geri bildirim formu bulunamadı.'); await this.access.requireEventAccess(userId, organizationId, form.eventId, ['ORGANIZATION_ADMIN', 'EVENT_MANAGER']); const updated = await this.prisma.feedbackForm.update({ where: { id }, data: { open } }); await this.audit.record({ actorId: userId, organizationId, action: open ? 'feedback.opened' : 'feedback.closed', resourceType: 'feedback_form', resourceId: id }); return updated; }
  async submit(userId: string, id: string, answers: object, anonymous: boolean) { const form = await this.prisma.feedbackForm.findUnique({ where: { id } }); if (!form?.open) throw new NotFoundException('Geri bildirim formu açık değil.'); const user = await this.prisma.user.findUnique({ where: { id: userId } }), registration = user ? await this.prisma.eventRegistration.findUnique({ where: { eventId_email: { eventId: form.eventId, email: user.email } } }) : null; if (!registration || registration.applicationStatus !== 'ACCEPTED') throw new NotFoundException('Katılımcı kaydı bulunamadı.'); return this.prisma.feedbackSubmission.create({ data: { formId: id, registrationId: registration.id, answers: answers as Prisma.InputJsonValue, anonymous } }); }
  async results(userId: string, organizationId: string, id: string) { const form = await this.prisma.feedbackForm.findUnique({ where: { id }, include: { event: true, submissions: { select: { answers: true, anonymous: true, submittedAt: true, registration: { select: { firstName: true, lastName: true } } } } } }); if (!form || form.event.organizationId !== organizationId) throw new NotFoundException('Form bulunamadı.'); await this.access.requireEventAccess(userId, organizationId, form.eventId, ['ORGANIZATION_ADMIN', 'EVENT_MANAGER']); return { ...form, submissions: form.submissions.map(submission => submission.anonymous ? { ...submission, registration: null } : submission) }; }
}
