'use client';
import { FormEvent, useState } from 'react';
type Consent = { required: boolean; definition: { title: string; versions: Array<{ id: string; text: string }> } };
export type RegistrationField = { key: string; type: 'text'|'textarea'|'email'|'phone'|'number'|'select'|'checkbox'; label: string; required: boolean; options: string[] };
export function RegistrationForm({ orgSlug, eventSlug, open, consents, fields }: { orgSlug: string; eventSlug: string; open: boolean; consents: Consent[]; fields: RegistrationField[] }) {
  const [message, setMessage] = useState(''), [busy, setBusy] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const form = event.currentTarget, data = new FormData(form), consentVersionIds = consents.filter(item => data.get(`consent-${item.definition.versions[0]?.id}`)).map(item => item.definition.versions[0].id), answers = Object.fromEntries(fields.map(field => [field.key, field.type === 'checkbox' ? data.get(field.key) === 'on' : data.get(field.key)])); const response = await fetch(`/api/public/events/${orgSlug}/${eventSlug}/registrations`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ firstName: data.get('firstName'), lastName: data.get('lastName'), email: data.get('email'), answers, consentVersionIds, createAccount: data.get('createAccount') === 'on' }) }), result = await response.json(); setMessage(response.ok ? `Başvurunuz alındı. Durum: ${result.status}` : (Array.isArray(result.message) ? result.message.join(' ') : result.message ?? 'Başvuru gönderilemedi.')); setBusy(false); if (response.ok) form.reset(); }
  if (!open) return <aside className="registration-card"><h2>Kayıtlar kapalı</h2></aside>;
  return <form className="registration-card" onSubmit={submit}><p className="eyebrow">KAYIT FORMU</p><h2>Yerinizi ayırın</h2><div className="two"><label>Ad<input name="firstName" required/></label><label>Soyad<input name="lastName" required/></label></div><label>E-posta<input name="email" type="email" required/></label>{fields.map(field => <label key={field.key}>{field.label}{field.type === 'textarea' ? <textarea name={field.key} required={field.required}/> : field.type === 'select' ? <select name={field.key} required={field.required}><option value="">Seçin</option>{(field.options ?? []).map(option => <option key={option}>{option}</option>)}</select> : field.type === 'checkbox' ? <input name={field.key} type="checkbox" required={field.required}/> : <input name={field.key} type={field.type === 'phone' ? 'tel' : field.type} required={field.required}/>}</label>)}<label className="consent"><input type="checkbox" name="createAccount" defaultChecked/><span><b>Hesabımı da oluştur</b><small>Şifrenizi belirlemeniz için güvenli, tek kullanımlık bağlantı gönderilir.</small></span></label>{consents.map(item => { const version = item.definition.versions[0]; return version && <label className="consent" key={version.id}><input type="checkbox" name={`consent-${version.id}`} required={item.required}/><span><b>{item.definition.title}</b><small>{version.text}</small></span></label>; })}{message && <p className="notice" role="status">{message}</p>}<button className="primary" disabled={busy}>{busy ? 'Gönderiliyor…' : 'Başvuruyu gönder'}</button></form>;
}
