import { BadRequestException, ConflictException, Inject, Injectable, NotFoundException } from '@nestjs/common';
import { Prisma, RegistrationApplicationStatus } from '@prisma/client';
import { PrismaService } from '../../shared/persistence/prisma.service';
import { AuditService } from '../audit/audit.service';
import { OrganizationAccessService } from '../organizations/policies/organization-access.service';
import { CommunicationsService } from '../communications/communications.service';
import { ConsentsService } from '../consents/consents.service';
import { allowedRegistrationTransitions, assertRegistrationOpen, initialRegistrationStatus } from './domain/registration-rules';
type Field = { key: string; type: string; required: boolean; options: string[] };
@Injectable()
export class RegistrationsService {
  constructor(@Inject(PrismaService) private prisma: PrismaService, @Inject(OrganizationAccessService) private access: OrganizationAccessService, @Inject(AuditService) private audit: AuditService, @Inject(CommunicationsService) private communications: CommunicationsService, @Inject(ConsentsService) private consents: ConsentsService) {}
  async submit(orgSlug: string, eventSlug: string, d: { email: string; firstName: string; lastName: string; answers: object; formVersionId?: string; consentVersionIds: string[] }) {
    const event = await this.prisma.event.findFirst({ where: { slug: eventSlug, organization: { slug: orgSlug } }, include: { organization: true, form: { include: { versions: { where: { publishedAt: { not: null } }, orderBy: { version: 'desc' }, take: 1 } } } } });
    if (!event) throw new NotFoundException('Etkinlik bulunamadı.'); assertRegistrationOpen(event);
    const email = d.email.trim().toLowerCase(); if (await this.prisma.eventRegistration.findUnique({ where: { eventId_email: { eventId: event.id, email } } })) throw new ConflictException('Bu e-posta ile kayıt zaten var.');
    const version = event.form?.versions[0]; if (!version) throw new BadRequestException('Yayınlanmış başvuru formu bulunamadı.'); const fields = ((version.schema as { fields?: Field[] } | undefined)?.fields ?? []), answers = d.answers as Record<string, unknown>;
    for (const field of fields) { const value = answers[field.key]; if (field.required && (value === undefined || value === null || value === '')) throw new BadRequestException(`${field.key} alanı zorunludur.`); if (field.type === 'number' && value !== undefined && value !== '' && !Number.isFinite(Number(value))) throw new BadRequestException(`${field.key} sayısal olmalıdır.`); if (field.type === 'select' && value !== undefined && field.options && !field.options.includes(String(value))) throw new BadRequestException(`${field.key} için geçersiz seçim.`); }
    const consentIds = await this.consents.validateSelection(event.id, d.consentVersionIds ?? []), accepted = await this.prisma.eventRegistration.count({ where: { eventId: event.id, applicationStatus: 'ACCEPTED' } }), status = initialRegistrationStatus(event, accepted) as RegistrationApplicationStatus;
    const registration = await this.prisma.eventRegistration.create({ data: { eventId: event.id, email, firstName: d.firstName.trim(), lastName: d.lastName.trim(), answers: answers as Prisma.InputJsonValue, formVersionId: version.id, applicationStatus: status, statusHistory: { create: { toStatus: status } } } });
    await this.consents.record(registration.id, consentIds); await this.communications.queueRegistrationMessage({ organizationId: event.organizationId, templateKey: status === 'ACCEPTED' ? 'registration_confirmed' : status === 'WAITLISTED' ? 'waitlisted' : 'application_received', recipient: email, participantFirstName: registration.firstName, participantFullName: `${registration.firstName} ${registration.lastName}`, organizationName: event.organization.name, eventName: event.title, eventStart: event.startsAt, eventLocation: event.venueName ?? undefined, eventPublicUrl: `/events/${orgSlug}/${eventSlug}` }); return { id: registration.id, status: registration.applicationStatus };
  }
  async list(userId: string, organizationId: string, eventId: string) { await this.access.requireEventAccess(userId, organizationId, eventId, ['ORGANIZATION_ADMIN', 'EVENT_MANAGER']); return this.prisma.eventRegistration.findMany({ where: { eventId, event: { organizationId } }, orderBy: { createdAt: 'desc' } }); }
  async decide(userId: string, organizationId: string, id: string, to: RegistrationApplicationStatus, reason: string) { await this.access.requireMembership(userId, organizationId, ['ORGANIZATION_ADMIN', 'EVENT_MANAGER']); const registration = await this.prisma.eventRegistration.findFirst({ where: { id, event: { organizationId } }, include: { event: { include: { organization: true } } } }); if (!registration) throw new NotFoundException('Kayıt bulunamadı.'); if (!allowedRegistrationTransitions[registration.applicationStatus].includes(to)) throw new BadRequestException('Geçersiz kayıt durumu geçişi.'); const updated = await this.prisma.$transaction(async tx => { const value = await tx.eventRegistration.update({ where: { id }, data: { applicationStatus: to } }); await tx.registrationStatusHistory.create({ data: { registrationId: id, fromStatus: registration.applicationStatus, toStatus: to, actorId: userId, reason } }); return value; }); await this.audit.record({ actorId: userId, organizationId, action: 'registration.decided', resourceType: 'registration', resourceId: id, metadata: { to } }); const key = to === 'ACCEPTED' ? 'application_accepted' : to === 'REJECTED' ? 'application_rejected' : to === 'WAITLISTED' ? 'waitlisted' : 'application_received'; await this.communications.queueRegistrationMessage({ organizationId, templateKey: key, recipient: registration.email, participantFirstName: registration.firstName, participantFullName: `${registration.firstName} ${registration.lastName}`, organizationName: registration.event.organization.name, eventName: registration.event.title, eventStart: registration.event.startsAt, eventLocation: registration.event.venueName ?? undefined, eventPublicUrl: `/events/${registration.event.organization.slug}/${registration.event.slug}` }); return updated; }
  async doorRegister(eventId: string, d: { email: string; firstName: string; lastName: string }) { const event = await this.prisma.event.findUnique({ where: { id: eventId } }); if (!event) throw new NotFoundException('Etkinlik bulunamadı.'); const email = d.email.trim().toLowerCase(), existing = await this.prisma.eventRegistration.findUnique({ where: { eventId_email: { eventId, email } } }); if (existing) return existing; return this.prisma.eventRegistration.create({ data: { eventId, email, firstName: d.firstName.trim(), lastName: d.lastName.trim(), answers: { source: 'door_registration' }, applicationStatus: 'ACCEPTED', statusHistory: { create: { toStatus: 'ACCEPTED', reason: 'Kapıda kayıt' } } } }); }
}
