export const updates = [
  {
    version: '0.11.0',
    title: 'Daha güvenilir etkinlik akışları',
    changes: [
      ['Etkinlik oluşturma ve düzenleme adımlarındaki doğrulamalar güçlendirildi; hatalı girişlerde form bilgileri artık korunuyor.', 'Daha az veri kaybı ve daha kolay düzeltme'],
      ['Aynı anda gelen başvurularda kapasite kontrolü iyileştirildi ve tekrarlanan kayıt işlemleri engellendi.', 'Daha doğru kontenjan yönetimi'],
      ['Etkinlik günü araçları tarih veya manuel durum kısıtı olmadan her zaman kullanılabilir hâle getirildi; yinelenen katılım kayıtları önlendi.', 'Önceden prova ve daha güvenilir yoklama'],
      ['Etkinlik kopyalama özelliği kayıt formunu da yeni etkinliğe uyarlayacak şekilde geliştirildi.', 'Daha hızlı etkinlik hazırlığı'],
      ['“Yaklaşan”, “Devam ediyor” ve “Tamamlandı” bilgileri etkinlik tarihinden otomatik hesaplanıyor ve hiçbir aracı kilitlemiyor.', 'Daha sade ve anlaşılır etkinlik durumu'],
      ['Rapor, sertifika ve hatırlatma işlemlerinde tekrar eden talepler ile başarısızlık durumlarının yönetimi iyileştirildi.', 'Daha tutarlı sonuçlar ve açık işlem durumu'],
      ['Fotoğraf, kaynak ve sertifika arka planı yüklemelerine dosya, kota ve etkinlik yetkisi kontrolleri eklendi.', 'Daha güvenli içerik yönetimi'],
      ['Testler, oyunlar, geri bildirimler ve diğer etkinlik araçlarının otomatik kapanması kaldırıldı.', 'Etkinlik öncesinde prova ve sonrasında kesintisiz kullanım'],
      ['Sistem yöneticileri test kullanıcılarını, kurumları ve etkinlikleri bağlı verileriyle birlikte kalıcı olarak temizleyebilir hâle geldi.', 'Daha kolay test verisi temizliği'],
      ['Kayıt, check-in ve yönetim ekranlarında bağlantı hataları daha anlaşılır gösteriliyor; işlem başarısız olduğunda girilen bilgiler silinmiyor.', 'Daha öngörülebilir kullanıcı deneyimi'],
      ['Giriş, kayıt ve etkinlik ekranlarındaki mobil taşma sorunları giderildi.', 'Telefonlarda daha rahat kullanım'],
    ],
  },
  {
    version: '0.10.0',
    title: 'Etkinlik keşfi ve sadeleştirilmiş yönetim',
    changes: [
      ['Katılımcı alanına herkese açık etkinliklerin listelendiği “Yaklaşan Etkinlikler” ekranı eklendi.', 'Yeni etkinlikleri daha kolay keşfetme'],
      ['Etkinlik kartlarında başvuru ve kayıt durumu gösterilmeye başlandı.', 'Katılım durumunu tek bakışta görme'],
      ['Katılımcının yaklaşan, devam eden ve geçmiş etkinlikleri birbirinden ayrıldı.', 'Daha düzenli kişisel etkinlik alanı'],
      ['Takip edilen STK’ların etkinlikleri için filtre ve takip yönetimi eklendi.', 'İlgilenilen etkinliklere daha hızlı ulaşma'],
      ['Etkinlik tanıtım ve kayıt sayfası yenilendi; mobil kayıt işlemi kolaylaştırıldı.', 'Daha anlaşılır ve akıcı kayıt deneyimi'],
      ['Yeni etkinlikler varsayılan olarak herkese açık oluşturulmaya başlandı.', 'Etkinliklerin daha kolay keşfedilmesi'],
      ['Etkinlik yönetimindeki manuel “Canlıya al” adımı kaldırıldı; dönem bilgisi tarihe göre otomatik gösteriliyor.', 'Daha az işlem ve daha açık yönetim'],
      ['Etkinlik günü araçları etkinlikten önce denenebilir hâle getirildi ve otomatik kapatma kaldırıldı.', 'Daha rahat hazırlık ve prova imkânı'],
      ['Yeni etkinlik oluşturma akışındaki kullanılmayan şablon adımları temizlendi.', 'Daha kısa ve sade etkinlik oluşturma'],
    ],
  },
  {
    version: '0.9.0',
    title: 'Daha kolay erişim ve geri bildirim',
    changes: [
      ['Google hesabıyla giriş seçeneği eklendi.', 'Daha hızlı erişim'],
      ['“Sorun Bildir” özelliği eklendi; karşılaşılan sorunlar bulunulan ekrandan iletilebilir.', 'Daha kolay geri bildirim'],
      ['Beta sürümü bilgilendirmesi eklendi.', 'Daha şeffaf ürün deneyimi'],
      ['Katılımcı ana sayfası sadeleştirildi; etkinlikler ve takip edilen kurumlar ayrıldı.', 'Daha düzenli katılımcı alanı'],
      ['Kurum takip etme özelliği eklendi.', 'Etkinliklerden daha kolay haberdar olma'],
      ['Etkinlik bağlantıları ve yönlendirmeleri iyileştirildi.', 'Daha akıcı gezinme'],
    ],
  },
  {
    version: '0.8.0',
    title: 'İletişim ve sertifika geliştirmeleri',
    changes: [
      ['İletişim şablonları ve katılımcı mesajları daha anlaşılır hâle getirildi.', 'Daha tutarlı iletişim'],
      ['Gönderilen bildirimlerin ve planlanan hatırlatmaların takibi iyileştirildi.', 'Daha güvenilir planlama'],
      ['Sertifika hazırlama, görüntüleme ve yönetim ekranları geliştirildi.', 'Daha düzenli sertifika süreci'],
      ['Sertifika görünümü etkinliğe uygun biçimde özelleştirilebilir hâle getirildi.', 'Kuruma uygun görünüm'],
      ['Etkinlik açıklamalarındaki başlık, liste ve bağlantı gösterimleri iyileştirildi.', 'Daha rahat okunabilirlik'],
    ],
  },
  {
    version: '0.7.0',
    title: 'Katılımcı deneyimi ve rehber',
    changes: [
      ['Katılımcılar için başvuru, içerik ve etkinlik sonrası işlemleri bir araya getiren etkinlik sayfası eklendi.', 'Tüm işlemler bir arada'],
      ['Etkinlik içerikleri açılır-kapanır bölümler hâlinde düzenlendi.', 'Daha sade ekran kullanımı'],
      ['Etkinlik günü giriş ve katılım yönlendirmeleri iyileştirildi.', 'Daha hızlı etkinlik günü deneyimi'],
      ['Değerlendirme formlarına sayı, kısa metin ve uzun açıklama soru türleri eklendi.', 'Daha kapsamlı geri bildirim'],
      ['Kaynak ve etkinlik içeriklerinin katılımcılara sunulması iyileştirildi.', 'Bilgilere daha kolay erişim'],
      ['STK Rehberi ve sık sorulan sorular sayfası oluşturularak ana menüye eklendi.', 'Daha hızlı destek'],
    ],
  },
  {
    version: '0.6.0',
    title: 'Etkinlik içi modüller',
    changes: [
      ['Test ve değerlendirme modülleri ile hazır test şablonları eklendi.', 'Esnek ve hızlı içerik oluşturma'],
      ['Değerlendirme soru düzenleyicisi yenilendi.', 'Daha kolay düzenleme'],
      ['Ön test ve son test sonuçlarını karşılaştırma özelliği eklendi.', 'Daha anlamlı sonuçlar'],
      ['Otomatik ve manuel grup oluşturma özellikleri eklendi.', 'Esnek grup yönetimi'],
      ['Oyun ve etkinlik içi görev modülleri geliştirildi; sonuçlar kontrollü biçimde açıklanabilir hâle geldi.', 'Daha etkileşimli etkinlikler'],
      ['Geri bildirimler kategorilere ayrılabilir hâle getirildi.', 'Daha düzenli değerlendirme'],
      ['Modül işlemlerindeki açıklamalar ve hata mesajları iyileştirildi.', 'Daha anlaşılır kullanım'],
    ],
  },
  {
    version: '0.5.0',
    title: 'Etkinlik günü yönetimi',
    changes: [
      ['QR kod ile katılımcı girişi ve kapıda kayıt özellikleri eklendi.', 'Daha hızlı ve esnek giriş'],
      ['Girişler, saha işlemleri ve katılım durumunu bir araya getiren kontrol merkezi oluşturuldu.', 'Merkezi operasyon yönetimi'],
      ['Saha görevlisi atama ve görev yönetimi eklendi.', 'Daha koordineli ekip çalışması'],
      ['Katılımcı giriş ve çıkış kayıtları geliştirildi.', 'Daha doğru katılım takibi'],
      ['Giriş sırasında yaşanan kayıt ve yönlendirme sorunları giderildi.', 'Daha sorunsuz etkinlik günü'],
    ],
  },
  {
    version: '0.4.0',
    title: 'Etkinlik ve başvuru yönetimi',
    changes: [
      ['Adım adım yeni etkinlik oluşturma akışı geliştirildi.', 'Daha kolay etkinlik oluşturma'],
      ['Yüz yüze, çevrim içi ve hibrit etkinlik türleri ile çevrim içi bağlantı desteği eklendi.', 'Farklı etkinlik modelleri'],
      ['Etkinlik açıklamalarına başlık, liste, bağlantı ve vurgu desteği eklendi.', 'Daha etkili etkinlik tanıtımı'],
      ['Etkinlik bilgi ve ayarları anlaşılır bölümlere ayrıldı.', 'Daha kolay yönetim'],
      ['Etkinliğe özel SSS alanı ve görsel SSS düzenleyicisi eklendi.', 'Daha açık bilgilendirme'],
      ['Başvuru formu, görsel alan düzenleyicisi ve form sürüm yönetimi eklendi.', 'İhtiyaca uygun başvurular'],
      ['Formların yeni etkinlikle birlikte hazır oluşturulması sağlandı.', 'Daha az kurulum adımı'],
      ['Başvuruları tek ekrandan inceleme, kabul etme ve reddetme özellikleri eklendi.', 'Merkezi başvuru yönetimi'],
      ['Katılım ve iletişim onayları başvuru sürecine eklendi.', 'Daha açık başvuru süreci'],
      ['Davetli etkinlik desteği ile kayıtları açma ve kapatma kontrolleri eklendi.', 'Kontrollü katılım'],
    ],
  },
  {
    version: '0.3.0',
    title: 'Etkinlik çalışma alanı ve iletişim',
    changes: [
      ['Etkinliğin tüm aşamalarını bir araya getiren yönetim çalışma alanı oluşturuldu.', 'Bütünlüklü çalışma alanı'],
      ['Yönetim; Dashboard, Ayarlar, Modüller, İletişim, Etkinlik Günü, Etkinlik Sonrası ve Sertifikalar bölümlerine ayrıldı.', 'Daha kolay gezinme'],
      ['Etkinlik yol haritası ve “Yayına Al” özelliği eklendi.', 'Süreç boyunca yönlendirme'],
      ['Etkinlik özellikleri için hızlı açma-kapama kontrolleri ve silme işlemi eklendi.', 'Daha fazla kontrol'],
      ['E-posta şablonları, hedefli bilgilendirmeler ve hatırlatma planlama özellikleri eklendi.', 'Merkezi iletişim'],
      ['Gönderilen mesajların görüntülenmesi ve etkinlik özeti hazırlama kolaylaştırıldı.', 'Daha kolay takip'],
    ],
  },
  {
    version: '0.2.0',
    title: 'Etkinlik sonrası süreçler',
    changes: [
      ['Değerlendirme, raporlama ve katılımcı işlemleri için etkinlik sonrası yönetim alanı eklendi.', 'Düzenli kapanış süreci'],
      ['Katılımcı geri bildirim formları ile etkinlik raporu oluşturma ve paylaşma özellikleri eklendi.', 'Sonuçları değerlendirme'],
      ['Etkinlik sonrası kaynak ve içerik paylaşımı eklendi.', 'Etkinlik sonrasında bilgiye erişim'],
      ['Sertifika oluşturma, katılımcıya sunma ve kodla doğrulama özellikleri eklendi.', 'Kolay sertifika teslimi'],
      ['Katılımcıların etkinliklerini takip edebildiği kişisel alan oluşturuldu.', 'Kişisel etkinlik takibi'],
      ['Etkinlik kapatma ve sonuçlandırma akışı geliştirildi.', 'Eksiksiz etkinlik yaşam döngüsü'],
    ],
  },
  {
    version: '0.1.0',
    title: 'İlk Eventise sürümü',
    changes: [
      ['STK’lar için etkinlik yönetim panelinin ilk sürümü oluşturuldu.', 'Dijital etkinlik yönetimi'],
      ['Kurum hesabı, kullanıcı kaydı ve giriş adımları eklendi.', 'Kuruma özel çalışma alanı'],
      ['Etkinlik listeleme, oluşturma ve düzenleme akışları hazırlandı.', 'Etkinliklere tek noktadan erişim'],
      ['Katılımcı başvurularını görüntüleme ve sonuçlandırma özellikleri eklendi.', 'Düzenli başvuru takibi'],
      ['E-posta iletişim planlama ve etkinlik günü giriş işlemlerinin ilk sürümleri eklendi.', 'Merkezi operasyon'],
      ['Kurum ekibi, görevler, kullanım bilgileri ve sistem yönetimi ekranları oluşturuldu.', 'Birlikte çalışma'],
      ['Ana menü ve etkinlik yönetimi navigasyonu oluşturuldu.', 'Kolay gezinme'],
    ],
  },
] as const;
