export const updates = [
  {
    version: '0.34.0',
    title: 'Yeni etkinlik akışı canlı önizleme ve daha kapsamlı yönlendirmeyle yenilendi',
    changes: [
      ['Yeni etkinlik oluşturma alanı; temel bilgiler, zaman ve yer, başvuru ve son kontrol adımlarını daha belirgin bir ilerleme düzeninde bir araya getirecek şekilde yenilendi.', 'Nerede olduğunu bilerek daha rahat ilerleme'],
      ['Tamamlanan adımlara geri dönme ve son kontrol ekranından ilgili bilgi grubunu doğrudan düzenleme seçenekleri eklendi.', 'Bilgileri baştan başlamadan gözden geçirme'],
      ['Etkinlik adı, kısa açıklama, tarih, saat, katılım biçimi ve mekân bilgileri yazıldıkça katılımcı sayfasının canlı önizlemesinde gösterilmeye başlandı.', 'Etkinliği oluşturmadan önce katılımcı görünümünü görme'],
      ['Yüz yüze, çevrim içi ve hibrit etkinlik seçenekleri; mekân, adres ve çevrim içi katılım bağlantısı alanlarıyla birlikte oluşturma akışına eklendi.', 'Etkinlik biçimini ilk kurulumda eksiksiz tanımlama'],
      ['Hazır bir duyuru metninden etkinlik adı, özet, açıklama, tarih, mekân ve kontenjan bilgilerini taslağa aktarma alanı daha görünür ve anlaşılır hâle getirildi.', 'Mevcut içerikten daha hızlı etkinlik taslağı hazırlama'],
      ['Önümüzdeki hafta ve önümüzdeki ay için hızlı tarih seçimleri ile otomatik etkinlik bağlantısı oluşturma seçenekleri düzenlendi.', 'Tekrarlayan tarih ve bağlantı işlemlerini hızlandırma'],
      ['Onaylı başvuru ve doğrudan kayıt seçenekleri; kontenjan, görünürlük ve kişisel veri yönlendirmeleriyle aynı adımda toplandı.', 'Başvuru modelini sonuçlarını bilerek seçme'],
      ['Etkinliğin önce taslak olarak kaydedileceği açıkça anlatıldı; doğrulama ve bağlantı hatalarında girilen bilgilerin korunması sürdürüldü.', 'Yayınlama baskısı olmadan güvenle hazırlık yapma'],
    ],
  },
  {
    version: '0.33.0',
    title: 'Yönetim ekranları ve etkinlik kontrol merkezi ortak bir görsel dilde buluştu',
    changes: [
      ['Başlangıç ekranındaki sıcak, sakin ve odaklı görsel dil yönetim sayfalarına; renkler, yüzeyler, gölgeler ve tipografi üzerinden taşındı.', 'Ürün genelinde daha bütünlüklü deneyim'],
      ['Ana eylemler, ikincil düğmeler, form alanları ve klavye odak durumları daha belirgin ve tutarlı hâle getirildi.', 'İşlemleri ve aktif alanı daha kolay ayırt etme'],
      ['Ana menü, bilgi kartları, sekmeler, tablolar ve durum yüzeyleri aynı tasarım sistemine göre yenilendi.', 'Sayfalar arasında görsel alışkanlığı koruma'],
      ['Etkinlik kontrol merkezi koyu ve odaklı yeni bir üst alana kavuştu; etkinlik adı, kurum, tarih ve saat daha güçlü bir kimlik düzeninde gösterilmeye başlandı.', 'Yönetilen etkinliği tek bakışta tanıma'],
      ['Etkinlik tarihi gün ve ayı öne çıkaran ayrı bir tarih kartıyla gösterilirken hızlı işlemler yayın ve kayıt durumlarını daha anlaşılır biçimde yansıtmaya başladı.', 'Tarih ve canlı durum bilgisine daha hızlı erişim'],
      ['Genel bakış, sıradaki işler, ölçümler ve etkinlik bilgi kartları yeni kontrol merkeziyle uyumlu yüzeylere dönüştürüldü.', 'Hazırlık ve takip işlerini daha rahat okuma'],
      ['Yeni görsel düzenin dar ekran, tablet ve mobil davranışları iyileştirildi.', 'Farklı ekran boyutlarında tutarlı yönetim'],
    ],
  },
  {
    version: '0.32.0',
    title: 'Ana sayfa bugünün önceliklerini, sıradaki etkinliği ve genel tabloyu birlikte gösteriyor',
    changes: [
      ['Ana sayfa günün tarihini ve saate göre değişen kişisel karşılamayı gösterecek şekilde baştan tasarlandı.', 'Çalışma alanına daha doğal ve anlaşılır başlangıç'],
      ['Öne çıkan görev alanı; yayın bekleyen taslağa, sıradaki etkinliğe veya ilk etkinlik oluşturma adımına mevcut duruma göre otomatik yönlendiriyor.', 'O anda en önemli işe doğrudan odaklanma'],
      ['Sıradaki etkinliğin tarihi, başlama zamanı, başvuru sayısı ve göreli zamanı ayrı bir özet kartında bir araya getirildi.', 'Yaklaşan etkinliği tek bakışta takip etme'],
      ['Yaklaşan etkinlik, toplam başvuru ve yayındaki etkinlik ölçümleri daha sade bir özet şeridinde gösterilmeye başlandı.', 'Genel durumu hızlı değerlendirme'],
      ['Etkinlik listesi tarihe göre sıralandı; yayın durumu, başvuru sayısı ve “bugün”, “yarın” veya “gün sonra” bilgileri satır düzeyinde görünür hâle geldi.', 'Takvimi ve hareketliliği daha kolay okuma'],
      ['Henüz etkinliği olmayan kurumlar için ne yapılacağını anlatan yeni bir başlangıç alanı hazırlandı.', 'İlk etkinliğe daha kolay başlama'],
      ['Ana sayfanın masaüstü, tablet ve telefon yerleşimleri yeni bilgi yoğunluğuna göre ayrı ayrı düzenlendi.', 'Her ekranda önemli bilgileri kaybetmeden çalışma'],
    ],
  },
  {
    version: '0.31.0',
    title: 'Yeni İletişim sayfası ve açılır menü grupları desteğe erişimi kolaylaştırdı',
    changes: [
      ['Ana menüdeki Başlangıç, Etkinlikler, Kurum, Yönetim, Yardım ve Destek ile Eventise grupları açılıp kapatılabilir hâle getirildi.', 'Uzun menüde daha az kalabalıkla gezinme'],
      ['Bulunulan sayfanın ait olduğu menü grubu otomatik olarak açık gösterilmeye başlandı.', 'Mevcut konumu ve ilgili seçenekleri kaybetmeme'],
      ['Soru, öneri ve iş birliği mesajları için Yardım ve Destek altında ayrı bir İletişim sayfası eklendi.', 'Ekibe doğru kanaldan daha kolay ulaşma'],
      ['İletişim formuna hangi konularda kullanılabileceğini anlatan yönlendirmeler ve yanıtın hesap e-posta adresine geleceği bilgisi eklendi.', 'Mesaj göndermeden önce süreci bilme'],
      ['Teknik sorunlar için “Sorun bildir”, kullanım soruları için rehber, genel mesajlar için İletişim seçenekleri birbirinden ayrıldı.', 'İhtiyaca uygun destek yolunu daha kolay seçme'],
      ['Açılır menü grupları ile iletişim alanının daraltılmış menü ve küçük ekran görünümleri iyileştirildi.', 'Masaüstü ve telefonda tutarlı destek erişimi'],
    ],
  },
  {
    version: '0.30.0',
    title: 'Etkinlik onamı tek metin, güvenli sürümleme ve sade katılımcı kabulüyle yenilendi',
    changes: [
      ['Her etkinlik için birden fazla dağınık onam yerine katılımcının görüp kabul edeceği tek bir etkinlik onamı kullanılmaya başlandı.', 'Onam sürecini daha açık ve yönetilebilir tutma'],
      ['Onam metni aynı düzenleme alanından oluşturulabilir ve güncellenebilir hâle geldi; her değişiklik yeni sürüm olarak korunuyor.', 'Metni çoğaltmadan güncel tutma'],
      ['Eski etkinliklerde birden fazla onam bulunması durumunda en güncel kayıt korunacak şekilde veri yapısı güvenli biçimde düzenlendi.', 'Mevcut etkinliklerde tutarlı onam yapısı'],
      ['Katılımcı kayıt formunda etkinliğe ait tek onam metni açık bir kabul seçeneğiyle gösterilmeye başlandı.', 'Başvuru sırasında daha anlaşılır karar verme'],
      ['Eksik, geçersiz veya eski onam sürümleriyle kayıt tamamlanması engellendi ve hata mesajları sadeleştirildi.', 'Güncel metne dayanan daha güvenilir kayıt'],
      ['Kullanım Rehberi, tek etkinlik onamının nereden düzenleneceğini anlatacak şekilde güncellendi.', 'Yeni yapıyı doğru yerden yönetme'],
    ],
  },
  {
    version: '0.29.0',
    title: 'Giriş yolları sadeleşti, katılımcı ve STK ekranlarında SİCİ kimliği güçlendi',
    changes: [
      ['Giriş ve hesap oluşturma başlangıcında katılımcı ile STK seçenekleri daha kısa açıklamalar ve tek, belirgin eylemle yeniden düzenlendi.', 'Doğru hesap yolunu daha hızlı seçme'],
      ['Katılımcı ve STK için giriş ile hesap oluşturma ekranlarının başlıkları yapılacak işlemi doğrudan anlatacak şekilde sadeleştirildi.', 'Ekranın amacını ilk bakışta anlama'],
      ['STK daveti ve katılımcı etkinlikleri gibi bağlama özel yönlendirmeler ilgili giriş ekranlarında gösterilmeye başlandı.', 'Hesap işleminden sonra ne olacağını önceden bilme'],
      ['Giriş alanlarında ortak SİCİ logosu ve daha güçlü bir marka yüzeyi kullanılmaya başlandı; kurum adı yazımı ürün genelinde “SİCİ” olarak standartlaştırıldı.', 'Daha tutarlı ürün ve kurum kimliği'],
      ['Yeni giriş düzeni küçük ekranlarda logo, başlık ve form alanlarını koruyacak şekilde uyarlanlandı.', 'Telefonda daha rahat hesap erişimi'],
    ],
  },
  {
    version: '0.28.0',
    title: 'Etkinlik işlemleri artık daha görünür ve güvenli',
    changes: [
      ['Etkinlik sayfasını açma, katılımcılara duyuru gönderme ve silme işlemleri çalışma alanının üst bölümünde ayrı seçenekler olarak gösterilmeye başlandı.', 'Sık kullanılan işlemlere doğrudan erişim'],
      ['Etkinlik sayfası ve duyuru seçeneklerine işlemin sonucunu anlatan kısa açıklamalar eklendi.', 'Doğru işlemi daha kolay seçme'],
      ['Etkinlik silme işlemi, 30 günlük geri alma süresini açıklayan ayrı bir onay alanıyla güvenli hâle getirildi.', 'Yanlışlıkla silme riskini azaltma'],
      ['Silme onayı alanı dışarı tıklama ve Escape tuşuyla kapatılabilir hâle getirildi.', 'Daha rahat ve erişilebilir kullanım'],
    ],
  },
  {
    version: '0.27.0',
    title: 'Etkinlik vitrini görselleri daha doğru yansıtıyor',
    changes: [
      ['Kapak görselleri kırpılmadan, etkinlik sayfasının vurgu rengiyle uyumlu bir sunum alanında gösterilmeye başlandı.', 'Hazırlanan görselin bütününü koruma'],
      ['Kurum logolarının açık ve koyu tasarımlarda daha okunaklı görünmesi için logo alanlarının kontrastı iyileştirildi.', 'Daha güçlü kurum görünürlüğü'],
      ['Etkinlik sayfası renk seçenekleri anlaşılır tema adları ve daha dengeli tonlarla yenilendi.', 'Etkinliğe uygun görünümü daha kolay seçme'],
      ['Kayıt formu, bilgi kartları ve mobil kapak yerleşimi seçilen vurgu rengiyle daha tutarlı hâle getirildi.', 'Bütünlüklü ve profesyonel etkinlik sayfası'],
    ],
  },
  {
    version: '0.26.0',
    title: 'Katılımcı alanına daha sade geçiş',
    changes: [
      ['Kurum panelindeki katılımcı alanı bağlantısı menünün alt bölümünde daha sade ve belirgin bir geçiş olarak konumlandırıldı.', 'Çalışma alanları arasında daha kolay geçiş'],
      ['Daraltılmış menüde katılımcı geçişinin görünümü ve açıklamaları küçük ekranlara uyumlu hâle getirildi.', 'Her ekran boyutunda tutarlı navigasyon'],
    ],
  },
  {
    version: '0.25.0',
    title: 'Katılımcı ve STK hesapları için ayrı giriş yolları',
    changes: [
      ['Giriş ve kayıt başlangıcında katılımcı alanı ile STK ekip alanı birbirinden ayrıldı.', 'İlk adımdan itibaren doğru alana yönelme'],
      ['Katılımcılar ve kurum ekipleri için amaca uygun giriş, kayıt ve Google ile devam etme ekranları hazırlandı.', 'Daha açık ve kısa hesap işlemleri'],
      ['Kurum oluşturma, mevcut kuruma erişme ve ekip davetini tamamlama işlemleri yeni STK erişim alanında bir araya getirildi.', 'Kurum erişimini tek yerden yönetme'],
      ['Kurum yöneticileri hesap sahibi ekip üyelerini e-posta adresleriyle doğrudan çalışma alanına ekleyebilir hâle geldi.', 'Ekibi daha hızlı oluşturma'],
    ],
  },
  {
    version: '0.24.0',
    title: 'Menüde daha güçlü kurum kimliği ve kişisel alan',
    changes: [
      ['Kurum adı, çalışma alanı ve kullanıcı rolü ana menüde daha okunaklı bir kimlik alanında gösterilmeye başlandı.', 'Hangi kurum adına çalıştığını kolayca görme'],
      ['Katılımcı işlemleri kurum yönetim araçlarından ayrılarak kişisel alana taşındı.', 'Kişisel ve kurumsal işlemleri karıştırmadan ilerleme'],
      ['Menü başlıkları, açıklamaları ve aktif sayfa işaretleri daha tutarlı hâle getirildi.', 'Daha hızlı yön bulma'],
    ],
  },
  {
    version: '0.23.0',
    title: 'Etkinlik sayfaları daha güçlü bir vitrine dönüştü',
    changes: [
      ['Herkese açık etkinlik sayfası kapak görseli, kurum logosu ve etkinliğe özel vurgu rengiyle baştan tasarlandı.', 'Kuruma ait, daha etkileyici etkinlik tanıtımı'],
      ['Tarih, saat, mekân, kontenjan ve kayıt durumu sayfanın üst bölümünde hızlı okunabilir biçimde düzenlendi.', 'Temel bilgilere tek bakışta ulaşma'],
      ['Kayıt formu daha kısa açıklamalar, açık durum mesajları ve güven bilgileriyle yenilendi.', 'Daha anlaşılır ve güven veren başvuru'],
      ['Etkinlik bağlantısını paylaşma, kurum bilgilerini gösterme ve konumu haritada açma seçenekleri eklendi.', 'Etkinliği daha kolay duyurma ve keşfetme'],
      ['Etkinlik yöneticileri sayfa kapağını ve vurgu rengini çalışma alanından düzenleyebilir hâle geldi.', 'Etkinliğe uygun görünümü kolayca hazırlama'],
    ],
  },
  {
    version: '0.22.0',
    title: 'Daha açıklayıcı ve düzenli ana menü',
    changes: [
      ['Ana menü başlangıç, etkinlikler, çalışma alanları, yardım ve Eventise başlıkları altında yeniden düzenlendi.', 'Aranan bölüme daha hızlı ulaşma'],
      ['Menü seçeneklerine hangi işe yaradıklarını anlatan kısa açıklamalar eklendi.', 'Seçmeden önce doğru yolu anlayabilme'],
      ['Yeni etkinlik oluşturma ve Yenilikler bağlantıları görsel olarak öne çıkarıldı.', 'Sık kullanılan ve yeni içeriklere kolay erişim'],
      ['Daraltılmış ve mobil menü görünümleri yeni yapıyla uyumlu hâle getirildi.', 'Masaüstü ve telefonda tutarlı kullanım'],
    ],
  },
  {
    version: '0.21.0',
    title: 'Daha kapsamlı ve kararlı çalışma alanı turu',
    changes: [
      ['Ürün turu etkinlik bilgileri, araçlar, davet ve iletişim, kapı ve katılım ile sonuçlar boyunca genişletildi.', 'Etkinlik yönetiminin tamamını adım adım keşfetme'],
      ['Tur adımları ilgili bölümleri otomatik olarak görünür alana taşıyacak biçimde iyileştirildi.', 'Yönlendirmeyi kaybetmeden ilerleme'],
      ['Eksik veya henüz hazır olmayan bir bölüm turun ilerlemesini engellemeyecek şekilde tur akışı güçlendirildi.', 'Daha kararlı tanıtım deneyimi'],
      ['Tur sırasında vurgulanan alanlar ve açıklama kartlarının konumu küçük ekranlarda iyileştirildi.', 'Telefonda daha rahat ürün turu'],
    ],
  },
  {
    version: '0.20.0',
    title: 'Daha kalıcı oturumlar ve güvenilir e-posta gönderimi',
    changes: [
      ['Oturum süresi uzatıldı; kurum yöneticilerinin kısa aralıklarla yeniden giriş yapma ihtiyacı azaltıldı.', 'Kesintiye uğramayan etkinlik yönetimi'],
      ['Kurum çalışma alanı bulunan kullanıcıların Google ile giriş yaptıktan sonra yanlışlıkla katılımcı alanına yönlendirilmesi engellendi.', 'Her girişte doğru çalışma alanına ulaşma'],
      ['Kurum çalışma alanı bulunan kullanıcıların yeniden kurum oluşturma adımına dönmesi engellendi.', 'Daha tutarlı ve güvenli yönlendirme'],
      ['Başarısız e-posta gönderimleri yeniden denenebilir hâle getirildi; alıcı tarafından kabul edilmeyen iletiler artık başarılı sayılmıyor.', 'Daha güvenilir duyuru ve hatırlatmalar'],
    ],
  },
  {
    version: '0.19.0',
    title: 'Eventise’ı adım adım tanıtan ürün turu',
    changes: [
      ['Etkinlik çalışma alanını ilk kez açan kurum ekipleri için kısa bir karşılama ve rehberli ürün turu eklendi.', 'Eventise’a daha hızlı alışma'],
      ['Tur; kontrol merkezi, yayınlama, kayıt yönetimi, iletişim, kapı işlemleri ve sertifikalar boyunca kullanıcıyı adım adım yönlendiriyor.', 'Temel araçları yerinde keşfetme'],
      ['Ürün turu ana menüden istenildiği zaman yeniden başlatılabilir hâle getirildi.', 'İhtiyaç duyulduğunda rehbere tekrar ulaşma'],
      ['Tur adımları klavye ve küçük ekran kullanımı düşünülerek tasarlandı.', 'Daha erişilebilir bir tanıtım deneyimi'],
    ],
  },
  {
    version: '0.18.0',
    title: 'Google ile girişte daha açık hesap seçimi',
    changes: [
      ['Google ile giriş ve yeni hesap oluşturma işlemleri birbirinden ayrıldı; giriş ekranı yalnızca mevcut Eventise hesaplarını açıyor.', 'İstenmeden yeni hesap oluşmasını önleme'],
      ['Yeni kullanıcılar hesap oluşturmadan önce STK yöneticisi veya katılımcı olarak nasıl devam edeceklerini seçiyor.', 'İlk adımdan itibaren doğru deneyime yönelme'],
      ['Hesap türlerinin açacağı çalışma alanları kayıt ekranında daha açık biçimde anlatılmaya başlandı.', 'Seçim yaparken ne olacağını önceden bilme'],
      ['Kullanım koşulları kabul edildikten sonra kullanıcı seçtiği hesap türüne uygun alana yönlendiriliyor.', 'Kesintisiz ve tutarlı kayıt akışı'],
    ],
  },
  {
    version: '0.17.0',
    title: 'Etkinlik özellikleri artık yaptığı işi anlatıyor',
    changes: [
      ['Etkinlik menüsü Genel Bakış, Etkinlik Bilgileri, Etkinlik Araçları, Davet ve İletişim, Kapı ve Katılım, Sonuçlar ve Sertifikalar olarak açık biçimde adlandırıldı.', 'Aranan özelliği adından anlayabilme'],
      ['“Modüller” bölümü “Etkinlik Araçları” olarak yenilendi; ön test, son test, tanışma oyunu, geri bildirim ve gruplar anlaşılır başlıklarla ayrıldı.', 'Teknik terimleri öğrenmeden araçları kullanma'],
      ['Ön test, son test ve oyun ekranlarındaki eksik Türkçe karakterler, teknik durum adları ve belirsiz işlem metinleri düzeltildi.', 'Daha güven veren ve anlaşılır içerik'],
      ['Duyuru ve kaynak paylaşımının Etkinlik Araçları içindeki tekrarları kaldırıldı; bu işlemler Davet ve İletişim alanında toplandı.', 'Aynı işlem için doğru ve tek bir yer'],
      ['Katılımcı Daveti, Davet ve İletişim ekranının ilk bölümü yapıldı ve daha görünür bir davet alanına dönüştürüldü.', 'Davet işleminin arada kaybolmaması'],
      ['“Etkinlik Günü” ekranı yaptığı işi daha doğru anlatan “Kapı ve Katılım” adıyla yenilendi.', 'QR, kapıda kayıt ve katılım teyidine daha kolay ulaşma'],
      ['Kullanım Rehberi yeni bölüm adları ve güncel işlem yollarıyla eşleştirildi.', 'Ekranlarla aynı dili kullanan yardım içeriği'],
    ],
  },
  {
    version: '0.16.0',
    title: 'Daha sade etkinlik yönetimi ve görerek hazırlanan hatırlatmalar',
    changes: [
      ['Etkinlik çalışma alanı; Genel, Hazırlık, Katılımcı, Uygulama ve Sonuçlar aşamalarına göre yeniden düzenlendi.', 'Etkinliğin her aşamasında daha kolay yön bulma'],
      ['Genel bakış ekranı etkinliğin güncel durumunu, başvuru sayılarını, doluluğu ve sıradaki işleri tek yerde gösterecek şekilde yenilendi.', 'Ne yapılması gerektiğini tek bakışta anlama'],
      ['Sıradaki adımlar etkinliğin taslak, yaklaşan, devam eden veya tamamlanmış olmasına göre otomatik olarak uyarlanıyor.', 'Doğru zamanda doğru işe odaklanma'],
      ['Etkinlik ve kayıt, iletişim, etkinlik günü, rapor ve sertifika araçları daha anlaşılır isimlerle gruplandı.', 'Özellik kaybetmeden daha sade yönetim'],
      ['Hatırlatma planlama alanına şablon düzenleyici, kişiselleştirme alanları ve canlı e-posta ön izlemesi eklendi.', 'Mesajı göndermeden önce son hâliyle görebilme'],
      ['Hatırlatmanın alıcı sayısı, etkinliği ve gönderim zamanı aynı planlama alanında bir araya getirildi.', 'Daha güvenli ve anlaşılır gönderim planlama'],
      ['Planlanan ve gönderilen hatırlatmalar durum rozetleriyle okunabilir bir zaman çizelgesinde gösterilmeye başlandı.', 'Gönderimleri daha kolay takip etme'],
      ['Etkinlik alt menüleri ve çalışma alanı küçük ekranlarda daha rahat kullanılacak şekilde iyileştirildi.', 'Telefonda daha akıcı etkinlik yönetimi'],
    ],
  },
  {
    version: '0.15.0',
    title: 'Etkinlik açıklamalarında doğru biçim ve daha kısa keşif kartları',
    changes: [
      ['Etkinlik açıklamalarındaki kalın, italik, başlık, liste ve bağlantı biçimleri katılımcı ekranlarında doğru şekilde gösterilmeye başlandı.', 'Daha okunaklı etkinlik içerikleri'],
      ['Yaklaşan Etkinlikler ve takip edilen STK etkinlikleri kartlarında kısa açıklamalar kart boyutuna uygun şekilde sınırlandı.', 'Etkinlikleri daha hızlı inceleme'],
      ['Kartlardaki kısa açıklamalar düz metne çevrilmeden Markdown biçimi korunarak gösteriliyor.', 'Vurgularını kaybetmeyen kısa tanıtımlar'],
      ['Etkinlik özeti uzunluk kontrolü oluşturma ve güncelleme işlemlerinde tutarlı hâle getirildi.', 'Daha düzenli etkinlik kartları'],
    ],
  },
  {
    version: '0.14.0',
    title: 'Daha güncel ve ulaşılabilir yardım deneyimi',
    changes: [
      ['Ana menüde yardım içerikleri “Yardım ve Destek”, ürün bilgileri ise “Eventise” başlığı altında yeniden düzenlendi.', 'Aranan bilgiye daha hızlı erişim'],
      ['“STK Rehberi” güncel ürün akışlarını anlatan kapsamlı bir “Kullanım Rehberi” olarak baştan yazıldı.', 'Etkinliğin her aşamasında güncel yönlendirme'],
      ['Kullanım Rehberi’ne anlık arama, sık kullanılan işlemler için hızlı yollar ve “Nereden / Kontrol” bilgi blokları eklendi.', 'Daha az arama, daha kolay uygulama'],
      ['“Sorun Bildir” seçeneği ana menüye eklendi ve bulunulan ekrandan doğrudan bildirim gönderilebilir hâle geldi.', 'İhtiyaç anında daha kolay destek'],
      ['“Güncellemeler” sayfasının adı “Yenilikler” olarak değiştirildi; sürüm numaralı ürün günlüğü yapısı korundu.', 'Ürün gelişimini daha anlaşılır takip etme'],
      ['Eventise Hakkında bölümü SICI’yi ve platformun amacını anlatan daha kısa, samimi bir dille yenilendi.', 'Eventise’ı ve yaklaşımını daha yakından tanıma'],
    ],
  },
  {
    version: '0.13.0',
    title: 'Kurum ekibinizi birlikte yönetin',
    changes: [
      ['Aynı kurumun birden fazla kez oluşturulması engellendi; mevcut kurum bulunduğunda katılma isteği gönderilebiliyor.', 'Tek ve düzenli kurum kaydı'],
      ['Kurum yöneticileri gelen katılma isteklerini Kurum ve ekip ekranından kabul veya reddedebilir hâle geldi.', 'Kontrollü ekip katılımı'],
      ['Bir kuruma birden fazla kurum yöneticisi atanması ve ekip üyelerinin rollerinin sonradan değiştirilmesi eklendi.', 'Görevlerin ekip içinde paylaşılması'],
      ['Son kurum yöneticisinin yetkisinin kaldırılması engellendi.', 'Yöneticisiz kalmayan güvenli çalışma alanı'],
      ['Eventise hesabı olmayan kişiler e-postayla ekip üyesi olarak davet edilebilir hâle geldi.', 'Hesap durumundan bağımsız kolay davet'],
      ['Davet edilen kişi hesabını tamamladığında belirlenen rolle otomatik olarak kuruma ekleniyor.', 'Kesintisiz ekip oluşturma'],
      ['Bekleyen davetleri görüntüleme, yeniden gönderme ve iptal etme seçenekleri eklendi.', 'Daha açık davet takibi'],
    ],
  },
  {
    version: '0.12.0',
    title: 'Daha anlaşılır kurum yönetimi ve navigasyon',
    changes: [
      ['“Kullanım ve plan” alanı sadeleştirilerek “Kullanım” olarak yenilendi; Eventise’ın ücretsiz olduğu ve geçici limit artışı için sistem yöneticisine ulaşılabileceği açıkça belirtildi.', 'Ücretlendirme konusunda daha açık bilgilendirme'],
      ['“Ekip ve ayarlar” ekranı “Kurum ve ekip” olarak yeniden düzenlendi; kurum bilgileri, ekip yönetimi ve kişisel tercihler ayrı bölümlere ayrıldı.', 'Daha anlaşılır kurum yönetimi'],
      ['Yeni etkinlik ve STK Rehberi sayfalarında ana menünün kaybolması engellendi.', 'Sayfalar arasında kesintisiz gezinme'],
      ['Ana menü yeni ikonlar, belirgin aktif sayfa renkleri ve kalıcı daraltma seçeneğiyle yenilendi; mobilde kolay erişilen alt menü eklendi.', 'Daha hızlı ve anlaşılır navigasyon'],
    ],
  },
  {
    version: '0.11.0',
    title: 'Daha güvenilir etkinlik akışları',
    changes: [
      ['Etkinlik oluşturma ve düzenleme adımlarındaki doğrulamalar güçlendirildi; hatalı girişlerde form bilgileri artık korunuyor.', 'Daha az veri kaybı ve daha kolay düzeltme'],
      ['Aynı anda gelen başvurularda kapasite kontrolü iyileştirildi ve tekrarlanan kayıt işlemleri engellendi.', 'Daha doğru kontenjan yönetimi'],
      ['Etkinlik günü araçları tarih veya manuel durum kısıtı olmadan her zaman kullanılabilir hâle getirildi; yinelenen katılım kayıtları önlendi.', 'Önceden prova ve daha güvenilir yoklama'],
      ['Etkinlik kopyalama özelliği kayıt formunu da yeni etkinliğe uyarlayacak şekilde geliştirildi.', 'Daha hızlı etkinlik hazırlığı'],
      ['“Yaklaşan”, “Devam ediyor” ve “Tamamlandı” bilgileri etkinlik tarihinden otomatik hesaplanıyor ve hiçbir aracı kilitlemiyor.', 'Daha sade ve anlaşılır etkinlik durumu'],
      ['Rapor, sertifika ve hatırlatma işlemlerinde tekrar eden talepler ile başarısızlık durumlarının yönetimi iyileştirildi.', 'Daha tutarlı sonuçlar ve açık işlem durumu'],
      ['Fotoğraf, kaynak ve sertifika arka planı yüklemelerine dosya, kota ve etkinlik yetkisi kontrolleri eklendi.', 'Daha güvenli içerik yönetimi'],
      ['Testler, oyunlar, geri bildirimler ve diğer etkinlik araçlarının otomatik kapanması kaldırıldı.', 'Etkinlik öncesinde prova ve sonrasında kesintisiz kullanım'],
      ['Sistem yöneticileri test kullanıcılarını, kurumları ve etkinlikleri bağlı verileriyle birlikte kalıcı olarak temizleyebilir hâle geldi.', 'Daha kolay test verisi temizliği'],
      ['Kayıt, check-in ve yönetim ekranlarında bağlantı hataları daha anlaşılır gösteriliyor; işlem başarısız olduğunda girilen bilgiler silinmiyor.', 'Daha öngörülebilir kullanıcı deneyimi'],
      ['Giriş, kayıt ve etkinlik ekranlarındaki mobil taşma sorunları giderildi.', 'Telefonlarda daha rahat kullanım'],
    ],
  },
  {
    version: '0.10.0',
    title: 'Etkinlik keşfi ve sadeleştirilmiş yönetim',
    changes: [
      ['Katılımcı alanına herkese açık etkinliklerin listelendiği “Yaklaşan Etkinlikler” ekranı eklendi.', 'Yeni etkinlikleri daha kolay keşfetme'],
      ['Etkinlik kartlarında başvuru ve kayıt durumu gösterilmeye başlandı.', 'Katılım durumunu tek bakışta görme'],
      ['Katılımcının yaklaşan, devam eden ve geçmiş etkinlikleri birbirinden ayrıldı.', 'Daha düzenli kişisel etkinlik alanı'],
      ['Takip edilen STK’ların etkinlikleri için filtre ve takip yönetimi eklendi.', 'İlgilenilen etkinliklere daha hızlı ulaşma'],
      ['Etkinlik tanıtım ve kayıt sayfası yenilendi; mobil kayıt işlemi kolaylaştırıldı.', 'Daha anlaşılır ve akıcı kayıt deneyimi'],
      ['Yeni etkinlikler varsayılan olarak herkese açık oluşturulmaya başlandı.', 'Etkinliklerin daha kolay keşfedilmesi'],
      ['Etkinlik yönetimindeki manuel “Canlıya al” adımı kaldırıldı; dönem bilgisi tarihe göre otomatik gösteriliyor.', 'Daha az işlem ve daha açık yönetim'],
      ['Etkinlik günü araçları etkinlikten önce denenebilir hâle getirildi ve otomatik kapatma kaldırıldı.', 'Daha rahat hazırlık ve prova imkânı'],
      ['Yeni etkinlik oluşturma akışındaki kullanılmayan şablon adımları temizlendi.', 'Daha kısa ve sade etkinlik oluşturma'],
    ],
  },
  {
    version: '0.9.0',
    title: 'Daha kolay erişim ve geri bildirim',
    changes: [
      ['Google hesabıyla giriş seçeneği eklendi.', 'Daha hızlı erişim'],
      ['“Sorun Bildir” özelliği eklendi; karşılaşılan sorunlar bulunulan ekrandan iletilebilir.', 'Daha kolay geri bildirim'],
      ['Beta sürümü bilgilendirmesi eklendi.', 'Daha şeffaf ürün deneyimi'],
      ['Katılımcı ana sayfası sadeleştirildi; etkinlikler ve takip edilen kurumlar ayrıldı.', 'Daha düzenli katılımcı alanı'],
      ['Kurum takip etme özelliği eklendi.', 'Etkinliklerden daha kolay haberdar olma'],
      ['Etkinlik bağlantıları ve yönlendirmeleri iyileştirildi.', 'Daha akıcı gezinme'],
    ],
  },
  {
    version: '0.8.0',
    title: 'İletişim ve sertifika geliştirmeleri',
    changes: [
      ['İletişim şablonları ve katılımcı mesajları daha anlaşılır hâle getirildi.', 'Daha tutarlı iletişim'],
      ['Gönderilen bildirimlerin ve planlanan hatırlatmaların takibi iyileştirildi.', 'Daha güvenilir planlama'],
      ['Sertifika hazırlama, görüntüleme ve yönetim ekranları geliştirildi.', 'Daha düzenli sertifika süreci'],
      ['Sertifika görünümü etkinliğe uygun biçimde özelleştirilebilir hâle getirildi.', 'Kuruma uygun görünüm'],
      ['Etkinlik açıklamalarındaki başlık, liste ve bağlantı gösterimleri iyileştirildi.', 'Daha rahat okunabilirlik'],
    ],
  },
  {
    version: '0.7.0',
    title: 'Katılımcı deneyimi ve rehber',
    changes: [
      ['Katılımcılar için başvuru, içerik ve etkinlik sonrası işlemleri bir araya getiren etkinlik sayfası eklendi.', 'Tüm işlemler bir arada'],
      ['Etkinlik içerikleri açılır-kapanır bölümler hâlinde düzenlendi.', 'Daha sade ekran kullanımı'],
      ['Etkinlik günü giriş ve katılım yönlendirmeleri iyileştirildi.', 'Daha hızlı etkinlik günü deneyimi'],
      ['Değerlendirme formlarına sayı, kısa metin ve uzun açıklama soru türleri eklendi.', 'Daha kapsamlı geri bildirim'],
      ['Kaynak ve etkinlik içeriklerinin katılımcılara sunulması iyileştirildi.', 'Bilgilere daha kolay erişim'],
      ['STK Rehberi ve sık sorulan sorular sayfası oluşturularak ana menüye eklendi.', 'Daha hızlı destek'],
    ],
  },
  {
    version: '0.6.0',
    title: 'Etkinlik içi modüller',
    changes: [
      ['Test ve değerlendirme modülleri ile hazır test şablonları eklendi.', 'Esnek ve hızlı içerik oluşturma'],
      ['Değerlendirme soru düzenleyicisi yenilendi.', 'Daha kolay düzenleme'],
      ['Ön test ve son test sonuçlarını karşılaştırma özelliği eklendi.', 'Daha anlamlı sonuçlar'],
      ['Otomatik ve manuel grup oluşturma özellikleri eklendi.', 'Esnek grup yönetimi'],
      ['Oyun ve etkinlik içi görev modülleri geliştirildi; sonuçlar kontrollü biçimde açıklanabilir hâle geldi.', 'Daha etkileşimli etkinlikler'],
      ['Geri bildirimler kategorilere ayrılabilir hâle getirildi.', 'Daha düzenli değerlendirme'],
      ['Modül işlemlerindeki açıklamalar ve hata mesajları iyileştirildi.', 'Daha anlaşılır kullanım'],
    ],
  },
  {
    version: '0.5.0',
    title: 'Etkinlik günü yönetimi',
    changes: [
      ['QR kod ile katılımcı girişi ve kapıda kayıt özellikleri eklendi.', 'Daha hızlı ve esnek giriş'],
      ['Girişler, saha işlemleri ve katılım durumunu bir araya getiren kontrol merkezi oluşturuldu.', 'Merkezi operasyon yönetimi'],
      ['Saha görevlisi atama ve görev yönetimi eklendi.', 'Daha koordineli ekip çalışması'],
      ['Katılımcı giriş ve çıkış kayıtları geliştirildi.', 'Daha doğru katılım takibi'],
      ['Giriş sırasında yaşanan kayıt ve yönlendirme sorunları giderildi.', 'Daha sorunsuz etkinlik günü'],
    ],
  },
  {
    version: '0.4.0',
    title: 'Etkinlik ve başvuru yönetimi',
    changes: [
      ['Adım adım yeni etkinlik oluşturma akışı geliştirildi.', 'Daha kolay etkinlik oluşturma'],
      ['Yüz yüze, çevrim içi ve hibrit etkinlik türleri ile çevrim içi bağlantı desteği eklendi.', 'Farklı etkinlik modelleri'],
      ['Etkinlik açıklamalarına başlık, liste, bağlantı ve vurgu desteği eklendi.', 'Daha etkili etkinlik tanıtımı'],
      ['Etkinlik bilgi ve ayarları anlaşılır bölümlere ayrıldı.', 'Daha kolay yönetim'],
      ['Etkinliğe özel SSS alanı ve görsel SSS düzenleyicisi eklendi.', 'Daha açık bilgilendirme'],
      ['Başvuru formu, görsel alan düzenleyicisi ve form sürüm yönetimi eklendi.', 'İhtiyaca uygun başvurular'],
      ['Formların yeni etkinlikle birlikte hazır oluşturulması sağlandı.', 'Daha az kurulum adımı'],
      ['Başvuruları tek ekrandan inceleme, kabul etme ve reddetme özellikleri eklendi.', 'Merkezi başvuru yönetimi'],
      ['Katılım ve iletişim onayları başvuru sürecine eklendi.', 'Daha açık başvuru süreci'],
      ['Davetli etkinlik desteği ile kayıtları açma ve kapatma kontrolleri eklendi.', 'Kontrollü katılım'],
    ],
  },
  {
    version: '0.3.0',
    title: 'Etkinlik çalışma alanı ve iletişim',
    changes: [
      ['Etkinliğin tüm aşamalarını bir araya getiren yönetim çalışma alanı oluşturuldu.', 'Bütünlüklü çalışma alanı'],
      ['Yönetim; Dashboard, Ayarlar, Modüller, İletişim, Etkinlik Günü, Etkinlik Sonrası ve Sertifikalar bölümlerine ayrıldı.', 'Daha kolay gezinme'],
      ['Etkinlik yol haritası ve “Yayına Al” özelliği eklendi.', 'Süreç boyunca yönlendirme'],
      ['Etkinlik özellikleri için hızlı açma-kapama kontrolleri ve silme işlemi eklendi.', 'Daha fazla kontrol'],
      ['E-posta şablonları, hedefli bilgilendirmeler ve hatırlatma planlama özellikleri eklendi.', 'Merkezi iletişim'],
      ['Gönderilen mesajların görüntülenmesi ve etkinlik özeti hazırlama kolaylaştırıldı.', 'Daha kolay takip'],
    ],
  },
  {
    version: '0.2.0',
    title: 'Etkinlik sonrası süreçler',
    changes: [
      ['Değerlendirme, raporlama ve katılımcı işlemleri için etkinlik sonrası yönetim alanı eklendi.', 'Düzenli kapanış süreci'],
      ['Katılımcı geri bildirim formları ile etkinlik raporu oluşturma ve paylaşma özellikleri eklendi.', 'Sonuçları değerlendirme'],
      ['Etkinlik sonrası kaynak ve içerik paylaşımı eklendi.', 'Etkinlik sonrasında bilgiye erişim'],
      ['Sertifika oluşturma, katılımcıya sunma ve kodla doğrulama özellikleri eklendi.', 'Kolay sertifika teslimi'],
      ['Katılımcıların etkinliklerini takip edebildiği kişisel alan oluşturuldu.', 'Kişisel etkinlik takibi'],
      ['Etkinlik kapatma ve sonuçlandırma akışı geliştirildi.', 'Eksiksiz etkinlik yaşam döngüsü'],
    ],
  },
  {
    version: '0.1.0',
    title: 'İlk Eventise sürümü',
    changes: [
      ['STK’lar için etkinlik yönetim panelinin ilk sürümü oluşturuldu.', 'Dijital etkinlik yönetimi'],
      ['Kurum hesabı, kullanıcı kaydı ve giriş adımları eklendi.', 'Kuruma özel çalışma alanı'],
      ['Etkinlik listeleme, oluşturma ve düzenleme akışları hazırlandı.', 'Etkinliklere tek noktadan erişim'],
      ['Katılımcı başvurularını görüntüleme ve sonuçlandırma özellikleri eklendi.', 'Düzenli başvuru takibi'],
      ['E-posta iletişim planlama ve etkinlik günü giriş işlemlerinin ilk sürümleri eklendi.', 'Merkezi operasyon'],
      ['Kurum ekibi, görevler, kullanım bilgileri ve sistem yönetimi ekranları oluşturuldu.', 'Birlikte çalışma'],
      ['Ana menü ve etkinlik yönetimi navigasyonu oluşturuldu.', 'Kolay gezinme'],
    ],
  },
] as const;
