import { INestApplication, ValidationPipe } from '@nestjs/common'; import { Test } from '@nestjs/testing'; import { PrismaClient } from '@prisma/client'; import request from 'supertest'; import { afterAll,beforeAll,describe,expect,inject,it } from 'vitest'; import { AppModule } from '../../dist/app.module';
describe('Phase 2 pre-event workflow',()=>{let app:INestApplication,prisma:PrismaClient,token:string,orgId:string,eventId:string,consentVersionId:string;
beforeAll(async()=>{process.env.DATABASE_URL=inject('databaseUrl');process.env.JWT_SECRET='integration-test-secret-at-least-32-characters';prisma=new PrismaClient();const m=await Test.createTestingModule({imports:[AppModule]}).compile();app=m.createNestApplication();app.setGlobalPrefix('api');app.useGlobalPipes(new ValidationPipe({whitelist:true,forbidNonWhitelisted:true,transform:true}));await app.init();token=(await request(app.getHttpServer()).post('/api/auth/register').send({email:'phase2@example.org',firstName:'Phase',lastName:'Two',password:'SecurePassword1'})).body.accessToken;await request(app.getHttpServer()).post('/api/legal/accept-user-terms').set('Authorization',`Bearer ${token}`).send({version:'1.0'}).expect(201);orgId=(await request(app.getHttpServer()).post('/api/organizations').set('Authorization',`Bearer ${token}`).send({name:'Phase 2 STK',slug:'phase-2-stk',contactEmail:'p2@example.org',organizationType:'DERNEK',representativeRole:'Koordinatör',authorityDeclared:true,organizationTermsAccepted:true,organizationTermsVersion:'1.0'}).expect(201)).body.id});afterAll(async()=>{await app.close();await prisma.$disconnect()});
it('creates defaults, versioned consent, and publishes an event with FAQ',async()=>{const emailTemplates=(await request(app.getHttpServer()).get(`/api/organizations/${orgId}/email-templates`).set('Authorization',`Bearer ${token}`).expect(200)).body;expect(emailTemplates).toHaveLength(13);expect(emailTemplates.filter((template:{category:string})=>template.category==='REMINDER')).toHaveLength(2);expect(emailTemplates.find((template:{key:string})=>template.key==='application_received').subject).toContain('Başvurunuzu aldık');expect(await prisma.formTemplate.count({where:{organizationId:orgId}})).toBe(4);const event=(await request(app.getHttpServer()).post(`/api/organizations/${orgId}/events`).set('Authorization',`Bearer ${token}`).send({title:'Gönüllü Buluşması',slug:'gonullu-bulusmasi',startsAt:'2027-06-20T09:00:00.000Z',endsAt:'2027-06-20T15:00:00.000Z',capacity:1,registrationMode:'DIRECT',faqs:[{question:'Ücretli mi?',answer:'Hayır.'}]}).expect(201)).body;eventId=event.id;const consent=(await request(app.getHttpServer()).post(`/api/organizations/${orgId}/consents`).set('Authorization',`Bearer ${token}`).send({key:'kvkk',title:'KVKK Onamı',text:'Verilerimin etkinlik için işlenmesini kabul ediyorum.'}).expect(201)).body;consentVersionId=consent.versions[0].id;await request(app.getHttpServer()).put(`/api/organizations/${orgId}/events/${eventId}/consents/${consent.id}`).set('Authorization',`Bearer ${token}`).send({required:true}).expect(200);await request(app.getHttpServer()).patch(`/api/organizations/${orgId}/events/${eventId}/state`).set('Authorization',`Bearer ${token}`).send({publicationStatus:'PUBLISHED',registrationStatus:'OPEN'}).expect(200);expect((await request(app.getHttpServer()).get('/api/public/events/phase-2-stk/gonullu-bulusmasi').expect(200)).body.faqs).toHaveLength(1)});
it('returns AI drafts without persisting them',async()=>{const before=await prisma.event.count();const response=(await request(app.getHttpServer()).post(`/api/organizations/${orgId}/event-drafts/extract`).set('Authorization',`Bearer ${token}`).send({text:'Dayanışma Atölyesi\nTarih: 20.06.2027\nMekân: Kent Merkezi\nKontenjan: 40'}).expect(201)).body;expect(response).toMatchObject({requiresHumanApproval:true,persisted:false});expect(response.draft.capacity).toBe(40);expect(await prisma.event.count()).toBe(before)});
it('enforces current consent, applies capacity and queues email messages',async()=>{const submit=(email:string,consents=[consentVersionId])=>request(app.getHttpServer()).post('/api/public/events/phase-2-stk/gonullu-bulusmasi/registrations').send({email,firstName:'Ada',lastName:'Test',answers:{city:'İstanbul'},consentVersionIds:consents});await submit('missing@example.org',[]).expect(400);expect((await submit('ADA@example.org').expect(201)).body.status).toBe('ACCEPTED');await submit('ada@example.org').expect(409);expect((await submit('second@example.org').expect(201)).body.status).toBe('WAITLISTED');expect((await request(app.getHttpServer()).get(`/api/organizations/${orgId}/events/${eventId}/registrations`).set('Authorization',`Bearer ${token}`).expect(200)).body).toHaveLength(2);const messages=await prisma.emailMessage.findMany({where:{recipient:{in:['ada@example.org','second@example.org']}}});expect(messages.filter(m=>m.subject==='Eventise hesabınızı tamamlayın')).toHaveLength(2);expect(messages.filter(m=>m.subject!=='Eventise hesabınızı tamamlayın')).toHaveLength(2);expect(await prisma.accountSetupToken.count({where:{user:{email:{in:['ada@example.org','second@example.org']}}}})).toBe(2)});

it('atomically limits reminders and keeps cancellation reusable',async()=>{
  const templates=await prisma.emailTemplate.findMany({where:{organizationId:orgId,category:'REMINDER'},orderBy:{key:'asc'}});
  const schedule=(templateId:string,sendAt:string)=>request(app.getHttpServer()).post(`/api/organizations/${orgId}/events/${eventId}/reminders`).set('Authorization',`Bearer ${token}`).send({templateId,sendAt});
  const responses=await Promise.all([
    schedule(templates[0].id,'2027-05-01T09:00:00.000Z'),
    schedule(templates[1].id,'2027-05-02T09:00:00.000Z'),
    schedule(templates[0].id,'2027-05-03T09:00:00.000Z'),
  ]);
  expect(responses.map(response=>response.status).sort()).toEqual([201,201,400]);
  const planned=await prisma.scheduledNotification.findMany({where:{eventId,status:'SCHEDULED'}});
  expect(planned).toHaveLength(2);
  expect(await prisma.backgroundJob.count({where:{idempotencyKey:{in:planned.map(item=>`notification:${item.id}`)}}})).toBe(2);
  await request(app.getHttpServer()).delete(`/api/organizations/${orgId}/events/${eventId}/reminders/${planned[0].id}`).set('Authorization',`Bearer ${token}`).expect(200);
  await schedule(templates[0].id,'2027-05-04T09:00:00.000Z').expect(201);
  expect(await prisma.scheduledNotification.count({where:{eventId,status:'SCHEDULED'}})).toBe(2);
});
});
