CREATE TYPE "AccountStatus" AS ENUM ('ACTIVE', 'SUSPENDED', 'DELETED_PENDING');
CREATE TYPE "OrganizationStatus" AS ENUM ('ACTIVE', 'SUSPENDED', 'DELETED_PENDING');
CREATE TYPE "OrganizationRole" AS ENUM ('ORGANIZATION_ADMIN', 'EVENT_MANAGER', 'FIELD_STAFF');
CREATE TYPE "JobStatus" AS ENUM ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED');
CREATE TABLE "User" ("id" TEXT NOT NULL, "email" TEXT NOT NULL, "passwordHash" TEXT NOT NULL, "firstName" TEXT NOT NULL, "lastName" TEXT NOT NULL, "preferredLanguage" TEXT NOT NULL DEFAULT 'tr', "emailVerifiedAt" TIMESTAMP(3), "status" "AccountStatus" NOT NULL DEFAULT 'ACTIVE', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Tier" ("id" TEXT NOT NULL, "key" TEXT NOT NULL, "name" TEXT NOT NULL, "maxActiveEvents" INTEGER NOT NULL, "maxParticipantsPerEvent" INTEGER NOT NULL, "photoStorageLimitBytes" BIGINT NOT NULL, "fileStorageLimitBytes" BIGINT NOT NULL, "maxPhotosPerEvent" INTEGER NOT NULL, "defaultMaxPhotosPerParticipant" INTEGER NOT NULL, "emailMultiplier" INTEGER NOT NULL, "allowedFileTypes" TEXT[], "featureFlags" JSONB NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Tier_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Organization" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "slug" TEXT NOT NULL, "description" TEXT, "contactEmail" TEXT NOT NULL, "website" TEXT, "defaultLanguage" TEXT NOT NULL DEFAULT 'tr', "status" "OrganizationStatus" NOT NULL DEFAULT 'ACTIVE', "announcementApproved" BOOLEAN NOT NULL DEFAULT false, "tierId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Organization_pkey" PRIMARY KEY ("id"));
CREATE TABLE "OrganizationMembership" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "organizationId" TEXT NOT NULL, "role" "OrganizationRole" NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "OrganizationMembership_pkey" PRIMARY KEY ("id"));
CREATE TABLE "OrganizationTierOverride" ("id" TEXT NOT NULL, "organizationId" TEXT NOT NULL, "limits" JSONB NOT NULL, "expiresAt" TIMESTAMP(3), "reason" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "OrganizationTierOverride_pkey" PRIMARY KEY ("id"));
CREATE TABLE "UsageCounter" ("id" TEXT NOT NULL, "organizationId" TEXT NOT NULL, "key" TEXT NOT NULL, "period" TEXT NOT NULL, "value" BIGINT NOT NULL DEFAULT 0, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "UsageCounter_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AuditLog" ("id" TEXT NOT NULL, "organizationId" TEXT, "actorId" TEXT, "action" TEXT NOT NULL, "resourceType" TEXT NOT NULL, "resourceId" TEXT, "metadata" JSONB NOT NULL, "ipHash" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AuditLog_pkey" PRIMARY KEY ("id"));
CREATE TABLE "BackgroundJob" ("id" TEXT NOT NULL, "type" TEXT NOT NULL, "payload" JSONB NOT NULL, "status" "JobStatus" NOT NULL DEFAULT 'PENDING', "runAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "attempts" INTEGER NOT NULL DEFAULT 0, "maxAttempts" INTEGER NOT NULL DEFAULT 5, "lockedAt" TIMESTAMP(3), "lockedBy" TEXT, "completedAt" TIMESTAMP(3), "lastError" TEXT, "idempotencyKey" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "BackgroundJob_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
CREATE UNIQUE INDEX "Tier_key_key" ON "Tier"("key");
CREATE UNIQUE INDEX "Organization_slug_key" ON "Organization"("slug");
CREATE INDEX "OrganizationMembership_organizationId_role_idx" ON "OrganizationMembership"("organizationId", "role");
CREATE UNIQUE INDEX "OrganizationMembership_userId_organizationId_key" ON "OrganizationMembership"("userId", "organizationId");
CREATE UNIQUE INDEX "OrganizationTierOverride_organizationId_key" ON "OrganizationTierOverride"("organizationId");
CREATE UNIQUE INDEX "UsageCounter_organizationId_key_period_key" ON "UsageCounter"("organizationId", "key", "period");
CREATE INDEX "AuditLog_organizationId_createdAt_idx" ON "AuditLog"("organizationId", "createdAt");
CREATE INDEX "AuditLog_actorId_createdAt_idx" ON "AuditLog"("actorId", "createdAt");
CREATE UNIQUE INDEX "BackgroundJob_idempotencyKey_key" ON "BackgroundJob"("idempotencyKey");
CREATE INDEX "BackgroundJob_status_runAt_idx" ON "BackgroundJob"("status", "runAt");
ALTER TABLE "Organization" ADD CONSTRAINT "Organization_tierId_fkey" FOREIGN KEY ("tierId") REFERENCES "Tier"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "OrganizationMembership" ADD CONSTRAINT "OrganizationMembership_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "OrganizationMembership" ADD CONSTRAINT "OrganizationMembership_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "OrganizationTierOverride" ADD CONSTRAINT "OrganizationTierOverride_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "UsageCounter" ADD CONSTRAINT "UsageCounter_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_actorId_fkey" FOREIGN KEY ("actorId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
