import { BadRequestException, ConflictException, Inject, Injectable, NotFoundException } from '@nestjs/common';
import { GameSessionStatus, Prisma } from '@prisma/client';
import { PrismaService } from '../../shared/persistence/prisma.service';
import { OrganizationAccessService } from '../organizations/policies/organization-access.service';
import { AuditService } from '../audit/audit.service';
import { FeaturesService } from '../features/features.service';
const icebreaker = { key: 'icebreaker_match', title: 'Başkasının Yanıtını Oku', defaultPrompt: 'Diğer katılımcıların seni tanımasını sağlayacak kısa bir anını veya ilgi alanını yaz.' };
@Injectable()
export class ActivitiesService {
  constructor(@Inject(PrismaService) private prisma: PrismaService, @Inject(OrganizationAccessService) private access: OrganizationAccessService, @Inject(AuditService) private audit: AuditService, @Inject(FeaturesService) private features: FeaturesService) {}
  definitions() { return [icebreaker]; }
  async list(userId: string, organizationId: string, eventId: string) { await this.access.requireEventAccess(userId, organizationId, eventId); return this.prisma.gameSession.findMany({ where: { eventId }, include: { _count: { select: { participants: true, responses: true } } }, orderBy: { createdAt: 'desc' } }); }
  async details(userId: string, organizationId: string, sessionId: string) { const session = await this.sessionForStaff(userId, organizationId, sessionId); const [responses, assignments] = await Promise.all([ this.prisma.gameResponse.findMany({ where: { sessionId } }), this.prisma.gameAssignment.findMany({ where: { sessionId } }) ]); const regIds = new Set<string>(); responses.forEach(r => regIds.add(r.registrationId)); assignments.forEach(a => { regIds.add(a.registrationId); regIds.add(a.targetRegistrationId); }); const regs = await this.prisma.eventRegistration.findMany({ where: { id: { in: [...regIds] } }, select: { id: true, firstName: true, lastName: true } }); const regMap = new Map(regs.map(r => [r.id, `${r.firstName} ${r.lastName}`])); return { session: { id: session.id, title: session.title, status: session.status, prompt: String((session.config as Record<string, unknown>).prompt ?? '') }, responses: responses.map(r => ({ id: r.id, name: regMap.get(r.registrationId) ?? '—', answer: r.answer })), assignments: assignments.map(a => ({ from: regMap.get(a.registrationId) ?? '—', to: regMap.get(a.targetRegistrationId) ?? '—' })) }; }
  async create(userId: string, organizationId: string, eventId: string, title?: string, prompt?: string) { await this.access.requireEventAccess(userId, organizationId, eventId, ['ORGANIZATION_ADMIN', 'EVENT_MANAGER']); return this.prisma.gameSession.create({ data: { eventId, gameKey: icebreaker.key, title: title ?? icebreaker.title, config: { prompt: prompt ?? icebreaker.defaultPrompt } } }); }
  async open(userId: string, organizationId: string, sessionId: string) { const session = await this.sessionForStaff(userId, organizationId, sessionId); await this.features.assertEnabled(session.eventId, 'icebreaker'); const registrations = await this.prisma.eventRegistration.findMany({ where: { eventId: session.eventId, applicationStatus: 'ACCEPTED' }, select: { id: true } }); if (registrations.length < 2) throw new BadRequestException('Oyun için en az iki kabul edilmiş katılımcı gerekir.'); const prompt = String((session.config as Record<string, unknown>).prompt ?? icebreaker.defaultPrompt); await this.prisma.$transaction(async tx => { await tx.gameParticipant.createMany({ data: registrations.map(r => ({ sessionId, registrationId: r.id })), skipDuplicates: true }); await tx.gameAssignment.createMany({ data: registrations.map((r, index) => ({ sessionId, registrationId: r.id, targetRegistrationId: registrations[(index + 1) % registrations.length].id, prompt })), skipDuplicates: true }); await tx.gameSession.update({ where: { id: sessionId }, data: { status: 'OPEN' } }); }); await this.audit.record({ actorId: userId, organizationId, action: 'game.opened', resourceType: 'game_session', resourceId: sessionId }); return this.prisma.gameSession.findUnique({ where: { id: sessionId }, include: { assignments: true } }); }
  async setStatus(userId: string, organizationId: string, sessionId: string, status: Extract<GameSessionStatus, 'REVEAL'|'COMPLETED'>) { const session = await this.sessionForStaff(userId, organizationId, sessionId); if (status === 'REVEAL' && session.status !== 'OPEN') throw new BadRequestException('Yalnız açık oyun reveal aşamasına alınabilir.'); if (status === 'COMPLETED' && session.status !== 'REVEAL') throw new BadRequestException('Yalnız reveal aşamasındaki oyun tamamlanabilir.'); const updated = await this.prisma.gameSession.update({ where: { id: sessionId }, data: { status } }); await this.audit.record({ actorId: userId, organizationId, action: status === 'REVEAL' ? 'game.revealed' : 'game.completed', resourceType: 'game_session', resourceId: sessionId }); return updated; }
  async myAssignment(userId: string, sessionId: string) { const { session, registration } = await this.participantSession(userId, sessionId, ['OPEN', 'REVEAL']); const assignment = await this.prisma.gameAssignment.findUnique({ where: { sessionId_registrationId: { sessionId, registrationId: registration.id } } }); if (!assignment) throw new NotFoundException('Oyun eşleşmesi bulunamadı.'); const target = await this.prisma.eventRegistration.findUniqueOrThrow({ where: { id: assignment.targetRegistrationId }, select: { firstName: true, lastName: true } }); return { ...assignment, status: session.status, target }; }
  async revealedAnswer(userId: string, sessionId: string) { const { registration } = await this.participantSession(userId, sessionId, ['REVEAL']); const assignment = await this.prisma.gameAssignment.findUnique({ where: { sessionId_registrationId: { sessionId, registrationId: registration.id } } }); if (!assignment) throw new NotFoundException('Oyun eşleşmesi bulunamadı.'); const response = await this.prisma.gameResponse.findFirst({ where: { sessionId, registrationId: assignment.targetRegistrationId }, select: { answer: true } }); if (!response) throw new NotFoundException('Eşleşen katılımcının yanıtı henüz yok.'); return { answer: response.answer, anonymous: true };
  }
  async respond(userId: string, sessionId: string, promptKey: string, answer: string) { const { registration } = await this.participantSession(userId, sessionId, ['OPEN']); try{return await this.prisma.gameResponse.create({ data: { sessionId, registrationId: registration.id, promptKey, answer: answer.trim() } })}catch(error){if(error instanceof Prisma.PrismaClientKnownRequestError&&error.code==='P2002')throw new ConflictException('Bu oyun yanıtını daha önce gönderdiniz.');throw error} }
  private async sessionForStaff(userId: string, organizationId: string, sessionId: string) { const session = await this.prisma.gameSession.findUnique({ where: { id: sessionId }, include: { event: true } }); if (!session || session.event.organizationId !== organizationId) throw new NotFoundException('Oyun oturumu bulunamadı.'); await this.access.requireEventAccess(userId, organizationId, session.eventId, ['ORGANIZATION_ADMIN', 'EVENT_MANAGER']); return session; }
  private async participantSession(userId: string, sessionId: string, statuses: GameSessionStatus[]) { const user = await this.prisma.user.findUnique({ where: { id: userId } }), session = await this.prisma.gameSession.findUnique({ where: { id: sessionId } }); if (!user || !session || !statuses.includes(session.status)) throw new NotFoundException('Uygun durumda oyun bulunamadı.'); await this.features.assertEnabled(session.eventId, 'icebreaker'); const registration = await this.prisma.eventRegistration.findUnique({ where: { eventId_email: { eventId: session.eventId, email: user.email } } }); if (!registration || registration.applicationStatus !== 'ACCEPTED') throw new NotFoundException('Katılımcı kaydı bulunamadı.'); return { session, registration };
  }
}
