'use client';
import { FormEvent, useState } from 'react';
import { ManualGroups } from './manual-groups';
import { TestComparison } from './test-comparison';

type Group={id:string;name:string;members:Array<{registration:{id:string;firstName:string;lastName:string}}>};
type Game={id:string;title:string;status:string;_count:{participants:number;responses:number}};
type Assessment={id:string;kind:'PRE_TEST'|'POST_TEST';title:string;open:boolean;_count:{submissions:number}};
type Feedback={id:string;title:string;open:boolean;_count:{submissions:number}};
type Feature={key:string;enabled:boolean}; type Person={id:string;firstName:string;lastName:string};
type Comparison={pre:{submissions:number;average:number|null};post:{submissions:number;average:number|null};improvement:number|null};

export function ModuleManager(p:{organizationId:string;eventId:string;initialGroups:Group[];initialGames:Game[];initialAssessments:Assessment[];initialFeedback:Feedback[];initialFeatures:Feature[];roster:Person[];initialComparison:Comparison}) {
 const {organizationId,eventId,roster}=p; const[tab,setTab]=useState('groups'),[groups,setGroups]=useState(p.initialGroups),[games,setGames]=useState(p.initialGames),[assessments,setAssessments]=useState(p.initialAssessments),[feedback,setFeedback]=useState(p.initialFeedback),[features,setFeatures]=useState(p.initialFeatures),[comparison,setComparison]=useState(p.initialComparison),[message,setMessage]=useState('');
 async function call(path:string,method='POST',body?:object){const response=await fetch(`/api/backend/${path}`,{method,headers:{'content-type':'application/json'},body:body?JSON.stringify(body):undefined});const data=await response.json();if(!response.ok){setMessage(Array.isArray(data.message)?data.message.join(' '):(data.message??'İşlem tamamlanamadı.'));return null}setMessage('İşlem tamamlandı.');return data}
 async function enable(key:string){if(features.find(x=>x.key===key)?.enabled)return true;const result=await call(`organizations/${organizationId}/events/${eventId}/features/${key}`,'PUT',{enabled:true,config:{}});if(result)setFeatures(v=>v.map(x=>x.key===key?{...x,enabled:true}:x));return Boolean(result)}
 async function generate(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!await enable('groups'))return;const d=new FormData(e.currentTarget),r=await call(`organizations/${organizationId}/events/${eventId}/groups/generate`,'POST',{count:Number(d.get('count')),strategy:d.get('strategy'),balanceField:d.get('balanceField')||undefined});if(r)setGroups(r)}
 async function saveManual(values:string[][]){if(!await enable('groups'))return false;const r=await call(`organizations/${organizationId}/events/${eventId}/groups/manual`,'POST',{groups:values});if(r)setGroups(r);return Boolean(r)}
 async function createGame(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!await enable('icebreaker'))return;const d=new FormData(e.currentTarget),created=await call(`organizations/${organizationId}/events/${eventId}/games`,'POST',{title:d.get('title'),prompt:d.get('prompt')});if(created){const opened=await call(`organizations/${organizationId}/game-sessions/${created.id}/open`);if(opened)setGames(v=>[{...created,status:'OPEN',_count:{participants:opened.assignments.length,responses:0}},...v])}}
 async function gameStatus(x:Game,action:'reveal'|'complete'){const r=await call(`organizations/${organizationId}/game-sessions/${x.id}/${action}`);if(r)setGames(v=>v.map(g=>g.id===x.id?{...g,status:r.status}:g))}
 async function createTest(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!await enable('assessments'))return;const d=new FormData(e.currentTarget),questions=String(d.get('questions')).split('\n').map((line,i)=>{const[label,correctAnswer]=line.split('|').map(x=>x.trim());return{id:`q${i+1}`,type:'single',label,correctAnswer}}).filter(x=>x.label&&x.correctAnswer);const created=await call(`organizations/${organizationId}/events/${eventId}/assessments`,'POST',{kind:d.get('kind'),title:d.get('title'),questions});if(created){await call(`organizations/${organizationId}/assessments/${created.id}/open`,'PATCH',{open:true});setAssessments(v=>[{...created,open:true,_count:{submissions:0}},...v])}}
 async function copyTest(x:Assessment){const kind=x.kind==='PRE_TEST'?'POST_TEST':'PRE_TEST',r=await call(`organizations/${organizationId}/assessments/${x.id}/copy`,'POST',{kind,title:`${x.title} — ${kind==='POST_TEST'?'Son test':'Ön test'}`});if(r)setAssessments(v=>[{...r,open:false,_count:{submissions:0}},...v])}
 async function createFeedback(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!await enable('feedback'))return;const d=new FormData(e.currentTarget),r=await call(`organizations/${organizationId}/events/${eventId}/feedback`,'POST',{title:d.get('title'),schema:{questions:[{id:'rating',type:'number',label:d.get('question')}]}});if(r){await call(`organizations/${organizationId}/feedback/${r.id}/open`,'PATCH',{open:true});setFeedback(v=>[{...r,open:true,_count:{submissions:0}},...v])}}
 const tabs=[['groups','Gruplar'],['game','Tanışma oyunu'],['tests','Testler'],['feedback','Geri bildirim'],['notifications','Duyurular']];
 return <><nav className="workspace-tabs">{tabs.map(([k,l])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{l}</button>)}</nav>{message&&<p className="notice">{message}</p>}<section className="module-workspace">
 {tab==='groups'&&<><form className="workspace-card" onSubmit={generate}><h2>Otomatik gruplama</h2><input name="count" type="number" min="1" defaultValue="2"/><select name="strategy"><option value="RANDOM">Rastgele</option><option value="BALANCED">Dengeli</option></select><input name="balanceField" placeholder="Denge alanı (isteğe bağlı)"/><button>Grupları oluştur</button></form><div className="group-board">{groups.map(g=><article className="workspace-card" key={g.id}><h3>{g.name}</h3>{g.members.map(m=><span className="participant-chip" key={m.registration.id}>{m.registration.firstName} {m.registration.lastName}</span>)}</article>)}</div><ManualGroups people={roster} initial={groups.map(g=>g.members.map(m=>m.registration.id))} onSave={saveManual}/></>}
 {tab==='game'&&<><form className="workspace-card" onSubmit={createGame}><h2>Tanışma oyunu</h2><input name="title" defaultValue="Başkasının Yanıtını Oku"/><textarea name="prompt" required/><button>Oluştur ve aç</button></form>{games.map(g=><article className="workspace-card" key={g.id}><h3>{g.title}</h3><p>{g.status} · {g._count.responses}/{g._count.participants}</p>{g.status==='OPEN'&&<button onClick={()=>gameStatus(g,'reveal')}>Yanıtları göster</button>}{g.status==='REVEAL'&&<button onClick={()=>gameStatus(g,'complete')}>Tamamla</button>}</article>)}</>}
 {tab==='tests'&&<><form className="workspace-card" onSubmit={createTest}><h2>Test oluştur</h2><select name="kind"><option value="PRE_TEST">Ön test</option><option value="POST_TEST">Son test</option></select><input name="title" placeholder="Başlık" required/><textarea name="questions" placeholder="Soru | doğru yanıt" required/><button>Oluştur ve aç</button></form><TestComparison comparison={comparison}/><button onClick={async()=>{const r=await call(`organizations/${organizationId}/events/${eventId}/assessments/comparison`,'GET');if(r)setComparison(r)}}>Karşılaştırmayı yenile</button>{assessments.map(a=><article className="workspace-card" key={a.id}><h3>{a.title}</h3><p>{a.kind==='PRE_TEST'?'Ön test':'Son test'} · {a._count.submissions} yanıt</p><button onClick={()=>copyTest(a)}>Diğer teste kopyala</button></article>)}</>}
 {tab==='feedback'&&<><form className="workspace-card" onSubmit={createFeedback}><h2>Geri bildirim</h2><input name="title" defaultValue="Etkinlik geri bildirimi"/><input name="question" defaultValue="Etkinliği 1–5 arasında puanlayın"/><button>Oluştur ve aç</button></form>{feedback.map(f=><article className="workspace-card" key={f.id}><h3>{f.title}</h3><p>{f._count.submissions} yanıt</p></article>)}</>}
 {tab==='notifications'&&<form className="workspace-card" onSubmit={async e=>{e.preventDefault();const d=new FormData(e.currentTarget);await call(`organizations/${organizationId}/events/${eventId}/notifications`,'POST',{title:d.get('title'),body:d.get('body')})}}><h2>Duyuru</h2><input name="title" required/><textarea name="body" required/><button>Gönder</button></form>}
 </section></>;
}
