'use client';
import { FormEvent, useState } from 'react';
import { ManualGroups } from './manual-groups';
import { TestComparison } from './test-comparison';

type Group={id:string;name:string;members:Array<{registration:{id:string;firstName:string;lastName:string}}>};
type Game={id:string;title:string;status:string;_count:{participants:number;responses:number}};
type Assessment={id:string;kind:'PRE_TEST'|'POST_TEST';title:string;open:boolean;_count:{submissions:number}};
type Feedback={id:string;title:string;open:boolean;_count:{submissions:number}};
type Feature={key:string;enabled:boolean}; type Person={id:string;firstName:string;lastName:string};
type Comparison={pre:{submissions:number;average:number|null};post:{submissions:number;average:number|null};improvement:number|null};

export function ModuleManager(p:{organizationId:string;eventId:string;initialGroups:Group[];initialGames:Game[];initialAssessments:Assessment[];initialFeedback:Feedback[];initialFeatures:Feature[];roster:Person[];initialComparison:Comparison}) {
 const {organizationId,eventId,roster}=p; const[tab,setTab]=useState('groups'),[groups,setGroups]=useState(p.initialGroups),[games,setGames]=useState(p.initialGames),[assessments,setAssessments]=useState(p.initialAssessments),[feedback,setFeedback]=useState(p.initialFeedback),[features,setFeatures]=useState(p.initialFeatures),[comparison,setComparison]=useState(p.initialComparison),[message,setMessage]=useState('');
 async function call(path:string,method='POST',body?:object){const response=await fetch(`/api/backend/${path}`,{method,headers:{'content-type':'application/json'},body:body?JSON.stringify(body):undefined});const data=await response.json();if(!response.ok){setMessage(Array.isArray(data.message)?data.message.join(' '):(data.message??'İşlem tamamlanamadı.'));return null}setMessage('İşlem tamamlandı.');return data}
 async function enable(key:string){if(features.find(x=>x.key===key)?.enabled)return true;const result=await call(`organizations/${organizationId}/events/${eventId}/features/${key}`,'PUT',{enabled:true,config:{}});if(result)setFeatures(v=>v.map(x=>x.key===key?{...x,enabled:true}:x));return Boolean(result)}
 async function generate(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!await enable('groups'))return;const d=new FormData(e.currentTarget),r=await call(`organizations/${organizationId}/events/${eventId}/groups/generate`,'POST',{count:Number(d.get('count')),strategy:d.get('strategy'),balanceField:d.get('balanceField')||undefined});if(r)setGroups(r)}
 async function saveManual(values:string[][]){if(!await enable('groups'))return false;const r=await call(`organizations/${organizationId}/events/${eventId}/groups/manual`,'POST',{groups:values});if(r)setGroups(r);return Boolean(r)}
 async function createGame(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!await enable('icebreaker'))return;const d=new FormData(e.currentTarget),created=await call(`organizations/${organizationId}/events/${eventId}/games`,'POST',{title:d.get('title'),prompt:d.get('prompt')});if(created){const opened=await call(`organizations/${organizationId}/game-sessions/${created.id}/open`);if(opened)setGames(v=>[{...created,status:'OPEN',_count:{participants:opened.assignments.length,responses:0}},...v])}}
 async function gameStatus(x:Game,action:'reveal'|'complete'){const r=await call(`organizations/${organizationId}/game-sessions/${x.id}/${action}`);if(r)setGames(v=>v.map(g=>g.id===x.id?{...g,status:r.status}:g))}
 async function createTest(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!await enable('assessments'))return;const d=new FormData(e.currentTarget),questions=String(d.get('questions')).split('\n').map((line,i)=>{const[label,correctAnswer]=line.split('|').map(x=>x.trim());return{id:`q${i+1}`,type:'single',label,correctAnswer}}).filter(x=>x.label&&x.correctAnswer);const created=await call(`organizations/${organizationId}/events/${eventId}/assessments`,'POST',{kind:d.get('kind'),title:d.get('title'),questions});if(created){await call(`organizations/${organizationId}/assessments/${created.id}/open`,'PATCH',{open:true});setAssessments(v=>[{...created,open:true,_count:{submissions:0}},...v])}}
 async function copyTest(x:Assessment){const kind=x.kind==='PRE_TEST'?'POST_TEST':'PRE_TEST',r=await call(`organizations/${organizationId}/assessments/${x.id}/copy`,'POST',{kind,title:`${x.title} — ${kind==='POST_TEST'?'Son test':'Ön test'}`});if(r)setAssessments(v=>[{...r,open:false,_count:{submissions:0}},...v])}
 async function createFeedback(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!await enable('feedback'))return;const d=new FormData(e.currentTarget),r=await call(`organizations/${organizationId}/events/${eventId}/feedback`,'POST',{title:d.get('title'),schema:{questions:[{id:'rating',type:'number',label:d.get('question')}]}});if(r){await call(`organizations/${organizationId}/feedback/${r.id}/open`,'PATCH',{open:true});setFeedback(v=>[{...r,open:true,_count:{submissions:0}},...v])}}
 const tabs=[['groups','Gruplar'],['game','Tanışma oyunu'],['tests','Testler'],['feedback','Geri bildirim'],['notifications','Duyurular']];
 const intro:{[k:string]:{title:string;desc:string}}={groups:{title:'Katılımcıları gruplara ayırın',desc:'Atölye veya küçük grup çalışmaları için katılımcıları otomatik veya elle gruplara bölün.'},game:{title:'Buz kırıcı tanışma oyunu',desc:'Katılımcıların birbirini tanıması için eğlenceli, etkileşimli bir oyun başlatın.'},tests:{title:'Ön test ve son test',desc:'Etkinlik öncesi ve sonrası bilgi düzeyini ölçün, değişimi karşılaştırın.'},feedback:{title:'Katılımcı geri bildirimi',desc:'Etkinlik hakkındaki görüşleri toplayın ve geliştirme noktalarını görün.'},notifications:{title:'Katılımcılara duyuru',desc:'Etkinlik alanındaki tüm katılımcılara anlık bildirim gönderin.'}};
 return <><nav className="workspace-tabs">{tabs.map(([k,l])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{l}</button>)}</nav>{intro[tab]&&<div className="section-intro"><h2>{intro[tab].title}</h2><p>{intro[tab].desc}</p></div>}{message&&<p className="notice">{message}</p>}<section className="module-workspace">
 {tab==='groups'&&<><form className="workspace-card" onSubmit={generate}><div className="section-intro"><h2>Otomatik gruplama</h2><p>Sistem, katılımcıları seçtiğiniz sayıda gruba böler.</p></div><label>Grup sayısı<input name="count" type="number" min="1" defaultValue="2"/></label><label>Dağıtım yöntemi<select name="strategy"><option value="RANDOM">Rastgele — karışık dağıt</option><option value="BALANCED">Dengeli — ölçüte göre</option></select></label><label>Denge ölçütü <span className="tooltip" data-tip="Dengeli dağıtımda grupları homojenleştirmek için kayıt formundaki bir alanı seçin. Örneğin kurum, şehir veya deneyim seviyesi.">(?)</span><input name="balanceField" placeholder="Örn. kurum, şehir (isteğe bağlı)"/></label><button className="primary">Grupları oluştur</button></form><div className="group-board">{groups.map(g=><article className="workspace-card" key={g.id}><h3>{g.name}</h3>{g.members.map(m=><span className="participant-chip" key={m.registration.id}>{m.registration.firstName} {m.registration.lastName}</span>)}</article>)}</div><ManualGroups people={roster} initial={groups.map(g=>g.members.map(m=>m.registration.id))} onSave={saveManual}/></>}
 {tab==='game'&&<><form className="workspace-card" onSubmit={createGame}><div className="section-intro"><h2>Tanışma oyunu başlat</h2><p>“Başkasının yanıtını oku” oyunu: herkese bir soru sorulur, yanıtlar toplanır, sonra herkes başka birinin yanıtını okur.</p></div><label>Oyun başlığı<input name="title" defaultValue="Başkasının Yanıtını Oku"/></label><label>Katılımcılara sorulacak soru<textarea name="prompt" required placeholder="Örn. Bu etkinlikten en çok ne bekliyorsunuz?"/></label><button className="primary">Oluştur ve katılımcılara aç</button><small className="field-help">Oyun açıldığında katılımcılar alanlarından yanıt verebilir. Yeterli yanıt toplanınca “Yanıtları göster” ile paylaşım aşamasına geçebilirsiniz.</small></form>{games.map(g=><article className="workspace-card" key={g.id}><h3>{g.title}</h3><p>{g.status} · {g._count.responses}/{g._count.participants} yanıt</p>{g.status==='OPEN'&&<button className="primary" onClick={()=>gameStatus(g,'reveal')}>Yanıtları göster</button>}{g.status==='REVEAL'&&<button className="primary" onClick={()=>gameStatus(g,'complete')}>Oyunu tamamla</button>}</article>)}</>}
 {tab==='tests'&&<><form className="workspace-card" onSubmit={createTest}><div className="section-intro"><h2>Test oluşturun</h2><p>Her satıra bir soru ve doğru yanıtını yazın. Test oluşturulur oluşturulmaz katılımcılara açılır.</p></div><label>Test türü<select name="kind"><option value="PRE_TEST">Ön test — etkinlik öncesi</option><option value="POST_TEST">Son test — etkinlik sonrası</option></select></label><label>Test başlığı<input name="title" placeholder="Örn. Etkinlik bilgi testi" required/></label><label>Sorular <span className="tooltip" data-tip="Her satıra: Soru metni | doğru yanıt. Örnek: Türkiye'nin başkenti neresidir? | Ankara">(?)</span><textarea name="questions" required placeholder={"Etkinliğin ana teması nedir? | Sürdürülebilirlik\nHangi yıl Paris Anlaşması imzalandı? | 2015"}/></label><button className="primary">Oluştur ve aç</button></form><TestComparison comparison={comparison}/><button onClick={async()=>{const r=await call(`organizations/${organizationId}/events/${eventId}/assessments/comparison`,'GET');if(r)setComparison(r)}}>Karşılaştırmayı yenile</button>{assessments.map(a=><article className="workspace-card" key={a.id}><h3>{a.title}</h3><p>{a.kind==='PRE_TEST'?'Ön test':'Son test'} · {a._count.submissions} yanıt</p><button onClick={()=>copyTest(a)}>Diğer teste kopyala</button></article>)}</>}
 {tab==='feedback'&&<><form className="workspace-card" onSubmit={createFeedback}><div className="section-intro"><h2>Geri bildirim formu açın</h2><p>Katılımcılar 1–5 arası puan verir. Sonuçları toplayıp değerlendirebilirsiniz.</p></div><label>Form başlığı<input name="title" defaultValue="Etkinlik geri bildirimi"/></label><label>Soru<input name="question" defaultValue="Etkinliği 1–5 arasında puanlayın"/></label><button className="primary">Oluştur ve aç</button></form>{feedback.map(f=><article className="workspace-card" key={f.id}><h3>{f.title}</h3><p>{f._count.submissions} yanıt</p></article>)}</>}
 {tab==='notifications'&&<form className="workspace-card" onSubmit={async e=>{e.preventDefault();const d=new FormData(e.currentTarget);await call(`organizations/${organizationId}/events/${eventId}/notifications`,'POST',{title:d.get('title'),body:d.get('body')})}}><div className="section-intro"><h2>Duyuru gönderin</h2><p>Bu mesaj etkinlik alanını açmış tüm katılımcılara anlık bildirim olarak gider.</p></div><label>Başlık<input name="title" required placeholder="Örn. Öğle arası saati değişti"/></label><label>Mesaj<textarea name="body" required placeholder="Kısa ve net bir duyuru yazın."/></label><button className="primary">Duyuruyu gönder</button></form>}
 </section></>;
}
